export const fallbackServices = [
  {
    id: "fallback-invisible-grills",
    slug: "invisible-grills",
    name: "Invisible Grills",
    shortName: null,
    description: "SS304 stainless steel invisible grills for balconies and windows.",
    category: "Grills",
    keywords: ["invisible grills"],
    imageSlug: "invisible-grills",
    sortOrder: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fallback-safety-nets",
    slug: "safety-nets",
    name: "Safety Nets",
    shortName: null,
    description: "Heavy-duty balcony and terrace safety nets.",
    category: "Nets",
    keywords: ["safety nets"],
    imageSlug: "safety-nets",
    sortOrder: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fallback-mosquito-nets",
    slug: "mosquito-nets",
    name: "Mosquito Nets",
    shortName: null,
    description: "Frameless mosquito nets for windows and doors.",
    category: "Nets",
    keywords: ["mosquito nets"],
    imageSlug: "mosquito-nets",
    sortOrder: 3,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fallback-cloth-hangers",
    slug: "cloth-hangers",
    name: "Cloth Hangers",
    shortName: null,
    description: "Ceiling cloth drying hangers for apartments.",
    category: "Hangers",
    keywords: ["cloth hangers"],
    imageSlug: "cloth-hangers",
    sortOrder: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fallback-sports-nets",
    slug: "sports-nets",
    name: "Sports Nets",
    shortName: null,
    description: "Cricket and multi-sport practice nets.",
    category: "Sports",
    keywords: ["sports nets"],
    imageSlug: "sports-nets",
    sortOrder: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fallback-bird-spikes",
    slug: "bird-spikes",
    name: "Bird Spikes",
    shortName: null,
    description: "Humane bird spike installation.",
    category: "Bird Control",
    keywords: ["bird spikes"],
    imageSlug: "bird-protection-nets",
    sortOrder: 6,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const fallbackCities = [
  {
    id: "fallback-hyderabad",
    slug: "hyderabad",
    name: "Hyderabad",
    type: "CITY" as const,
    parentId: null,
    citySlug: null,
    areaSlug: null,
    state: "Telangana",
    pincode: null,
    latitude: null,
    longitude: null,
    description: "Professional invisible grills and safety solutions across Hyderabad.",
    keywords: ["Hyderabad"],
    sortOrder: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [] as { slug: string; name: string }[],
  },
  {
    id: "fallback-chennai",
    slug: "chennai",
    name: "Chennai",
    type: "CITY" as const,
    parentId: null,
    citySlug: null,
    areaSlug: null,
    state: "Tamil Nadu",
    pincode: null,
    latitude: null,
    longitude: null,
    description: "Professional invisible grills and safety solutions across Chennai.",
    keywords: ["Chennai"],
    sortOrder: 2,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    children: [] as { slug: string; name: string }[],
  },
];

export type FallbackService = (typeof fallbackServices)[number];
export type FallbackCity = (typeof fallbackCities)[number];
