/**
 * Generates src/data/chennai-areas.ts from scripts/chennai-localities.raw.txt
 * Run: npm run areas:generate:chennai
 */
import { readFileSync, writeFileSync } from "node:fs";
import { slugify } from "../src/lib/slug";
import { getChennaiZoneId } from "../src/config/chennai-zones";

const RAW_PATH = new URL("./chennai-localities.raw.txt", import.meta.url);

function displayName(raw: string): string {
  return raw
    .split(/\s+/)
    .map((w) => {
      const u = w.toUpperCase();
      if (["ECR", "OMR", "CMBT", "DLF", "ICF", "MCC", "MGR", "MKB", "KK", "RA", "RK"].includes(u)) {
        return u;
      }
      if (u === "DR.") return "Dr.";
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    })
    .join(" ")
    .replace(/\bDr\./g, "Dr.")
    .replace(/\bT\. Nagar\b/g, "T. Nagar")
    .replace(/\bK\.K\./g, "K.K.")
    .replace(/\bM\.G\.R\./g, "M.G.R.")
    .replace(/\bR\.A\./g, "R.A.")
    .replace(/\bR\.K\./g, "R.K.");
}

const CANONICAL_SLUG: Record<string, string> = {
  "guduvanchery": "guduvancheri",
  "tirusulam": "tirusulam",
  "tharamani": "taramani",
  "thiruvanmiyur": "thiruvanmiyur",
  "mugappair": "mogappair",
  "purasaiwakkam": "purasawalkam",
  "parrys": "parrys-corner",
  "parrys-corner": "parrys",
};

function canonicalSlug(raw: string): string {
  const base = slugify(raw);
  return CANONICAL_SLUG[base] ?? base;
}

function getPriorityTier(slug: string): 1 | 2 | 3 {
  const tier1 = new Set([
    "adyar", "velachery", "anna-nagar", "t-nagar", "nungambakkam", "mylapore",
    "porur", "omr", "sholinganallur", "thoraipakkam", "tambaram", "chromepet",
    "pallavaram", "medavakkam", "perungudi", "guindy", "kilpauk", "besant-nagar",
    "thiruvanmiyur", "koyambedu", "vadapalani", "ambattur", "mogappair", "ecr-neelankarai",
  ]);
  const tier2 = new Set([
    "injambakkam", "navalur", "siruseri", "palavakkam", "royapettah", "egmore",
    "valasaravakkam", "virugambakkam", "avadi", "pallikaranai", "selaiyur", "guduvancheri",
    "chengalpattu", "madipakkam", "kk-nagar", "ashok-nagar", "saidapet", "alandur",
  ]);
  if (tier1.has(slug) || slug.includes("omr") || slug.includes("anna-nagar")) return 1;
  if (tier2.has(slug)) return 2;
  return 3;
}

const rawText = readFileSync(RAW_PATH, "utf8");
const seen = new Map<string, { slug: string; name: string }>();

for (const line of rawText.split(/\r?\n/)) {
  const raw = line.trim();
  if (!raw) continue;
  const slug = canonicalSlug(raw);
  if (!slug) continue;
  const name = displayName(raw);
  const existing = seen.get(slug);
  if (!existing || name.length < existing.name.length) {
    seen.set(slug, { slug, name });
  }
}

const areas = [...seen.values()].map((a, i) => ({
  slug: a.slug,
  name: a.name,
  zone: getChennaiZoneId(a.slug),
  sortOrder: i + 1,
  priorityTier: getPriorityTier(a.slug),
}));

const out = `/** Auto-generated by scripts/generate-chennai-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface ChennaiArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const CHENNAI_AREAS: ChennaiArea[] = ${JSON.stringify(areas, null, 2)};

export const CHENNAI_AREA_COUNT = ${areas.length};

export function getChennaiAreaBySlug(slug: string): ChennaiArea | undefined {
  return CHENNAI_AREAS.find((a) => a.slug === slug);
}
`;

writeFileSync(new URL("../src/data/chennai-areas.ts", import.meta.url), out, "utf8");
console.log(`Wrote ${areas.length} Chennai areas to src/data/chennai-areas.ts`);
