/**
 * Generates src/data/coimbatore-areas.ts from scripts/coimbatore-localities.raw.txt
 * Run: npm run areas:generate:coimbatore
 */
import { readFileSync, writeFileSync } from "node:fs";
import { slugify } from "../src/lib/slug";
import { getCoimbatoreZoneId } from "../src/config/coimbatore-zones";

const RAW_PATH = new URL("./coimbatore-localities.raw.txt", import.meta.url);

function displayName(raw: string): string {
  return raw
    .split(/\s+/)
    .map((w) => {
      const u = w.toUpperCase();
      if (["ECR", "OMR", "CMBT", "DLF", "ICF", "MCC", "MGR", "MKB", "KK", "RA", "RK", "NSR", "TVR", "CHIL", "SEZ", "SIDCO", "PSG", "FCI", "ESI", "HUDCO", "NGO", "NGR", "NKR", "NRI", "ATT", "KGISL", "VGP", "VOC"].includes(u)) {
        return u;
      }
      if (u === "DR.") return "Dr.";
      if (u === "R.S.") return "R.S.";
      if (u === "K.K.") return "K.K.";
      if (u === "K.R.G.") return "K.R.G.";
      if (u === "G.N.") return "G.N.";
      if (u === "P.N.") return "P.N.";
      if (u === "T.") return "T.";
      if (u === "V.K.") return "V.K.";
      if (u === "V.G.") return "V.G.";
      if (u === "E.B.") return "E.B.";
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    })
    .join(" ")
    .replace(/\bDr\./g, "Dr.")
    .replace(/\bR\.S\./g, "R.S.")
    .replace(/\bK\.K\./g, "K.K.")
    .replace(/\bG\.N\./g, "G.N.")
    .replace(/\bP\.N\./g, "P.N.")
    .replace(/\bT\. Kottampatti\b/g, "T. Kottampatti")
    .replace(/\bT\.V\.S\./g, "T.V.S.");
}

const CANONICAL_SLUG: Record<string, string> = {
  "rs-puram": "rs-puram",
  "r-s-puram": "rs-puram",
  "dhalyur": "dhaliyur",
  "odayakulam": "odaiyakulam",
  "villankurichi-road": "vilankurichi-road",
};

function canonicalSlug(raw: string): string {
  const base = slugify(raw);
  return CANONICAL_SLUG[base] ?? base;
}

function getPriorityTier(slug: string): 1 | 2 | 3 {
  const tier1 = new Set([
    "gandhipuram", "peelamedu", "saibaba-colony", "rs-puram", "singanallur",
    "saravanampatti", "race-course", "ramanathapuram", "vadavalli", "kurichi",
    "kuniyamuthur", "vilankurichi", "kalapatti", "avinashi-road", "ukkadam",
    "podanur", "thudiyalur", "kovaipudur", "pollachi", "mettupalayam",
  ]);
  const tier2 = new Set([
    "tidel-park-coimbatore-area", "keeranatham", "sulur", "irugur", "ondipudur",
    "uppilipalayam", "kavundampalayam", "ganapathy", "sivananda-colony",
    "brookefields-area", "psg-tech-area", "annur", "karamadai", "eachanari",
  ]);
  if (tier1.has(slug) || slug.includes("gandhipuram") || slug.includes("peelamedu")) return 1;
  if (tier2.has(slug)) return 2;
  return 3;
}

const rawText = readFileSync(RAW_PATH, "utf8");
const seen = new Map<string, { slug: string; name: string }>();

for (const line of rawText.split(/\r?\n/)) {
  const raw = line.trim();
  if (!raw) continue;
  const slug = canonicalSlug(raw);
  if (!slug) continue;
  const name = displayName(raw);
  const existing = seen.get(slug);
  if (!existing || name.length < existing.name.length) {
    seen.set(slug, { slug, name });
  }
}

const areas = [...seen.values()].map((a, i) => ({
  slug: a.slug,
  name: a.name,
  zone: getCoimbatoreZoneId(a.slug),
  sortOrder: i + 1,
  priorityTier: getPriorityTier(a.slug),
}));

const out = `/** Auto-generated by scripts/generate-coimbatore-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface CoimbatoreArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const COIMBATORE_AREAS: CoimbatoreArea[] = ${JSON.stringify(areas, null, 2)};

export const COIMBATORE_AREA_COUNT = ${areas.length};

export function getCoimbatoreAreaBySlug(slug: string): CoimbatoreArea | undefined {
  return COIMBATORE_AREAS.find((a) => a.slug === slug);
}
`;

writeFileSync(new URL("../src/data/coimbatore-areas.ts", import.meta.url), out, "utf8");
console.log(`Wrote ${areas.length} Coimbatore areas to src/data/coimbatore-areas.ts`);
