/**
 * Generates src/data/kochi-areas.ts from scripts/kochi-localities.raw.txt
 * Run: npm run areas:generate:kochi
 */
import { readFileSync, writeFileSync } from "node:fs";
import { slugify } from "../src/lib/slug";
import { getKochiZoneId } from "../src/config/kochi-zones";

const RAW_PATH = new URL("./kochi-localities.raw.txt", import.meta.url);

function displayName(raw: string): string {
  return raw
    .split(/\s+/)
    .map((w) => {
      const u = w.toUpperCase();
      if (["MG", "NH", "BTS", "CUSAT", "FACT", "HMT", "JN", "KP", "NAD", "NGO", "SN", "SRM", "UC"].includes(u)) {
        return u;
      }
      if (u === "DR.") return "Dr.";
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    })
    .join(" ")
    .replace(/\bMG Road\b/g, "MG Road")
    .replace(/\bKP Vallon\b/g, "KP Vallon");
}

const CANONICAL_SLUG: Record<string, string> = {
  "kumbalanghi": "kumbalangi",
};

function canonicalSlug(raw: string): string {
  const base = slugify(raw);
  return CANONICAL_SLUG[base] ?? base;
}

function getPriorityTier(slug: string): 1 | 2 | 3 {
  const tier1 = new Set([
    "kakkanad", "edappally", "vyttila", "ernakulam-central", "fort-kochi",
    "aluva", "infopark-kochi", "kaloor", "kadavanthra", "palarivattom",
    "maradu", "tripunithura", "mattancherry", "kalamassery", "panampilly-nagar",
    "lulu-mall-area", "mg-road-kochi",
  ]);
  const tier2 = new Set([
    "angamaly", "nedumbassery", "thrikkakara", "elamkulam", "kundannoor",
    "kumbalangi", "cherai", "perumbavoor", "north-paravur", "smartcity-kochi",
    "infopark-phase-1", "infopark-phase-2", "cochin-international-airport-area",
  ]);
  if (tier1.has(slug) || slug.includes("kakkanad") || slug.includes("infopark")) return 1;
  if (tier2.has(slug)) return 2;
  return 3;
}

const rawText = readFileSync(RAW_PATH, "utf8");
const seen = new Map<string, { slug: string; name: string }>();

for (const line of rawText.split(/\r?\n/)) {
  const raw = line.trim();
  if (!raw) continue;
  const slug = canonicalSlug(raw);
  if (!slug) continue;
  const name = displayName(raw);
  const existing = seen.get(slug);
  if (!existing || name.length < existing.name.length) {
    seen.set(slug, { slug, name });
  }
}

const areas = [...seen.values()].map((a, i) => ({
  slug: a.slug,
  name: a.name,
  zone: getKochiZoneId(a.slug),
  sortOrder: i + 1,
  priorityTier: getPriorityTier(a.slug),
}));

const out = `/** Auto-generated by scripts/generate-kochi-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface KochiArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const KOCHI_AREAS: KochiArea[] = ${JSON.stringify(areas, null, 2)};

export const KOCHI_AREA_COUNT = ${areas.length};

export function getKochiAreaBySlug(slug: string): KochiArea | undefined {
  return KOCHI_AREAS.find((a) => a.slug === slug);
}
`;

writeFileSync(new URL("../src/data/kochi-areas.ts", import.meta.url), out, "utf8");
console.log(`Wrote ${areas.length} Kochi areas to src/data/kochi-areas.ts`);
