/**
 * Generates src/data/chhattisgarh-areas.ts from scripts/chhattisgarh-localities.raw.txt
 * Run: npm run areas:generate:chhattisgarh
 */
import { readFileSync, writeFileSync } from "node:fs";
import { slugify } from "../src/lib/slug";
import { getChhattisgarhZoneId } from "../src/config/chhattisgarh-zones";

const RAW_PATH = new URL("./chhattisgarh-localities.raw.txt", import.meta.url);

const DISPLAY_NAME_BY_SLUG: Record<string, string> = {
  "gaurela-pendra-marwahi": "Gaurela-Pendra-Marwahi",
  "khairagarh-chhuikhadan-gandai": "Khairagarh-Chhuikhadan-Gandai",
  "manendragarh-chirmiri-bharatpur": "Manendragarh-Chirmiri-Bharatpur",
  "mohla-manpur-ambagarh-chowki": "Mohla-Manpur-Ambagarh Chowki",
  "baloda-bazar-bhatapara": "Baloda Bazar-Bhatapara",
  "balrampur-ramanujganj": "Balrampur-Ramanujganj",
  "janjgir-champa": "Janjgir-Champa",
  "sarangarh-bilaigarh": "Sarangarh-Bilaigarh",
  "vip-road": "VIP Road",
  "atal-nagar": "Atal Nagar",
  "naya-raipur": "Naya Raipur",
  "balco-nagar": "BALCO Nagar",
  "bhilai-3": "Bhilai-3",
  "tilda-newra": "Tilda Newra",
  "gobra-nawapara": "Gobra Nawapara",
  "jashpur-nagar": "Jashpur Nagar",
  "ambagarh-chowki": "Ambagarh Chowki",
  "kota-raipur": "Kota, Raipur",
  "civil-lines-raipur": "Civil Lines, Raipur",
  "nehru-nagar-bhilai": "Nehru Nagar, Bhilai",
  "power-house-bhilai": "Power House, Bhilai",
  "civic-centre": "Civic Centre",
  "naila-janjgir": "Naila Janjgir",
  "dondi-lohara": "Dondi Lohara",
  "pendra-road": "Pendra Road",
  "pachpedi-naka": "Pachpedi Naka",
  "vyapar-vihar": "Vyapar Vihar",
};

const CANONICAL_SLUG: Record<string, string> = {
  gariyaband: "gariaband",
  korea: "koriya",
  gaurella: "gaurela",
  "gaurella-pendra-marwahi": "gaurela-pendra-marwahi",
  kabeerdham: "kabirdham",
};

function titleCaseWords(raw: string): string {
  return raw
    .split(/[\s-]+/)
    .filter(Boolean)
    .map((w) => {
      const upper = w.toUpperCase();
      if (["VIP", "BALCO"].includes(upper)) return upper;
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    })
    .join(" ");
}

function canonicalSlug(raw: string): string {
  const base = slugify(raw);
  return CANONICAL_SLUG[base] ?? base;
}

function displayName(raw: string, slug: string): string {
  if (DISPLAY_NAME_BY_SLUG[slug]) return DISPLAY_NAME_BY_SLUG[slug]!;
  return titleCaseWords(raw);
}

function getPriorityTier(slug: string): 1 | 2 | 3 {
  const tier1 = new Set([
    "raipur",
    "bhilai",
    "durg",
    "bilaspur",
    "korba",
    "naya-raipur",
    "shankar-nagar",
    "telibandha",
  ]);
  const tier2 = new Set([
    "rajnandgaon",
    "raigarh",
    "jagdalpur",
    "ambikapur",
    "dhamtari",
    "mahasamund",
    "atal-nagar",
    "bhatapara",
    "dongargarh",
    "champa",
    "janjgir",
    "kawardha",
    "risali",
    "charoda",
    "sarkanda",
  ]);
  if (tier1.has(slug)) return 1;
  if (tier2.has(slug)) return 2;
  return 3;
}

const rawText = readFileSync(RAW_PATH, "utf8");
const seen = new Map<string, { slug: string; name: string }>();

for (const line of rawText.split(/\r?\n/)) {
  const raw = line.trim();
  if (!raw) continue;
  const slug = canonicalSlug(raw);
  if (!slug) continue;
  const name = displayName(raw, slug);
  const existing = seen.get(slug);
  if (!existing || name.length > existing.name.length) {
    seen.set(slug, { slug, name });
  }
}

const areas = [...seen.values()].map((a, i) => ({
  slug: a.slug,
  name: a.name,
  zone: getChhattisgarhZoneId(a.slug),
  sortOrder: i + 1,
  priorityTier: getPriorityTier(a.slug),
}));

const out = `/** Auto-generated by scripts/generate-chhattisgarh-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface ChhattisgarhArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const CHHATTISGARH_AREAS: ChhattisgarhArea[] = ${JSON.stringify(areas, null, 2)};

export const CHHATTISGARH_AREA_COUNT = ${areas.length};

export function getChhattisgarhAreaBySlug(slug: string): ChhattisgarhArea | undefined {
  return CHHATTISGARH_AREAS.find((a) => a.slug === slug);
}
`;

writeFileSync(new URL("../src/data/chhattisgarh-areas.ts", import.meta.url), out, "utf8");
console.log(`Wrote ${areas.length} Chhattisgarh areas to src/data/chhattisgarh-areas.ts`);
