/** Auto-generated by scripts/generate-chennai-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface ChennaiArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const CHENNAI_AREAS: ChennaiArea[] = [
  {
    "slug": "aadhanur",
    "name": "Aadhanur",
    "zone": "central-chennai",
    "sortOrder": 1,
    "priorityTier": 3
  },
  {
    "slug": "abhiramapuram",
    "name": "Abhiramapuram",
    "zone": "central-chennai",
    "sortOrder": 2,
    "priorityTier": 3
  },
  {
    "slug": "abirami-nagar",
    "name": "Abirami Nagar",
    "zone": "central-chennai",
    "sortOrder": 3,
    "priorityTier": 3
  },
  {
    "slug": "adambakkam",
    "name": "Adambakkam",
    "zone": "central-chennai",
    "sortOrder": 4,
    "priorityTier": 3
  },
  {
    "slug": "adyar",
    "name": "Adyar",
    "zone": "south-chennai",
    "sortOrder": 5,
    "priorityTier": 1
  },
  {
    "slug": "adyar-gandhi-nagar",
    "name": "Adyar Gandhi Nagar",
    "zone": "central-chennai",
    "sortOrder": 6,
    "priorityTier": 3
  },
  {
    "slug": "adyar-indira-nagar",
    "name": "Adyar Indira Nagar",
    "zone": "central-chennai",
    "sortOrder": 7,
    "priorityTier": 3
  },
  {
    "slug": "adyar-karpagam-gardens",
    "name": "Adyar Karpagam Gardens",
    "zone": "central-chennai",
    "sortOrder": 8,
    "priorityTier": 3
  },
  {
    "slug": "adyar-kasturba-nagar",
    "name": "Adyar Kasturba Nagar",
    "zone": "central-chennai",
    "sortOrder": 9,
    "priorityTier": 3
  },
  {
    "slug": "adyar-signal",
    "name": "Adyar Signal",
    "zone": "central-chennai",
    "sortOrder": 10,
    "priorityTier": 3
  },
  {
    "slug": "agaram",
    "name": "Agaram",
    "zone": "central-chennai",
    "sortOrder": 11,
    "priorityTier": 3
  },
  {
    "slug": "agaram-perambur",
    "name": "Agaram Perambur",
    "zone": "central-chennai",
    "sortOrder": 12,
    "priorityTier": 3
  },
  {
    "slug": "agaramthen",
    "name": "Agaramthen",
    "zone": "central-chennai",
    "sortOrder": 13,
    "priorityTier": 3
  },
  {
    "slug": "agastheswarar-nagar",
    "name": "Agastheswarar Nagar",
    "zone": "central-chennai",
    "sortOrder": 14,
    "priorityTier": 3
  },
  {
    "slug": "agatheswaram",
    "name": "Agatheswaram",
    "zone": "central-chennai",
    "sortOrder": 15,
    "priorityTier": 3
  },
  {
    "slug": "akkarai",
    "name": "Akkarai",
    "zone": "ecr-coast",
    "sortOrder": 16,
    "priorityTier": 3
  },
  {
    "slug": "akkarai-ecr",
    "name": "Akkarai ECR",
    "zone": "ecr-coast",
    "sortOrder": 17,
    "priorityTier": 3
  },
  {
    "slug": "alamathi",
    "name": "Alamathi",
    "zone": "central-chennai",
    "sortOrder": 18,
    "priorityTier": 3
  },
  {
    "slug": "alandur",
    "name": "Alandur",
    "zone": "central-chennai",
    "sortOrder": 19,
    "priorityTier": 2
  },
  {
    "slug": "alapakkam",
    "name": "Alapakkam",
    "zone": "central-chennai",
    "sortOrder": 20,
    "priorityTier": 3
  },
  {
    "slug": "alapakkam-porur",
    "name": "Alapakkam Porur",
    "zone": "west-chennai",
    "sortOrder": 21,
    "priorityTier": 3
  },
  {
    "slug": "alwarpet",
    "name": "Alwarpet",
    "zone": "central-chennai",
    "sortOrder": 22,
    "priorityTier": 3
  },
  {
    "slug": "alwarthirunagar",
    "name": "Alwarthirunagar",
    "zone": "central-chennai",
    "sortOrder": 23,
    "priorityTier": 3
  },
  {
    "slug": "alwarthirunagar-annex",
    "name": "Alwarthirunagar Annex",
    "zone": "central-chennai",
    "sortOrder": 24,
    "priorityTier": 3
  },
  {
    "slug": "ambattur",
    "name": "Ambattur",
    "zone": "north-chennai",
    "sortOrder": 25,
    "priorityTier": 1
  },
  {
    "slug": "ambattur-industrial-estate",
    "name": "Ambattur Industrial Estate",
    "zone": "north-chennai",
    "sortOrder": 26,
    "priorityTier": 3
  },
  {
    "slug": "aminjikarai",
    "name": "Aminjikarai",
    "zone": "central-chennai",
    "sortOrder": 27,
    "priorityTier": 3
  },
  {
    "slug": "aminjikarai-east",
    "name": "Aminjikarai East",
    "zone": "central-chennai",
    "sortOrder": 28,
    "priorityTier": 3
  },
  {
    "slug": "anakaputhur",
    "name": "Anakaputhur",
    "zone": "central-chennai",
    "sortOrder": 29,
    "priorityTier": 3
  },
  {
    "slug": "andarkuppam",
    "name": "Andarkuppam",
    "zone": "central-chennai",
    "sortOrder": 30,
    "priorityTier": 3
  },
  {
    "slug": "anna-flyover",
    "name": "Anna Flyover",
    "zone": "central-chennai",
    "sortOrder": 31,
    "priorityTier": 3
  },
  {
    "slug": "anna-nagar",
    "name": "Anna Nagar",
    "zone": "central-chennai",
    "sortOrder": 32,
    "priorityTier": 1
  },
  {
    "slug": "anna-nagar-east",
    "name": "Anna Nagar East",
    "zone": "central-chennai",
    "sortOrder": 33,
    "priorityTier": 1
  },
  {
    "slug": "anna-nagar-roundtana",
    "name": "Anna Nagar Roundtana",
    "zone": "central-chennai",
    "sortOrder": 34,
    "priorityTier": 1
  },
  {
    "slug": "anna-nagar-shanthi-colony",
    "name": "Anna Nagar Shanthi Colony",
    "zone": "central-chennai",
    "sortOrder": 35,
    "priorityTier": 1
  },
  {
    "slug": "anna-nagar-tower",
    "name": "Anna Nagar Tower",
    "zone": "central-chennai",
    "sortOrder": 36,
    "priorityTier": 1
  },
  {
    "slug": "anna-nagar-west",
    "name": "Anna Nagar West",
    "zone": "central-chennai",
    "sortOrder": 37,
    "priorityTier": 1
  },
  {
    "slug": "anna-nagar-west-extension",
    "name": "Anna Nagar West Extension",
    "zone": "central-chennai",
    "sortOrder": 38,
    "priorityTier": 1
  },
  {
    "slug": "anna-salai",
    "name": "Anna Salai",
    "zone": "central-chennai",
    "sortOrder": 39,
    "priorityTier": 3
  },
  {
    "slug": "annanoor",
    "name": "Annanoor",
    "zone": "central-chennai",
    "sortOrder": 40,
    "priorityTier": 3
  },
  {
    "slug": "arakkambakkam",
    "name": "Arakkambakkam",
    "zone": "central-chennai",
    "sortOrder": 41,
    "priorityTier": 3
  },
  {
    "slug": "arambakkam",
    "name": "Arambakkam",
    "zone": "central-chennai",
    "sortOrder": 42,
    "priorityTier": 3
  },
  {
    "slug": "arani",
    "name": "Arani",
    "zone": "central-chennai",
    "sortOrder": 43,
    "priorityTier": 3
  },
  {
    "slug": "arumbakkam",
    "name": "Arumbakkam",
    "zone": "central-chennai",
    "sortOrder": 44,
    "priorityTier": 3
  },
  {
    "slug": "ashok-nagar",
    "name": "Ashok Nagar",
    "zone": "central-chennai",
    "sortOrder": 45,
    "priorityTier": 2
  },
  {
    "slug": "ashok-pillar",
    "name": "Ashok Pillar",
    "zone": "central-chennai",
    "sortOrder": 46,
    "priorityTier": 3
  },
  {
    "slug": "aspiran-garden",
    "name": "Aspiran Garden",
    "zone": "central-chennai",
    "sortOrder": 47,
    "priorityTier": 3
  },
  {
    "slug": "athipattu",
    "name": "Athipattu",
    "zone": "central-chennai",
    "sortOrder": 48,
    "priorityTier": 3
  },
  {
    "slug": "athipattu-pudunagar",
    "name": "Athipattu Pudunagar",
    "zone": "central-chennai",
    "sortOrder": 49,
    "priorityTier": 3
  },
  {
    "slug": "avadi",
    "name": "Avadi",
    "zone": "north-chennai",
    "sortOrder": 50,
    "priorityTier": 2
  },
  {
    "slug": "avadi-camp",
    "name": "Avadi Camp",
    "zone": "north-chennai",
    "sortOrder": 51,
    "priorityTier": 3
  },
  {
    "slug": "avadi-iaf",
    "name": "Avadi Iaf",
    "zone": "north-chennai",
    "sortOrder": 52,
    "priorityTier": 3
  },
  {
    "slug": "ayanambakkam",
    "name": "Ayanambakkam",
    "zone": "central-chennai",
    "sortOrder": 53,
    "priorityTier": 3
  },
  {
    "slug": "ayanambakkam-extension",
    "name": "Ayanambakkam Extension",
    "zone": "central-chennai",
    "sortOrder": 54,
    "priorityTier": 3
  },
  {
    "slug": "ayanavaram",
    "name": "Ayanavaram",
    "zone": "central-chennai",
    "sortOrder": 55,
    "priorityTier": 3
  },
  {
    "slug": "ayappakkam",
    "name": "Ayappakkam",
    "zone": "central-chennai",
    "sortOrder": 56,
    "priorityTier": 3
  },
  {
    "slug": "ayyappanthangal",
    "name": "Ayyappanthangal",
    "zone": "central-chennai",
    "sortOrder": 57,
    "priorityTier": 3
  },
  {
    "slug": "azeez-nagar",
    "name": "Azeez Nagar",
    "zone": "central-chennai",
    "sortOrder": 58,
    "priorityTier": 3
  },
  {
    "slug": "bakthavatsala-nagar",
    "name": "Bakthavatsala Nagar",
    "zone": "central-chennai",
    "sortOrder": 59,
    "priorityTier": 3
  },
  {
    "slug": "balfour-road",
    "name": "Balfour Road",
    "zone": "central-chennai",
    "sortOrder": 60,
    "priorityTier": 3
  },
  {
    "slug": "basin-bridge",
    "name": "Basin Bridge",
    "zone": "central-chennai",
    "sortOrder": 61,
    "priorityTier": 3
  },
  {
    "slug": "besant-nagar",
    "name": "Besant Nagar",
    "zone": "south-chennai",
    "sortOrder": 62,
    "priorityTier": 1
  },
  {
    "slug": "besant-nagar-kalakshetra-colony",
    "name": "Besant Nagar Kalakshetra Colony",
    "zone": "central-chennai",
    "sortOrder": 63,
    "priorityTier": 3
  },
  {
    "slug": "besant-nagar-sastri-nagar",
    "name": "Besant Nagar Sastri Nagar",
    "zone": "central-chennai",
    "sortOrder": 64,
    "priorityTier": 3
  },
  {
    "slug": "bharathi-nagar",
    "name": "Bharathi Nagar",
    "zone": "central-chennai",
    "sortOrder": 65,
    "priorityTier": 3
  },
  {
    "slug": "bharathi-nagar-selaiyur",
    "name": "Bharathi Nagar Selaiyur",
    "zone": "central-chennai",
    "sortOrder": 66,
    "priorityTier": 3
  },
  {
    "slug": "bharathipuram",
    "name": "Bharathipuram",
    "zone": "central-chennai",
    "sortOrder": 67,
    "priorityTier": 3
  },
  {
    "slug": "bharathipuram-chromepet",
    "name": "Bharathipuram Chromepet",
    "zone": "south-suburbs",
    "sortOrder": 68,
    "priorityTier": 3
  },
  {
    "slug": "bharathiyar-nagar",
    "name": "Bharathiyar Nagar",
    "zone": "central-chennai",
    "sortOrder": 69,
    "priorityTier": 3
  },
  {
    "slug": "brick-kiln-road",
    "name": "Brick Kiln Road",
    "zone": "central-chennai",
    "sortOrder": 70,
    "priorityTier": 3
  },
  {
    "slug": "broadway",
    "name": "Broadway",
    "zone": "central-chennai",
    "sortOrder": 71,
    "priorityTier": 3
  },
  {
    "slug": "camp-road",
    "name": "Camp Road",
    "zone": "central-chennai",
    "sortOrder": 72,
    "priorityTier": 3
  },
  {
    "slug": "chembarambakkam",
    "name": "Chembarambakkam",
    "zone": "central-chennai",
    "sortOrder": 73,
    "priorityTier": 3
  },
  {
    "slug": "chemmancheri",
    "name": "Chemmancheri",
    "zone": "central-chennai",
    "sortOrder": 74,
    "priorityTier": 3
  },
  {
    "slug": "chengalpattu",
    "name": "Chengalpattu",
    "zone": "south-suburbs",
    "sortOrder": 75,
    "priorityTier": 2
  },
  {
    "slug": "chennai-airport",
    "name": "Chennai Airport",
    "zone": "central-chennai",
    "sortOrder": 76,
    "priorityTier": 3
  },
  {
    "slug": "chennai-central",
    "name": "Chennai Central",
    "zone": "central-chennai",
    "sortOrder": 77,
    "priorityTier": 3
  },
  {
    "slug": "chennai-chetpet",
    "name": "Chennai Chetpet",
    "zone": "central-chennai",
    "sortOrder": 78,
    "priorityTier": 3
  },
  {
    "slug": "chennai-egmore",
    "name": "Chennai Egmore",
    "zone": "central-chennai",
    "sortOrder": 79,
    "priorityTier": 3
  },
  {
    "slug": "chennai-park-town",
    "name": "Chennai Park Town",
    "zone": "central-chennai",
    "sortOrder": 80,
    "priorityTier": 3
  },
  {
    "slug": "chennai-port",
    "name": "Chennai Port",
    "zone": "central-chennai",
    "sortOrder": 81,
    "priorityTier": 3
  },
  {
    "slug": "chennai-trade-centre",
    "name": "Chennai Trade Centre",
    "zone": "central-chennai",
    "sortOrder": 82,
    "priorityTier": 3
  },
  {
    "slug": "chetpet",
    "name": "Chetpet",
    "zone": "central-chennai",
    "sortOrder": 83,
    "priorityTier": 3
  },
  {
    "slug": "chinna-nolambur",
    "name": "Chinna Nolambur",
    "zone": "central-chennai",
    "sortOrder": 84,
    "priorityTier": 3
  },
  {
    "slug": "chinna-sekkadu",
    "name": "Chinna Sekkadu",
    "zone": "central-chennai",
    "sortOrder": 85,
    "priorityTier": 3
  },
  {
    "slug": "chintadripet",
    "name": "Chintadripet",
    "zone": "central-chennai",
    "sortOrder": 86,
    "priorityTier": 3
  },
  {
    "slug": "chitlapakkam",
    "name": "Chitlapakkam",
    "zone": "central-chennai",
    "sortOrder": 87,
    "priorityTier": 3
  },
  {
    "slug": "chitlapakkam-ramakrishnapuram",
    "name": "Chitlapakkam Ramakrishnapuram",
    "zone": "central-chennai",
    "sortOrder": 88,
    "priorityTier": 3
  },
  {
    "slug": "cholambedu",
    "name": "Cholambedu",
    "zone": "central-chennai",
    "sortOrder": 89,
    "priorityTier": 3
  },
  {
    "slug": "choolai",
    "name": "Choolai",
    "zone": "central-chennai",
    "sortOrder": 90,
    "priorityTier": 3
  },
  {
    "slug": "choolai-high-road",
    "name": "Choolai High Road",
    "zone": "central-chennai",
    "sortOrder": 91,
    "priorityTier": 3
  },
  {
    "slug": "choolaimedu",
    "name": "Choolaimedu",
    "zone": "central-chennai",
    "sortOrder": 92,
    "priorityTier": 3
  },
  {
    "slug": "chromepet",
    "name": "Chromepet",
    "zone": "south-suburbs",
    "sortOrder": 93,
    "priorityTier": 1
  },
  {
    "slug": "cit-colony",
    "name": "Cit Colony",
    "zone": "central-chennai",
    "sortOrder": 94,
    "priorityTier": 3
  },
  {
    "slug": "cit-nagar",
    "name": "Cit Nagar",
    "zone": "central-chennai",
    "sortOrder": 95,
    "priorityTier": 3
  },
  {
    "slug": "cmbt-koyambedu",
    "name": "CMBT Koyambedu",
    "zone": "central-chennai",
    "sortOrder": 96,
    "priorityTier": 3
  },
  {
    "slug": "cooks-road",
    "name": "Cooks Road",
    "zone": "central-chennai",
    "sortOrder": 97,
    "priorityTier": 3
  },
  {
    "slug": "cowl-bazaar",
    "name": "Cowl Bazaar",
    "zone": "central-chennai",
    "sortOrder": 98,
    "priorityTier": 3
  },
  {
    "slug": "defence-colony",
    "name": "Defence Colony",
    "zone": "central-chennai",
    "sortOrder": 99,
    "priorityTier": 3
  },
  {
    "slug": "devi-karumariamman-nagar",
    "name": "Devi Karumariamman Nagar",
    "zone": "central-chennai",
    "sortOrder": 100,
    "priorityTier": 3
  },
  {
    "slug": "dlf-it-park",
    "name": "DLF It Park",
    "zone": "central-chennai",
    "sortOrder": 101,
    "priorityTier": 3
  },
  {
    "slug": "dr-ambedkar-nagar",
    "name": "Dr. Ambedkar Nagar",
    "zone": "central-chennai",
    "sortOrder": 102,
    "priorityTier": 3
  },
  {
    "slug": "east-coast-road",
    "name": "East Coast Road",
    "zone": "central-chennai",
    "sortOrder": 103,
    "priorityTier": 3
  },
  {
    "slug": "east-tambaram",
    "name": "East Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 104,
    "priorityTier": 3
  },
  {
    "slug": "east-tambaram-camp-road",
    "name": "East Tambaram Camp Road",
    "zone": "south-suburbs",
    "sortOrder": 105,
    "priorityTier": 3
  },
  {
    "slug": "eattivakkam",
    "name": "Eattivakkam",
    "zone": "central-chennai",
    "sortOrder": 106,
    "priorityTier": 3
  },
  {
    "slug": "ecr-injambakkam",
    "name": "ECR Injambakkam",
    "zone": "ecr-coast",
    "sortOrder": 107,
    "priorityTier": 3
  },
  {
    "slug": "ecr-kanathur",
    "name": "ECR Kanathur",
    "zone": "ecr-coast",
    "sortOrder": 108,
    "priorityTier": 3
  },
  {
    "slug": "ecr-neelankarai",
    "name": "ECR Neelankarai",
    "zone": "ecr-coast",
    "sortOrder": 109,
    "priorityTier": 1
  },
  {
    "slug": "ecr-palavakkam",
    "name": "ECR Palavakkam",
    "zone": "ecr-coast",
    "sortOrder": 110,
    "priorityTier": 3
  },
  {
    "slug": "ecr-panaiyur",
    "name": "ECR Panaiyur",
    "zone": "ecr-coast",
    "sortOrder": 111,
    "priorityTier": 3
  },
  {
    "slug": "ecr-uthandi",
    "name": "ECR Uthandi",
    "zone": "ecr-coast",
    "sortOrder": 112,
    "priorityTier": 3
  },
  {
    "slug": "edayanchavadi",
    "name": "Edayanchavadi",
    "zone": "north-chennai",
    "sortOrder": 113,
    "priorityTier": 3
  },
  {
    "slug": "egattur",
    "name": "Egattur",
    "zone": "central-chennai",
    "sortOrder": 114,
    "priorityTier": 3
  },
  {
    "slug": "egmore",
    "name": "Egmore",
    "zone": "central-chennai",
    "sortOrder": 115,
    "priorityTier": 2
  },
  {
    "slug": "ekkaduthangal",
    "name": "Ekkaduthangal",
    "zone": "central-chennai",
    "sortOrder": 116,
    "priorityTier": 3
  },
  {
    "slug": "elandanur",
    "name": "Elandanur",
    "zone": "central-chennai",
    "sortOrder": 117,
    "priorityTier": 3
  },
  {
    "slug": "elavur",
    "name": "Elavur",
    "zone": "central-chennai",
    "sortOrder": 118,
    "priorityTier": 3
  },
  {
    "slug": "elcot-sez",
    "name": "Elcot Sez",
    "zone": "central-chennai",
    "sortOrder": 119,
    "priorityTier": 3
  },
  {
    "slug": "ennore",
    "name": "Ennore",
    "zone": "north-suburbs",
    "sortOrder": 120,
    "priorityTier": 3
  },
  {
    "slug": "ernavoor",
    "name": "Ernavoor",
    "zone": "central-chennai",
    "sortOrder": 121,
    "priorityTier": 3
  },
  {
    "slug": "erukkancheri",
    "name": "Erukkancheri",
    "zone": "central-chennai",
    "sortOrder": 122,
    "priorityTier": 3
  },
  {
    "slug": "flowers-road",
    "name": "Flowers Road",
    "zone": "central-chennai",
    "sortOrder": 123,
    "priorityTier": 3
  },
  {
    "slug": "gandhi-irwin-road",
    "name": "Gandhi Irwin Road",
    "zone": "central-chennai",
    "sortOrder": 124,
    "priorityTier": 3
  },
  {
    "slug": "gandhi-nagar-adyar",
    "name": "Gandhi Nagar Adyar",
    "zone": "central-chennai",
    "sortOrder": 125,
    "priorityTier": 3
  },
  {
    "slug": "gengu-reddy-road",
    "name": "Gengu Reddy Road",
    "zone": "central-chennai",
    "sortOrder": 126,
    "priorityTier": 3
  },
  {
    "slug": "george-town",
    "name": "George Town",
    "zone": "central-chennai",
    "sortOrder": 127,
    "priorityTier": 3
  },
  {
    "slug": "gerugambakkam",
    "name": "Gerugambakkam",
    "zone": "central-chennai",
    "sortOrder": 128,
    "priorityTier": 3
  },
  {
    "slug": "gill-nagar",
    "name": "Gill Nagar",
    "zone": "central-chennai",
    "sortOrder": 129,
    "priorityTier": 3
  },
  {
    "slug": "golden-george-nagar",
    "name": "Golden George Nagar",
    "zone": "central-chennai",
    "sortOrder": 130,
    "priorityTier": 3
  },
  {
    "slug": "gopalapuram",
    "name": "Gopalapuram",
    "zone": "central-chennai",
    "sortOrder": 131,
    "priorityTier": 3
  },
  {
    "slug": "govardhanagiri",
    "name": "Govardhanagiri",
    "zone": "central-chennai",
    "sortOrder": 132,
    "priorityTier": 3
  },
  {
    "slug": "gowrivakkam",
    "name": "Gowrivakkam",
    "zone": "central-chennai",
    "sortOrder": 133,
    "priorityTier": 3
  },
  {
    "slug": "gowrivakkam-tambaram",
    "name": "Gowrivakkam Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 134,
    "priorityTier": 3
  },
  {
    "slug": "guduvancheri",
    "name": "Guduvancheri",
    "zone": "south-suburbs",
    "sortOrder": 135,
    "priorityTier": 2
  },
  {
    "slug": "guindy",
    "name": "Guindy",
    "zone": "south-chennai",
    "sortOrder": 136,
    "priorityTier": 1
  },
  {
    "slug": "guindy-industrial-estate",
    "name": "Guindy Industrial Estate",
    "zone": "central-chennai",
    "sortOrder": 137,
    "priorityTier": 3
  },
  {
    "slug": "guindy-race-course",
    "name": "Guindy Race Course",
    "zone": "central-chennai",
    "sortOrder": 138,
    "priorityTier": 3
  },
  {
    "slug": "gummidipoondi",
    "name": "Gummidipoondi",
    "zone": "central-chennai",
    "sortOrder": 139,
    "priorityTier": 3
  },
  {
    "slug": "harrington-road",
    "name": "Harrington Road",
    "zone": "central-chennai",
    "sortOrder": 140,
    "priorityTier": 3
  },
  {
    "slug": "hasthinapuram",
    "name": "Hasthinapuram",
    "zone": "central-chennai",
    "sortOrder": 141,
    "priorityTier": 3
  },
  {
    "slug": "hasthinapuram-chromepet",
    "name": "Hasthinapuram Chromepet",
    "zone": "south-suburbs",
    "sortOrder": 142,
    "priorityTier": 3
  },
  {
    "slug": "hindu-college",
    "name": "Hindu College",
    "zone": "central-chennai",
    "sortOrder": 143,
    "priorityTier": 3
  },
  {
    "slug": "ibrahimpatnam-chennai",
    "name": "Ibrahimpatnam Chennai",
    "zone": "central-chennai",
    "sortOrder": 144,
    "priorityTier": 3
  },
  {
    "slug": "icf-colony",
    "name": "ICF Colony",
    "zone": "central-chennai",
    "sortOrder": 145,
    "priorityTier": 3
  },
  {
    "slug": "indira-nagar-adyar",
    "name": "Indira Nagar Adyar",
    "zone": "central-chennai",
    "sortOrder": 146,
    "priorityTier": 3
  },
  {
    "slug": "injambakkam",
    "name": "Injambakkam",
    "zone": "ecr-coast",
    "sortOrder": 147,
    "priorityTier": 2
  },
  {
    "slug": "irandankattalai",
    "name": "Irandankattalai",
    "zone": "central-chennai",
    "sortOrder": 148,
    "priorityTier": 3
  },
  {
    "slug": "irumbuliyur",
    "name": "Irumbuliyur",
    "zone": "central-chennai",
    "sortOrder": 149,
    "priorityTier": 3
  },
  {
    "slug": "irumbuliyur-tambaram",
    "name": "Irumbuliyur Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 150,
    "priorityTier": 3
  },
  {
    "slug": "iyyappanthangal",
    "name": "Iyyappanthangal",
    "zone": "central-chennai",
    "sortOrder": 151,
    "priorityTier": 3
  },
  {
    "slug": "jafferkhanpet",
    "name": "Jafferkhanpet",
    "zone": "central-chennai",
    "sortOrder": 152,
    "priorityTier": 3
  },
  {
    "slug": "jai-nagar",
    "name": "Jai Nagar",
    "zone": "central-chennai",
    "sortOrder": 153,
    "priorityTier": 3
  },
  {
    "slug": "jalladianpet",
    "name": "Jalladianpet",
    "zone": "central-chennai",
    "sortOrder": 154,
    "priorityTier": 3
  },
  {
    "slug": "jamalia",
    "name": "Jamalia",
    "zone": "central-chennai",
    "sortOrder": 155,
    "priorityTier": 3
  },
  {
    "slug": "jawahar-nagar",
    "name": "Jawahar Nagar",
    "zone": "central-chennai",
    "sortOrder": 156,
    "priorityTier": 3
  },
  {
    "slug": "jeeva-nagar",
    "name": "Jeeva Nagar",
    "zone": "central-chennai",
    "sortOrder": 157,
    "priorityTier": 3
  },
  {
    "slug": "jepiar-nagar",
    "name": "Jepiar Nagar",
    "zone": "central-chennai",
    "sortOrder": 158,
    "priorityTier": 3
  },
  {
    "slug": "jothi-nagar",
    "name": "Jothi Nagar",
    "zone": "central-chennai",
    "sortOrder": 159,
    "priorityTier": 3
  },
  {
    "slug": "kk-nagar",
    "name": "K.k. Nagar",
    "zone": "central-chennai",
    "sortOrder": 160,
    "priorityTier": 2
  },
  {
    "slug": "kadambathur",
    "name": "Kadambathur",
    "zone": "central-chennai",
    "sortOrder": 161,
    "priorityTier": 3
  },
  {
    "slug": "kadaperi",
    "name": "Kadaperi",
    "zone": "central-chennai",
    "sortOrder": 162,
    "priorityTier": 3
  },
  {
    "slug": "kadaperi-tambaram",
    "name": "Kadaperi Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 163,
    "priorityTier": 3
  },
  {
    "slug": "kadappakkam",
    "name": "Kadappakkam",
    "zone": "central-chennai",
    "sortOrder": 164,
    "priorityTier": 3
  },
  {
    "slug": "kadiyapattinam",
    "name": "Kadiyapattinam",
    "zone": "central-chennai",
    "sortOrder": 165,
    "priorityTier": 3
  },
  {
    "slug": "kaladipet",
    "name": "Kaladipet",
    "zone": "central-chennai",
    "sortOrder": 166,
    "priorityTier": 3
  },
  {
    "slug": "kalaignar-nagar",
    "name": "Kalaignar Nagar",
    "zone": "central-chennai",
    "sortOrder": 167,
    "priorityTier": 3
  },
  {
    "slug": "kalakshetra-colony",
    "name": "Kalakshetra Colony",
    "zone": "central-chennai",
    "sortOrder": 168,
    "priorityTier": 3
  },
  {
    "slug": "kallikuppam",
    "name": "Kallikuppam",
    "zone": "central-chennai",
    "sortOrder": 169,
    "priorityTier": 3
  },
  {
    "slug": "kamaraj-nagar-avadi",
    "name": "Kamaraj Nagar Avadi",
    "zone": "north-chennai",
    "sortOrder": 170,
    "priorityTier": 3
  },
  {
    "slug": "kanathur",
    "name": "Kanathur",
    "zone": "central-chennai",
    "sortOrder": 171,
    "priorityTier": 3
  },
  {
    "slug": "kandanchavadi",
    "name": "Kandanchavadi",
    "zone": "north-chennai",
    "sortOrder": 172,
    "priorityTier": 3
  },
  {
    "slug": "kandigai",
    "name": "Kandigai",
    "zone": "central-chennai",
    "sortOrder": 173,
    "priorityTier": 3
  },
  {
    "slug": "kannadasan-nagar",
    "name": "Kannadasan Nagar",
    "zone": "central-chennai",
    "sortOrder": 174,
    "priorityTier": 3
  },
  {
    "slug": "kannammapet",
    "name": "Kannammapet",
    "zone": "central-chennai",
    "sortOrder": 175,
    "priorityTier": 3
  },
  {
    "slug": "kannivakkam",
    "name": "Kannivakkam",
    "zone": "central-chennai",
    "sortOrder": 176,
    "priorityTier": 3
  },
  {
    "slug": "karambakkam",
    "name": "Karambakkam",
    "zone": "central-chennai",
    "sortOrder": 177,
    "priorityTier": 3
  },
  {
    "slug": "karanodai",
    "name": "Karanodai",
    "zone": "central-chennai",
    "sortOrder": 178,
    "priorityTier": 3
  },
  {
    "slug": "karapakkam",
    "name": "Karapakkam",
    "zone": "central-chennai",
    "sortOrder": 179,
    "priorityTier": 3
  },
  {
    "slug": "karapakkam-omr",
    "name": "Karapakkam OMR",
    "zone": "omr-corridor",
    "sortOrder": 180,
    "priorityTier": 1
  },
  {
    "slug": "karayanchavadi",
    "name": "Karayanchavadi",
    "zone": "north-chennai",
    "sortOrder": 181,
    "priorityTier": 3
  },
  {
    "slug": "karpagam-gardens",
    "name": "Karpagam Gardens",
    "zone": "central-chennai",
    "sortOrder": 182,
    "priorityTier": 3
  },
  {
    "slug": "kathipara-junction",
    "name": "Kathipara Junction",
    "zone": "central-chennai",
    "sortOrder": 183,
    "priorityTier": 3
  },
  {
    "slug": "kathirvedu",
    "name": "Kathirvedu",
    "zone": "central-chennai",
    "sortOrder": 184,
    "priorityTier": 3
  },
  {
    "slug": "kathivakkam",
    "name": "Kathivakkam",
    "zone": "central-chennai",
    "sortOrder": 185,
    "priorityTier": 3
  },
  {
    "slug": "kattankulathur",
    "name": "Kattankulathur",
    "zone": "central-chennai",
    "sortOrder": 186,
    "priorityTier": 3
  },
  {
    "slug": "kattivakkam",
    "name": "Kattivakkam",
    "zone": "central-chennai",
    "sortOrder": 187,
    "priorityTier": 3
  },
  {
    "slug": "kattupakkam",
    "name": "Kattupakkam",
    "zone": "central-chennai",
    "sortOrder": 188,
    "priorityTier": 3
  },
  {
    "slug": "kattupalli",
    "name": "Kattupalli",
    "zone": "central-chennai",
    "sortOrder": 189,
    "priorityTier": 3
  },
  {
    "slug": "kavankarai",
    "name": "Kavankarai",
    "zone": "central-chennai",
    "sortOrder": 190,
    "priorityTier": 3
  },
  {
    "slug": "kaveri-nagar",
    "name": "Kaveri Nagar",
    "zone": "central-chennai",
    "sortOrder": 191,
    "priorityTier": 3
  },
  {
    "slug": "kayarambedu",
    "name": "Kayarambedu",
    "zone": "central-chennai",
    "sortOrder": 192,
    "priorityTier": 3
  },
  {
    "slug": "kazhipattur",
    "name": "Kazhipattur",
    "zone": "central-chennai",
    "sortOrder": 193,
    "priorityTier": 3
  },
  {
    "slug": "kazhipattur-omr",
    "name": "Kazhipattur OMR",
    "zone": "omr-corridor",
    "sortOrder": 194,
    "priorityTier": 1
  },
  {
    "slug": "keelkattalai",
    "name": "Keelkattalai",
    "zone": "central-chennai",
    "sortOrder": 195,
    "priorityTier": 3
  },
  {
    "slug": "keelkottaiyur",
    "name": "Keelkottaiyur",
    "zone": "central-chennai",
    "sortOrder": 196,
    "priorityTier": 3
  },
  {
    "slug": "kelambakkam",
    "name": "Kelambakkam",
    "zone": "central-chennai",
    "sortOrder": 197,
    "priorityTier": 3
  },
  {
    "slug": "kellys",
    "name": "Kellys",
    "zone": "central-chennai",
    "sortOrder": 198,
    "priorityTier": 3
  },
  {
    "slug": "kellys-corner",
    "name": "Kellys Corner",
    "zone": "central-chennai",
    "sortOrder": 199,
    "priorityTier": 3
  },
  {
    "slug": "kilambakkam",
    "name": "Kilambakkam",
    "zone": "central-chennai",
    "sortOrder": 200,
    "priorityTier": 3
  },
  {
    "slug": "kilkattalai",
    "name": "Kilkattalai",
    "zone": "central-chennai",
    "sortOrder": 201,
    "priorityTier": 3
  },
  {
    "slug": "kilpauk",
    "name": "Kilpauk",
    "zone": "central-chennai",
    "sortOrder": 202,
    "priorityTier": 1
  },
  {
    "slug": "kilpauk-garden",
    "name": "Kilpauk Garden",
    "zone": "central-chennai",
    "sortOrder": 203,
    "priorityTier": 3
  },
  {
    "slug": "kodambakkam",
    "name": "Kodambakkam",
    "zone": "central-chennai",
    "sortOrder": 204,
    "priorityTier": 3
  },
  {
    "slug": "kodipallam",
    "name": "Kodipallam",
    "zone": "central-chennai",
    "sortOrder": 205,
    "priorityTier": 3
  },
  {
    "slug": "kodungaiyur",
    "name": "Kodungaiyur",
    "zone": "central-chennai",
    "sortOrder": 206,
    "priorityTier": 3
  },
  {
    "slug": "kodungaiyur-west",
    "name": "Kodungaiyur West",
    "zone": "central-chennai",
    "sortOrder": 207,
    "priorityTier": 3
  },
  {
    "slug": "kolapakkam",
    "name": "Kolapakkam",
    "zone": "central-chennai",
    "sortOrder": 208,
    "priorityTier": 3
  },
  {
    "slug": "kolathur",
    "name": "Kolathur",
    "zone": "central-chennai",
    "sortOrder": 209,
    "priorityTier": 3
  },
  {
    "slug": "kondavakkam",
    "name": "Kondavakkam",
    "zone": "central-chennai",
    "sortOrder": 210,
    "priorityTier": 3
  },
  {
    "slug": "konnur",
    "name": "Konnur",
    "zone": "central-chennai",
    "sortOrder": 211,
    "priorityTier": 3
  },
  {
    "slug": "korattur",
    "name": "Korattur",
    "zone": "north-chennai",
    "sortOrder": 212,
    "priorityTier": 3
  },
  {
    "slug": "korukkupet",
    "name": "Korukkupet",
    "zone": "central-chennai",
    "sortOrder": 213,
    "priorityTier": 3
  },
  {
    "slug": "kosappur",
    "name": "Kosappur",
    "zone": "central-chennai",
    "sortOrder": 214,
    "priorityTier": 3
  },
  {
    "slug": "kosasthalaiyar-nagar",
    "name": "Kosasthalaiyar Nagar",
    "zone": "central-chennai",
    "sortOrder": 215,
    "priorityTier": 3
  },
  {
    "slug": "kottivakkam",
    "name": "Kottivakkam",
    "zone": "central-chennai",
    "sortOrder": 216,
    "priorityTier": 3
  },
  {
    "slug": "kottur",
    "name": "Kottur",
    "zone": "central-chennai",
    "sortOrder": 217,
    "priorityTier": 3
  },
  {
    "slug": "kottur-gardens",
    "name": "Kottur Gardens",
    "zone": "central-chennai",
    "sortOrder": 218,
    "priorityTier": 3
  },
  {
    "slug": "kotturpuram",
    "name": "Kotturpuram",
    "zone": "central-chennai",
    "sortOrder": 219,
    "priorityTier": 3
  },
  {
    "slug": "kovalam",
    "name": "Kovalam",
    "zone": "central-chennai",
    "sortOrder": 220,
    "priorityTier": 3
  },
  {
    "slug": "kovilambakkam",
    "name": "Kovilambakkam",
    "zone": "central-chennai",
    "sortOrder": 221,
    "priorityTier": 3
  },
  {
    "slug": "kovilpadagai",
    "name": "Kovilpadagai",
    "zone": "central-chennai",
    "sortOrder": 222,
    "priorityTier": 3
  },
  {
    "slug": "koyambedu",
    "name": "Koyambedu",
    "zone": "central-chennai",
    "sortOrder": 223,
    "priorityTier": 1
  },
  {
    "slug": "koyambedu-cmbt",
    "name": "Koyambedu CMBT",
    "zone": "central-chennai",
    "sortOrder": 224,
    "priorityTier": 3
  },
  {
    "slug": "koyambedu-market",
    "name": "Koyambedu Market",
    "zone": "central-chennai",
    "sortOrder": 225,
    "priorityTier": 3
  },
  {
    "slug": "kumananchavadi",
    "name": "Kumananchavadi",
    "zone": "north-chennai",
    "sortOrder": 226,
    "priorityTier": 3
  },
  {
    "slug": "kumaran-nagar",
    "name": "Kumaran Nagar",
    "zone": "central-chennai",
    "sortOrder": 227,
    "priorityTier": 3
  },
  {
    "slug": "kumaran-nagar-sholinganallur",
    "name": "Kumaran Nagar Sholinganallur",
    "zone": "omr-corridor",
    "sortOrder": 228,
    "priorityTier": 3
  },
  {
    "slug": "kundrathur",
    "name": "Kundrathur",
    "zone": "central-chennai",
    "sortOrder": 229,
    "priorityTier": 3
  },
  {
    "slug": "kundrathur-road",
    "name": "Kundrathur Road",
    "zone": "central-chennai",
    "sortOrder": 230,
    "priorityTier": 3
  },
  {
    "slug": "lakshmipuram",
    "name": "Lakshmipuram",
    "zone": "central-chennai",
    "sortOrder": 231,
    "priorityTier": 3
  },
  {
    "slug": "little-mount",
    "name": "Little Mount",
    "zone": "central-chennai",
    "sortOrder": 232,
    "priorityTier": 3
  },
  {
    "slug": "mgr-nagar",
    "name": "MGR Nagar",
    "zone": "central-chennai",
    "sortOrder": 233,
    "priorityTier": 3
  },
  {
    "slug": "madambakkam",
    "name": "Madambakkam",
    "zone": "central-chennai",
    "sortOrder": 234,
    "priorityTier": 3
  },
  {
    "slug": "madambakkam-tambaram",
    "name": "Madambakkam Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 235,
    "priorityTier": 3
  },
  {
    "slug": "madhavaram",
    "name": "Madhavaram",
    "zone": "central-chennai",
    "sortOrder": 236,
    "priorityTier": 3
  },
  {
    "slug": "madhavaram-milk-colony",
    "name": "Madhavaram Milk Colony",
    "zone": "central-chennai",
    "sortOrder": 237,
    "priorityTier": 3
  },
  {
    "slug": "madhavaram-ring-road",
    "name": "Madhavaram Ring Road",
    "zone": "central-chennai",
    "sortOrder": 238,
    "priorityTier": 3
  },
  {
    "slug": "madhavaram-village",
    "name": "Madhavaram Village",
    "zone": "central-chennai",
    "sortOrder": 239,
    "priorityTier": 3
  },
  {
    "slug": "madhya-kailash",
    "name": "Madhya Kailash",
    "zone": "central-chennai",
    "sortOrder": 240,
    "priorityTier": 3
  },
  {
    "slug": "madipakkam",
    "name": "Madipakkam",
    "zone": "central-chennai",
    "sortOrder": 241,
    "priorityTier": 2
  },
  {
    "slug": "madurapakkam",
    "name": "Madurapakkam",
    "zone": "central-chennai",
    "sortOrder": 242,
    "priorityTier": 3
  },
  {
    "slug": "maduravoyal",
    "name": "Maduravoyal",
    "zone": "central-chennai",
    "sortOrder": 243,
    "priorityTier": 3
  },
  {
    "slug": "maduravoyal-bypass",
    "name": "Maduravoyal Bypass",
    "zone": "central-chennai",
    "sortOrder": 244,
    "priorityTier": 3
  },
  {
    "slug": "mahalakshmi-nagar-selaiyur",
    "name": "Mahalakshmi Nagar Selaiyur",
    "zone": "central-chennai",
    "sortOrder": 245,
    "priorityTier": 3
  },
  {
    "slug": "mahalingapuram",
    "name": "Mahalingapuram",
    "zone": "central-chennai",
    "sortOrder": 246,
    "priorityTier": 3
  },
  {
    "slug": "mahindra-world-city",
    "name": "Mahindra World City",
    "zone": "central-chennai",
    "sortOrder": 247,
    "priorityTier": 3
  },
  {
    "slug": "mambakkam",
    "name": "Mambakkam",
    "zone": "central-chennai",
    "sortOrder": 248,
    "priorityTier": 3
  },
  {
    "slug": "mambalam",
    "name": "Mambalam",
    "zone": "central-chennai",
    "sortOrder": 249,
    "priorityTier": 3
  },
  {
    "slug": "manali",
    "name": "Manali",
    "zone": "central-chennai",
    "sortOrder": 250,
    "priorityTier": 3
  },
  {
    "slug": "manali-new-town",
    "name": "Manali New Town",
    "zone": "central-chennai",
    "sortOrder": 251,
    "priorityTier": 3
  },
  {
    "slug": "manali-pudhunagar",
    "name": "Manali Pudhunagar",
    "zone": "central-chennai",
    "sortOrder": 252,
    "priorityTier": 3
  },
  {
    "slug": "manapakkam",
    "name": "Manapakkam",
    "zone": "central-chennai",
    "sortOrder": 253,
    "priorityTier": 3
  },
  {
    "slug": "mandaveli",
    "name": "Mandaveli",
    "zone": "central-chennai",
    "sortOrder": 254,
    "priorityTier": 3
  },
  {
    "slug": "mandaveli-pakkam",
    "name": "Mandaveli Pakkam",
    "zone": "central-chennai",
    "sortOrder": 255,
    "priorityTier": 3
  },
  {
    "slug": "mandaveli-raja-annamalaipuram",
    "name": "Mandaveli Raja Annamalaipuram",
    "zone": "central-chennai",
    "sortOrder": 256,
    "priorityTier": 3
  },
  {
    "slug": "manjambakkam",
    "name": "Manjambakkam",
    "zone": "central-chennai",
    "sortOrder": 257,
    "priorityTier": 3
  },
  {
    "slug": "mannadi",
    "name": "Mannadi",
    "zone": "central-chennai",
    "sortOrder": 258,
    "priorityTier": 3
  },
  {
    "slug": "mannivakkam",
    "name": "Mannivakkam",
    "zone": "central-chennai",
    "sortOrder": 259,
    "priorityTier": 3
  },
  {
    "slug": "mannivakkam-extension",
    "name": "Mannivakkam Extension",
    "zone": "central-chennai",
    "sortOrder": 260,
    "priorityTier": 3
  },
  {
    "slug": "mappedu",
    "name": "Mappedu",
    "zone": "central-chennai",
    "sortOrder": 261,
    "priorityTier": 3
  },
  {
    "slug": "maraimalai-nagar",
    "name": "Maraimalai Nagar",
    "zone": "central-chennai",
    "sortOrder": 262,
    "priorityTier": 3
  },
  {
    "slug": "maraimalai-nagar-industrial-estate",
    "name": "Maraimalai Nagar Industrial Estate",
    "zone": "central-chennai",
    "sortOrder": 263,
    "priorityTier": 3
  },
  {
    "slug": "marina-beach",
    "name": "Marina Beach",
    "zone": "central-chennai",
    "sortOrder": 264,
    "priorityTier": 3
  },
  {
    "slug": "mathur",
    "name": "Mathur",
    "zone": "central-chennai",
    "sortOrder": 265,
    "priorityTier": 3
  },
  {
    "slug": "mcc-campus",
    "name": "MCC Campus",
    "zone": "central-chennai",
    "sortOrder": 266,
    "priorityTier": 3
  },
  {
    "slug": "medavakkam",
    "name": "Medavakkam",
    "zone": "central-chennai",
    "sortOrder": 267,
    "priorityTier": 1
  },
  {
    "slug": "medavakkam-tank-road",
    "name": "Medavakkam Tank Road",
    "zone": "central-chennai",
    "sortOrder": 268,
    "priorityTier": 3
  },
  {
    "slug": "meenakshi-nagar",
    "name": "Meenakshi Nagar",
    "zone": "central-chennai",
    "sortOrder": 269,
    "priorityTier": 3
  },
  {
    "slug": "meenambakkam",
    "name": "Meenambakkam",
    "zone": "central-chennai",
    "sortOrder": 270,
    "priorityTier": 3
  },
  {
    "slug": "melnallathur",
    "name": "Melnallathur",
    "zone": "central-chennai",
    "sortOrder": 271,
    "priorityTier": 3
  },
  {
    "slug": "melpakkam",
    "name": "Melpakkam",
    "zone": "central-chennai",
    "sortOrder": 272,
    "priorityTier": 3
  },
  {
    "slug": "mettukuppam",
    "name": "Mettukuppam",
    "zone": "central-chennai",
    "sortOrder": 273,
    "priorityTier": 3
  },
  {
    "slug": "mettukuppam-porur",
    "name": "Mettukuppam Porur",
    "zone": "west-chennai",
    "sortOrder": 274,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam-chennai",
    "name": "Mettupalayam Chennai",
    "zone": "central-chennai",
    "sortOrder": 275,
    "priorityTier": 3
  },
  {
    "slug": "minjur",
    "name": "Minjur",
    "zone": "north-suburbs",
    "sortOrder": 276,
    "priorityTier": 3
  },
  {
    "slug": "mint",
    "name": "Mint",
    "zone": "central-chennai",
    "sortOrder": 277,
    "priorityTier": 3
  },
  {
    "slug": "mkb-nagar",
    "name": "MKB Nagar",
    "zone": "central-chennai",
    "sortOrder": 278,
    "priorityTier": 3
  },
  {
    "slug": "mogappair",
    "name": "Mogappair",
    "zone": "north-chennai",
    "sortOrder": 279,
    "priorityTier": 1
  },
  {
    "slug": "mogappair-east",
    "name": "Mogappair East",
    "zone": "north-chennai",
    "sortOrder": 280,
    "priorityTier": 3
  },
  {
    "slug": "mogappair-west",
    "name": "Mogappair West",
    "zone": "north-chennai",
    "sortOrder": 281,
    "priorityTier": 3
  },
  {
    "slug": "moolachathiram",
    "name": "Moolachathiram",
    "zone": "central-chennai",
    "sortOrder": 282,
    "priorityTier": 3
  },
  {
    "slug": "moolakadai",
    "name": "Moolakadai",
    "zone": "central-chennai",
    "sortOrder": 283,
    "priorityTier": 3
  },
  {
    "slug": "moulivakkam",
    "name": "Moulivakkam",
    "zone": "central-chennai",
    "sortOrder": 284,
    "priorityTier": 3
  },
  {
    "slug": "mount-road",
    "name": "Mount Road",
    "zone": "central-chennai",
    "sortOrder": 285,
    "priorityTier": 3
  },
  {
    "slug": "mudichur",
    "name": "Mudichur",
    "zone": "central-chennai",
    "sortOrder": 286,
    "priorityTier": 3
  },
  {
    "slug": "mugalivakkam",
    "name": "Mugalivakkam",
    "zone": "west-chennai",
    "sortOrder": 287,
    "priorityTier": 3
  },
  {
    "slug": "music-academy",
    "name": "Music Academy",
    "zone": "central-chennai",
    "sortOrder": 288,
    "priorityTier": 3
  },
  {
    "slug": "muthapudupet",
    "name": "Muthapudupet",
    "zone": "central-chennai",
    "sortOrder": 289,
    "priorityTier": 3
  },
  {
    "slug": "mylapore",
    "name": "Mylapore",
    "zone": "central-chennai",
    "sortOrder": 290,
    "priorityTier": 1
  },
  {
    "slug": "naduveerapattu",
    "name": "Naduveerapattu",
    "zone": "central-chennai",
    "sortOrder": 291,
    "priorityTier": 3
  },
  {
    "slug": "nallambakkam",
    "name": "Nallambakkam",
    "zone": "central-chennai",
    "sortOrder": 292,
    "priorityTier": 3
  },
  {
    "slug": "nandambakkam",
    "name": "Nandambakkam",
    "zone": "central-chennai",
    "sortOrder": 293,
    "priorityTier": 3
  },
  {
    "slug": "nandanam",
    "name": "Nandanam",
    "zone": "central-chennai",
    "sortOrder": 294,
    "priorityTier": 3
  },
  {
    "slug": "nandiambakkam",
    "name": "Nandiambakkam",
    "zone": "central-chennai",
    "sortOrder": 295,
    "priorityTier": 3
  },
  {
    "slug": "nandivaram",
    "name": "Nandivaram",
    "zone": "central-chennai",
    "sortOrder": 296,
    "priorityTier": 3
  },
  {
    "slug": "nanganallur",
    "name": "Nanganallur",
    "zone": "central-chennai",
    "sortOrder": 297,
    "priorityTier": 3
  },
  {
    "slug": "nanmathi",
    "name": "Nanmathi",
    "zone": "central-chennai",
    "sortOrder": 298,
    "priorityTier": 3
  },
  {
    "slug": "navalur",
    "name": "Navalur",
    "zone": "omr-corridor",
    "sortOrder": 299,
    "priorityTier": 2
  },
  {
    "slug": "navalur-omr",
    "name": "Navalur OMR",
    "zone": "omr-corridor",
    "sortOrder": 300,
    "priorityTier": 1
  },
  {
    "slug": "neelankarai",
    "name": "Neelankarai",
    "zone": "ecr-coast",
    "sortOrder": 301,
    "priorityTier": 3
  },
  {
    "slug": "nemilichery",
    "name": "Nemilichery",
    "zone": "central-chennai",
    "sortOrder": 302,
    "priorityTier": 3
  },
  {
    "slug": "nemilichery-chromepet",
    "name": "Nemilichery Chromepet",
    "zone": "south-suburbs",
    "sortOrder": 303,
    "priorityTier": 3
  },
  {
    "slug": "nerkundram",
    "name": "Nerkundram",
    "zone": "central-chennai",
    "sortOrder": 304,
    "priorityTier": 3
  },
  {
    "slug": "nerkundram-extension",
    "name": "Nerkundram Extension",
    "zone": "central-chennai",
    "sortOrder": 305,
    "priorityTier": 3
  },
  {
    "slug": "nesapakkam",
    "name": "Nesapakkam",
    "zone": "central-chennai",
    "sortOrder": 306,
    "priorityTier": 3
  },
  {
    "slug": "new-avadi-road",
    "name": "New Avadi Road",
    "zone": "north-chennai",
    "sortOrder": 307,
    "priorityTier": 3
  },
  {
    "slug": "new-ernavoor",
    "name": "New Ernavoor",
    "zone": "central-chennai",
    "sortOrder": 308,
    "priorityTier": 3
  },
  {
    "slug": "new-manali-town",
    "name": "New Manali Town",
    "zone": "central-chennai",
    "sortOrder": 309,
    "priorityTier": 3
  },
  {
    "slug": "new-perungalathur",
    "name": "New Perungalathur",
    "zone": "central-chennai",
    "sortOrder": 310,
    "priorityTier": 3
  },
  {
    "slug": "new-washermenpet",
    "name": "New Washermenpet",
    "zone": "central-chennai",
    "sortOrder": 311,
    "priorityTier": 3
  },
  {
    "slug": "nolambur",
    "name": "Nolambur",
    "zone": "central-chennai",
    "sortOrder": 312,
    "priorityTier": 3
  },
  {
    "slug": "nolambur-phase-1",
    "name": "Nolambur Phase 1",
    "zone": "central-chennai",
    "sortOrder": 313,
    "priorityTier": 3
  },
  {
    "slug": "nolambur-phase-2",
    "name": "Nolambur Phase 2",
    "zone": "central-chennai",
    "sortOrder": 314,
    "priorityTier": 3
  },
  {
    "slug": "nungambakkam",
    "name": "Nungambakkam",
    "zone": "central-chennai",
    "sortOrder": 315,
    "priorityTier": 1
  },
  {
    "slug": "nungambakkam-high-road",
    "name": "Nungambakkam High Road",
    "zone": "central-chennai",
    "sortOrder": 316,
    "priorityTier": 3
  },
  {
    "slug": "okkiyam-pettai",
    "name": "Okkiyam Pettai",
    "zone": "central-chennai",
    "sortOrder": 317,
    "priorityTier": 3
  },
  {
    "slug": "okkiyam-thoraipakkam",
    "name": "Okkiyam Thoraipakkam",
    "zone": "omr-corridor",
    "sortOrder": 318,
    "priorityTier": 3
  },
  {
    "slug": "old-mahabalipuram-road",
    "name": "Old Mahabalipuram Road",
    "zone": "omr-corridor",
    "sortOrder": 319,
    "priorityTier": 3
  },
  {
    "slug": "old-pallavaram",
    "name": "Old Pallavaram",
    "zone": "south-suburbs",
    "sortOrder": 320,
    "priorityTier": 3
  },
  {
    "slug": "old-perungalathur",
    "name": "Old Perungalathur",
    "zone": "central-chennai",
    "sortOrder": 321,
    "priorityTier": 3
  },
  {
    "slug": "old-tambaram",
    "name": "Old Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 322,
    "priorityTier": 3
  },
  {
    "slug": "old-washermenpet",
    "name": "Old Washermenpet",
    "zone": "central-chennai",
    "sortOrder": 323,
    "priorityTier": 3
  },
  {
    "slug": "omr",
    "name": "OMR",
    "zone": "omr-corridor",
    "sortOrder": 324,
    "priorityTier": 1
  },
  {
    "slug": "oragadam",
    "name": "Oragadam",
    "zone": "central-chennai",
    "sortOrder": 325,
    "priorityTier": 3
  },
  {
    "slug": "ormes-road",
    "name": "Ormes Road",
    "zone": "central-chennai",
    "sortOrder": 326,
    "priorityTier": 3
  },
  {
    "slug": "otteri",
    "name": "Otteri",
    "zone": "central-chennai",
    "sortOrder": 327,
    "priorityTier": 3
  },
  {
    "slug": "otteri-vandalur",
    "name": "Otteri Vandalur",
    "zone": "central-chennai",
    "sortOrder": 328,
    "priorityTier": 3
  },
  {
    "slug": "padappai",
    "name": "Padappai",
    "zone": "central-chennai",
    "sortOrder": 329,
    "priorityTier": 3
  },
  {
    "slug": "padi",
    "name": "Padi",
    "zone": "central-chennai",
    "sortOrder": 330,
    "priorityTier": 3
  },
  {
    "slug": "padianallur",
    "name": "Padianallur",
    "zone": "central-chennai",
    "sortOrder": 331,
    "priorityTier": 3
  },
  {
    "slug": "padur",
    "name": "Padur",
    "zone": "central-chennai",
    "sortOrder": 332,
    "priorityTier": 3
  },
  {
    "slug": "padur-omr",
    "name": "Padur OMR",
    "zone": "omr-corridor",
    "sortOrder": 333,
    "priorityTier": 1
  },
  {
    "slug": "palavakkam",
    "name": "Palavakkam",
    "zone": "ecr-coast",
    "sortOrder": 334,
    "priorityTier": 2
  },
  {
    "slug": "pallavaram",
    "name": "Pallavaram",
    "zone": "south-suburbs",
    "sortOrder": 335,
    "priorityTier": 1
  },
  {
    "slug": "pallavaram-cantonment",
    "name": "Pallavaram Cantonment",
    "zone": "south-suburbs",
    "sortOrder": 336,
    "priorityTier": 3
  },
  {
    "slug": "pallikaranai",
    "name": "Pallikaranai",
    "zone": "central-chennai",
    "sortOrder": 337,
    "priorityTier": 2
  },
  {
    "slug": "pammal",
    "name": "Pammal",
    "zone": "central-chennai",
    "sortOrder": 338,
    "priorityTier": 3
  },
  {
    "slug": "panaiyur",
    "name": "Panaiyur",
    "zone": "central-chennai",
    "sortOrder": 339,
    "priorityTier": 3
  },
  {
    "slug": "pappanchatram",
    "name": "Pappanchatram",
    "zone": "central-chennai",
    "sortOrder": 340,
    "priorityTier": 3
  },
  {
    "slug": "park-town",
    "name": "Park Town",
    "zone": "central-chennai",
    "sortOrder": 341,
    "priorityTier": 3
  },
  {
    "slug": "parrys-corner",
    "name": "Parrys",
    "zone": "central-chennai",
    "sortOrder": 342,
    "priorityTier": 3
  },
  {
    "slug": "paruthipattu",
    "name": "Paruthipattu",
    "zone": "central-chennai",
    "sortOrder": 343,
    "priorityTier": 3
  },
  {
    "slug": "pattabiram",
    "name": "Pattabiram",
    "zone": "central-chennai",
    "sortOrder": 344,
    "priorityTier": 3
  },
  {
    "slug": "pattabiram-military-siding",
    "name": "Pattabiram Military Siding",
    "zone": "central-chennai",
    "sortOrder": 345,
    "priorityTier": 3
  },
  {
    "slug": "pattalam",
    "name": "Pattalam",
    "zone": "central-chennai",
    "sortOrder": 346,
    "priorityTier": 3
  },
  {
    "slug": "pattinapakkam",
    "name": "Pattinapakkam",
    "zone": "central-chennai",
    "sortOrder": 347,
    "priorityTier": 3
  },
  {
    "slug": "pazhavanthangal",
    "name": "Pazhavanthangal",
    "zone": "central-chennai",
    "sortOrder": 348,
    "priorityTier": 3
  },
  {
    "slug": "peerkankaranai",
    "name": "Peerkankaranai",
    "zone": "central-chennai",
    "sortOrder": 349,
    "priorityTier": 3
  },
  {
    "slug": "perambakkam",
    "name": "Perambakkam",
    "zone": "central-chennai",
    "sortOrder": 350,
    "priorityTier": 3
  },
  {
    "slug": "perambur",
    "name": "Perambur",
    "zone": "central-chennai",
    "sortOrder": 351,
    "priorityTier": 3
  },
  {
    "slug": "perambur-barracks-road",
    "name": "Perambur Barracks Road",
    "zone": "central-chennai",
    "sortOrder": 352,
    "priorityTier": 3
  },
  {
    "slug": "peravallur",
    "name": "Peravallur",
    "zone": "central-chennai",
    "sortOrder": 353,
    "priorityTier": 3
  },
  {
    "slug": "periamet",
    "name": "Periamet",
    "zone": "central-chennai",
    "sortOrder": 354,
    "priorityTier": 3
  },
  {
    "slug": "periyar-nagar",
    "name": "Periyar Nagar",
    "zone": "central-chennai",
    "sortOrder": 355,
    "priorityTier": 3
  },
  {
    "slug": "periyasekkadu",
    "name": "Periyasekkadu",
    "zone": "central-chennai",
    "sortOrder": 356,
    "priorityTier": 3
  },
  {
    "slug": "perumanttunallur",
    "name": "Perumanttunallur",
    "zone": "central-chennai",
    "sortOrder": 357,
    "priorityTier": 3
  },
  {
    "slug": "perumbakkam",
    "name": "Perumbakkam",
    "zone": "central-chennai",
    "sortOrder": 358,
    "priorityTier": 3
  },
  {
    "slug": "perungalathur",
    "name": "Perungalathur",
    "zone": "central-chennai",
    "sortOrder": 359,
    "priorityTier": 3
  },
  {
    "slug": "perungavoor",
    "name": "Perungavoor",
    "zone": "central-chennai",
    "sortOrder": 360,
    "priorityTier": 3
  },
  {
    "slug": "perungudi",
    "name": "Perungudi",
    "zone": "omr-corridor",
    "sortOrder": 361,
    "priorityTier": 1
  },
  {
    "slug": "perungudi-industrial-estate",
    "name": "Perungudi Industrial Estate",
    "zone": "central-chennai",
    "sortOrder": 362,
    "priorityTier": 3
  },
  {
    "slug": "perungudi-omr",
    "name": "Perungudi OMR",
    "zone": "omr-corridor",
    "sortOrder": 363,
    "priorityTier": 1
  },
  {
    "slug": "phoenix-marketcity",
    "name": "Phoenix Marketcity",
    "zone": "central-chennai",
    "sortOrder": 364,
    "priorityTier": 3
  },
  {
    "slug": "pondy-bazaar",
    "name": "Pondy Bazaar",
    "zone": "central-chennai",
    "sortOrder": 365,
    "priorityTier": 3
  },
  {
    "slug": "ponneri",
    "name": "Ponneri",
    "zone": "north-suburbs",
    "sortOrder": 366,
    "priorityTier": 3
  },
  {
    "slug": "ponniammanmedu",
    "name": "Ponniammanmedu",
    "zone": "central-chennai",
    "sortOrder": 367,
    "priorityTier": 3
  },
  {
    "slug": "poonamallee",
    "name": "Poonamallee",
    "zone": "central-chennai",
    "sortOrder": 368,
    "priorityTier": 3
  },
  {
    "slug": "poonamallee-cantonment",
    "name": "Poonamallee Cantonment",
    "zone": "central-chennai",
    "sortOrder": 369,
    "priorityTier": 3
  },
  {
    "slug": "poonamallee-high-road",
    "name": "Poonamallee High Road",
    "zone": "central-chennai",
    "sortOrder": 370,
    "priorityTier": 3
  },
  {
    "slug": "porur",
    "name": "Porur",
    "zone": "west-chennai",
    "sortOrder": 371,
    "priorityTier": 1
  },
  {
    "slug": "porur-gardens",
    "name": "Porur Gardens",
    "zone": "west-chennai",
    "sortOrder": 372,
    "priorityTier": 3
  },
  {
    "slug": "potheri",
    "name": "Potheri",
    "zone": "central-chennai",
    "sortOrder": 373,
    "priorityTier": 3
  },
  {
    "slug": "pozhichalur",
    "name": "Pozhichalur",
    "zone": "central-chennai",
    "sortOrder": 374,
    "priorityTier": 3
  },
  {
    "slug": "pudupakkam",
    "name": "Pudupakkam",
    "zone": "central-chennai",
    "sortOrder": 375,
    "priorityTier": 3
  },
  {
    "slug": "pudupet",
    "name": "Pudupet",
    "zone": "central-chennai",
    "sortOrder": 376,
    "priorityTier": 3
  },
  {
    "slug": "pudur-ambattur",
    "name": "Pudur Ambattur",
    "zone": "north-chennai",
    "sortOrder": 377,
    "priorityTier": 3
  },
  {
    "slug": "pulianthope",
    "name": "Pulianthope",
    "zone": "central-chennai",
    "sortOrder": 378,
    "priorityTier": 3
  },
  {
    "slug": "purasawalkam",
    "name": "Purasawalkam",
    "zone": "central-chennai",
    "sortOrder": 379,
    "priorityTier": 3
  },
  {
    "slug": "puzhal",
    "name": "Puzhal",
    "zone": "central-chennai",
    "sortOrder": 380,
    "priorityTier": 3
  },
  {
    "slug": "puzhuthivakkam",
    "name": "Puzhuthivakkam",
    "zone": "central-chennai",
    "sortOrder": 381,
    "priorityTier": 3
  },
  {
    "slug": "ra-puram",
    "name": "R.a. Puram",
    "zone": "central-chennai",
    "sortOrder": 382,
    "priorityTier": 3
  },
  {
    "slug": "rk-nagar",
    "name": "R.k. Nagar",
    "zone": "central-chennai",
    "sortOrder": 383,
    "priorityTier": 3
  },
  {
    "slug": "raj-bhavan",
    "name": "Raj Bhavan",
    "zone": "central-chennai",
    "sortOrder": 384,
    "priorityTier": 3
  },
  {
    "slug": "raja-annamalaipuram",
    "name": "Raja Annamalaipuram",
    "zone": "central-chennai",
    "sortOrder": 385,
    "priorityTier": 3
  },
  {
    "slug": "rajakilpakkam",
    "name": "Rajakilpakkam",
    "zone": "central-chennai",
    "sortOrder": 386,
    "priorityTier": 3
  },
  {
    "slug": "rajakilpakkam-tambaram",
    "name": "Rajakilpakkam Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 387,
    "priorityTier": 3
  },
  {
    "slug": "rajiv-gandhi-salai",
    "name": "Rajiv Gandhi Salai",
    "zone": "central-chennai",
    "sortOrder": 388,
    "priorityTier": 3
  },
  {
    "slug": "ramapuram",
    "name": "Ramapuram",
    "zone": "central-chennai",
    "sortOrder": 389,
    "priorityTier": 3
  },
  {
    "slug": "ramapuram-dlf",
    "name": "Ramapuram DLF",
    "zone": "central-chennai",
    "sortOrder": 390,
    "priorityTier": 3
  },
  {
    "slug": "ramavaram",
    "name": "Ramavaram",
    "zone": "central-chennai",
    "sortOrder": 391,
    "priorityTier": 3
  },
  {
    "slug": "red-hills",
    "name": "Red Hills",
    "zone": "north-suburbs",
    "sortOrder": 392,
    "priorityTier": 3
  },
  {
    "slug": "ritherdon-road",
    "name": "Ritherdon Road",
    "zone": "central-chennai",
    "sortOrder": 393,
    "priorityTier": 3
  },
  {
    "slug": "royapettah",
    "name": "Royapettah",
    "zone": "central-chennai",
    "sortOrder": 394,
    "priorityTier": 2
  },
  {
    "slug": "royapuram",
    "name": "Royapuram",
    "zone": "central-chennai",
    "sortOrder": 395,
    "priorityTier": 3
  },
  {
    "slug": "sadayan-kuppam",
    "name": "Sadayan Kuppam",
    "zone": "central-chennai",
    "sortOrder": 396,
    "priorityTier": 3
  },
  {
    "slug": "sadayankuppam",
    "name": "Sadayankuppam",
    "zone": "central-chennai",
    "sortOrder": 397,
    "priorityTier": 3
  },
  {
    "slug": "saidapet",
    "name": "Saidapet",
    "zone": "south-chennai",
    "sortOrder": 398,
    "priorityTier": 2
  },
  {
    "slug": "saligramam",
    "name": "Saligramam",
    "zone": "central-chennai",
    "sortOrder": 399,
    "priorityTier": 3
  },
  {
    "slug": "sanatorium-tambaram",
    "name": "Sanatorium Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 400,
    "priorityTier": 3
  },
  {
    "slug": "santhome",
    "name": "Santhome",
    "zone": "central-chennai",
    "sortOrder": 401,
    "priorityTier": 3
  },
  {
    "slug": "santhosapuram",
    "name": "Santhosapuram",
    "zone": "central-chennai",
    "sortOrder": 402,
    "priorityTier": 3
  },
  {
    "slug": "sastri-nagar",
    "name": "Sastri Nagar",
    "zone": "central-chennai",
    "sortOrder": 403,
    "priorityTier": 3
  },
  {
    "slug": "sathangadu",
    "name": "Sathangadu",
    "zone": "central-chennai",
    "sortOrder": 404,
    "priorityTier": 3
  },
  {
    "slug": "sathuvachari-chennai",
    "name": "Sathuvachari Chennai",
    "zone": "central-chennai",
    "sortOrder": 405,
    "priorityTier": 3
  },
  {
    "slug": "selaivayal",
    "name": "Selaivayal",
    "zone": "central-chennai",
    "sortOrder": 406,
    "priorityTier": 3
  },
  {
    "slug": "selaiyur",
    "name": "Selaiyur",
    "zone": "central-chennai",
    "sortOrder": 407,
    "priorityTier": 2
  },
  {
    "slug": "selaiyur-camp-road",
    "name": "Selaiyur Camp Road",
    "zone": "central-chennai",
    "sortOrder": 408,
    "priorityTier": 3
  },
  {
    "slug": "sembakkam",
    "name": "Sembakkam",
    "zone": "central-chennai",
    "sortOrder": 409,
    "priorityTier": 3
  },
  {
    "slug": "sembiam",
    "name": "Sembiam",
    "zone": "central-chennai",
    "sortOrder": 410,
    "priorityTier": 3
  },
  {
    "slug": "semmenchery",
    "name": "Semmenchery",
    "zone": "central-chennai",
    "sortOrder": 411,
    "priorityTier": 3
  },
  {
    "slug": "semmenchery-omr",
    "name": "Semmenchery OMR",
    "zone": "omr-corridor",
    "sortOrder": 412,
    "priorityTier": 1
  },
  {
    "slug": "senneerkuppam",
    "name": "Senneerkuppam",
    "zone": "central-chennai",
    "sortOrder": 413,
    "priorityTier": 3
  },
  {
    "slug": "senthil-nagar",
    "name": "Senthil Nagar",
    "zone": "central-chennai",
    "sortOrder": 414,
    "priorityTier": 3
  },
  {
    "slug": "seven-wells",
    "name": "Seven Wells",
    "zone": "central-chennai",
    "sortOrder": 415,
    "priorityTier": 3
  },
  {
    "slug": "sevvapet",
    "name": "Sevvapet",
    "zone": "central-chennai",
    "sortOrder": 416,
    "priorityTier": 3
  },
  {
    "slug": "shenoy-nagar",
    "name": "Shenoy Nagar",
    "zone": "central-chennai",
    "sortOrder": 417,
    "priorityTier": 3
  },
  {
    "slug": "shenoy-nagar-east",
    "name": "Shenoy Nagar East",
    "zone": "central-chennai",
    "sortOrder": 418,
    "priorityTier": 3
  },
  {
    "slug": "sholavaram",
    "name": "Sholavaram",
    "zone": "central-chennai",
    "sortOrder": 419,
    "priorityTier": 3
  },
  {
    "slug": "sholinganallur",
    "name": "Sholinganallur",
    "zone": "omr-corridor",
    "sortOrder": 420,
    "priorityTier": 1
  },
  {
    "slug": "sholinganallur-omr",
    "name": "Sholinganallur OMR",
    "zone": "omr-corridor",
    "sortOrder": 421,
    "priorityTier": 1
  },
  {
    "slug": "singaperumal-koil",
    "name": "Singaperumal Koil",
    "zone": "central-chennai",
    "sortOrder": 422,
    "priorityTier": 3
  },
  {
    "slug": "siruseri",
    "name": "Siruseri",
    "zone": "omr-corridor",
    "sortOrder": 423,
    "priorityTier": 2
  },
  {
    "slug": "siruseri-sipcot",
    "name": "Siruseri Sipcot",
    "zone": "central-chennai",
    "sortOrder": 424,
    "priorityTier": 3
  },
  {
    "slug": "sithalapakkam",
    "name": "Sithalapakkam",
    "zone": "central-chennai",
    "sortOrder": 425,
    "priorityTier": 3
  },
  {
    "slug": "sivaprakash-nagar",
    "name": "Sivaprakash Nagar",
    "zone": "central-chennai",
    "sortOrder": 426,
    "priorityTier": 3
  },
  {
    "slug": "sowcarpet",
    "name": "Sowcarpet",
    "zone": "central-chennai",
    "sortOrder": 427,
    "priorityTier": 3
  },
  {
    "slug": "spencer-plaza",
    "name": "Spencer Plaza",
    "zone": "central-chennai",
    "sortOrder": 428,
    "priorityTier": 3
  },
  {
    "slug": "srinivasa-nagar-north",
    "name": "Srinivasa Nagar North",
    "zone": "central-chennai",
    "sortOrder": 429,
    "priorityTier": 3
  },
  {
    "slug": "st-thomas-mount",
    "name": "St. Thomas Mount",
    "zone": "central-chennai",
    "sortOrder": 430,
    "priorityTier": 3
  },
  {
    "slug": "surapet",
    "name": "Surapet",
    "zone": "central-chennai",
    "sortOrder": 431,
    "priorityTier": 3
  },
  {
    "slug": "t-nagar",
    "name": "T. Nagar",
    "zone": "central-chennai",
    "sortOrder": 432,
    "priorityTier": 1
  },
  {
    "slug": "tambaram",
    "name": "Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 433,
    "priorityTier": 1
  },
  {
    "slug": "tambaram-east",
    "name": "Tambaram East",
    "zone": "south-suburbs",
    "sortOrder": 434,
    "priorityTier": 3
  },
  {
    "slug": "tambaram-railway-colony",
    "name": "Tambaram Railway Colony",
    "zone": "south-suburbs",
    "sortOrder": 435,
    "priorityTier": 3
  },
  {
    "slug": "tambaram-sanatorium",
    "name": "Tambaram Sanatorium",
    "zone": "south-suburbs",
    "sortOrder": 436,
    "priorityTier": 3
  },
  {
    "slug": "tambaram-west",
    "name": "Tambaram West",
    "zone": "south-suburbs",
    "sortOrder": 437,
    "priorityTier": 3
  },
  {
    "slug": "taramani",
    "name": "Taramani",
    "zone": "south-chennai",
    "sortOrder": 438,
    "priorityTier": 3
  },
  {
    "slug": "taylors-road",
    "name": "Taylor's Road",
    "zone": "central-chennai",
    "sortOrder": 439,
    "priorityTier": 3
  },
  {
    "slug": "teynampet",
    "name": "Teynampet",
    "zone": "central-chennai",
    "sortOrder": 440,
    "priorityTier": 3
  },
  {
    "slug": "thaiyur",
    "name": "Thaiyur",
    "zone": "central-chennai",
    "sortOrder": 441,
    "priorityTier": 3
  },
  {
    "slug": "thalambur",
    "name": "Thalambur",
    "zone": "central-chennai",
    "sortOrder": 442,
    "priorityTier": 3
  },
  {
    "slug": "thalambur-omr",
    "name": "Thalambur OMR",
    "zone": "omr-corridor",
    "sortOrder": 443,
    "priorityTier": 1
  },
  {
    "slug": "thandalam",
    "name": "Thandalam",
    "zone": "central-chennai",
    "sortOrder": 444,
    "priorityTier": 3
  },
  {
    "slug": "thangal",
    "name": "Thangal",
    "zone": "central-chennai",
    "sortOrder": 445,
    "priorityTier": 3
  },
  {
    "slug": "thirumangalam",
    "name": "Thirumangalam",
    "zone": "central-chennai",
    "sortOrder": 446,
    "priorityTier": 3
  },
  {
    "slug": "thirumangalam-extension",
    "name": "Thirumangalam Extension",
    "zone": "central-chennai",
    "sortOrder": 447,
    "priorityTier": 3
  },
  {
    "slug": "thirumazhisai",
    "name": "Thirumazhisai",
    "zone": "central-chennai",
    "sortOrder": 448,
    "priorityTier": 3
  },
  {
    "slug": "thirumudivakkam",
    "name": "Thirumudivakkam",
    "zone": "central-chennai",
    "sortOrder": 449,
    "priorityTier": 3
  },
  {
    "slug": "thirumullaivoyal",
    "name": "Thirumullaivoyal",
    "zone": "central-chennai",
    "sortOrder": 450,
    "priorityTier": 3
  },
  {
    "slug": "thirunindravur",
    "name": "Thirunindravur",
    "zone": "central-chennai",
    "sortOrder": 451,
    "priorityTier": 3
  },
  {
    "slug": "thiruninravur",
    "name": "Thiruninravur",
    "zone": "central-chennai",
    "sortOrder": 452,
    "priorityTier": 3
  },
  {
    "slug": "thiruvanmiyur",
    "name": "Thiruvanmiyur",
    "zone": "central-chennai",
    "sortOrder": 453,
    "priorityTier": 1
  },
  {
    "slug": "thiruvanmiyur-valmiki-nagar",
    "name": "Thiruvanmiyur Valmiki Nagar",
    "zone": "central-chennai",
    "sortOrder": 454,
    "priorityTier": 3
  },
  {
    "slug": "thiruverkadu",
    "name": "Thiruverkadu",
    "zone": "central-chennai",
    "sortOrder": 455,
    "priorityTier": 3
  },
  {
    "slug": "thiruvottiyur",
    "name": "Thiruvottiyur",
    "zone": "central-chennai",
    "sortOrder": 456,
    "priorityTier": 3
  },
  {
    "slug": "thoraipakkam",
    "name": "Thoraipakkam",
    "zone": "omr-corridor",
    "sortOrder": 457,
    "priorityTier": 1
  },
  {
    "slug": "thoraipakkam-omr",
    "name": "Thoraipakkam OMR",
    "zone": "omr-corridor",
    "sortOrder": 458,
    "priorityTier": 1
  },
  {
    "slug": "tirumangalam-chennai",
    "name": "Tirumangalam Chennai",
    "zone": "central-chennai",
    "sortOrder": 459,
    "priorityTier": 3
  },
  {
    "slug": "tirusulam",
    "name": "Tirusulam",
    "zone": "central-chennai",
    "sortOrder": 460,
    "priorityTier": 3
  },
  {
    "slug": "tiruvottiyur-west",
    "name": "Tiruvottiyur West",
    "zone": "central-chennai",
    "sortOrder": 461,
    "priorityTier": 3
  },
  {
    "slug": "tondiarpet",
    "name": "Tondiarpet",
    "zone": "central-chennai",
    "sortOrder": 462,
    "priorityTier": 3
  },
  {
    "slug": "triplicane",
    "name": "Triplicane",
    "zone": "central-chennai",
    "sortOrder": 463,
    "priorityTier": 3
  },
  {
    "slug": "ullagaram",
    "name": "Ullagaram",
    "zone": "central-chennai",
    "sortOrder": 464,
    "priorityTier": 3
  },
  {
    "slug": "urapakkam",
    "name": "Urapakkam",
    "zone": "central-chennai",
    "sortOrder": 465,
    "priorityTier": 3
  },
  {
    "slug": "urapakkam-east",
    "name": "Urapakkam East",
    "zone": "central-chennai",
    "sortOrder": 466,
    "priorityTier": 3
  },
  {
    "slug": "urapakkam-west",
    "name": "Urapakkam West",
    "zone": "central-chennai",
    "sortOrder": 467,
    "priorityTier": 3
  },
  {
    "slug": "uthandi",
    "name": "Uthandi",
    "zone": "central-chennai",
    "sortOrder": 468,
    "priorityTier": 3
  },
  {
    "slug": "vadakkupattu",
    "name": "Vadakkupattu",
    "zone": "central-chennai",
    "sortOrder": 469,
    "priorityTier": 3
  },
  {
    "slug": "vadapalani",
    "name": "Vadapalani",
    "zone": "central-chennai",
    "sortOrder": 470,
    "priorityTier": 1
  },
  {
    "slug": "vadapalani-bus-terminus",
    "name": "Vadapalani Bus Terminus",
    "zone": "central-chennai",
    "sortOrder": 471,
    "priorityTier": 3
  },
  {
    "slug": "vadaperumbakkam",
    "name": "Vadaperumbakkam",
    "zone": "central-chennai",
    "sortOrder": 472,
    "priorityTier": 3
  },
  {
    "slug": "valasaravakkam",
    "name": "Valasaravakkam",
    "zone": "west-chennai",
    "sortOrder": 473,
    "priorityTier": 2
  },
  {
    "slug": "valasaravakkam-extension",
    "name": "Valasaravakkam Extension",
    "zone": "west-chennai",
    "sortOrder": 474,
    "priorityTier": 3
  },
  {
    "slug": "vallur",
    "name": "Vallur",
    "zone": "central-chennai",
    "sortOrder": 475,
    "priorityTier": 3
  },
  {
    "slug": "valmiki-nagar",
    "name": "Valmiki Nagar",
    "zone": "central-chennai",
    "sortOrder": 476,
    "priorityTier": 3
  },
  {
    "slug": "vanagaram",
    "name": "Vanagaram",
    "zone": "central-chennai",
    "sortOrder": 477,
    "priorityTier": 3
  },
  {
    "slug": "vanagaram-mettukuppam",
    "name": "Vanagaram Mettukuppam",
    "zone": "central-chennai",
    "sortOrder": 478,
    "priorityTier": 3
  },
  {
    "slug": "vandalur",
    "name": "Vandalur",
    "zone": "central-chennai",
    "sortOrder": 479,
    "priorityTier": 3
  },
  {
    "slug": "vandalur-kelambakkam-road",
    "name": "Vandalur Kelambakkam Road",
    "zone": "central-chennai",
    "sortOrder": 480,
    "priorityTier": 3
  },
  {
    "slug": "vandalur-zoo-area",
    "name": "Vandalur Zoo Area",
    "zone": "central-chennai",
    "sortOrder": 481,
    "priorityTier": 3
  },
  {
    "slug": "velachery",
    "name": "Velachery",
    "zone": "south-chennai",
    "sortOrder": 482,
    "priorityTier": 1
  },
  {
    "slug": "velachery-baby-nagar",
    "name": "Velachery Baby Nagar",
    "zone": "central-chennai",
    "sortOrder": 483,
    "priorityTier": 3
  },
  {
    "slug": "velachery-dhandeeswaram",
    "name": "Velachery Dhandeeswaram",
    "zone": "central-chennai",
    "sortOrder": 484,
    "priorityTier": 3
  },
  {
    "slug": "velachery-main-road",
    "name": "Velachery Main Road",
    "zone": "central-chennai",
    "sortOrder": 485,
    "priorityTier": 3
  },
  {
    "slug": "velachery-vijaya-nagar",
    "name": "Velachery Vijaya Nagar",
    "zone": "central-chennai",
    "sortOrder": 486,
    "priorityTier": 3
  },
  {
    "slug": "velappanchavadi",
    "name": "Velappanchavadi",
    "zone": "north-chennai",
    "sortOrder": 487,
    "priorityTier": 3
  },
  {
    "slug": "vengaivasal",
    "name": "Vengaivasal",
    "zone": "central-chennai",
    "sortOrder": 488,
    "priorityTier": 3
  },
  {
    "slug": "vepery",
    "name": "Vepery",
    "zone": "central-chennai",
    "sortOrder": 489,
    "priorityTier": 3
  },
  {
    "slug": "vepery-high-road",
    "name": "Vepery High Road",
    "zone": "central-chennai",
    "sortOrder": 490,
    "priorityTier": 3
  },
  {
    "slug": "veppampattu",
    "name": "Veppampattu",
    "zone": "central-chennai",
    "sortOrder": 491,
    "priorityTier": 3
  },
  {
    "slug": "vettuvankeni",
    "name": "Vettuvankeni",
    "zone": "central-chennai",
    "sortOrder": 492,
    "priorityTier": 3
  },
  {
    "slug": "vichoor",
    "name": "Vichoor",
    "zone": "central-chennai",
    "sortOrder": 493,
    "priorityTier": 3
  },
  {
    "slug": "villivakkam",
    "name": "Villivakkam",
    "zone": "central-chennai",
    "sortOrder": 494,
    "priorityTier": 3
  },
  {
    "slug": "virugambakkam",
    "name": "Virugambakkam",
    "zone": "west-chennai",
    "sortOrder": 495,
    "priorityTier": 2
  },
  {
    "slug": "vyasarpadi",
    "name": "Vyasarpadi",
    "zone": "central-chennai",
    "sortOrder": 496,
    "priorityTier": 3
  },
  {
    "slug": "washermenpet",
    "name": "Washermenpet",
    "zone": "central-chennai",
    "sortOrder": 497,
    "priorityTier": 3
  },
  {
    "slug": "west-mambalam",
    "name": "West Mambalam",
    "zone": "central-chennai",
    "sortOrder": 498,
    "priorityTier": 3
  },
  {
    "slug": "west-tambaram",
    "name": "West Tambaram",
    "zone": "south-suburbs",
    "sortOrder": 499,
    "priorityTier": 3
  },
  {
    "slug": "wimco-nagar",
    "name": "Wimco Nagar",
    "zone": "central-chennai",
    "sortOrder": 500,
    "priorityTier": 3
  },
  {
    "slug": "zamin-pallavaram",
    "name": "Zamin Pallavaram",
    "zone": "south-suburbs",
    "sortOrder": 501,
    "priorityTier": 3
  }
];

export const CHENNAI_AREA_COUNT = 501;

export function getChennaiAreaBySlug(slug: string): ChennaiArea | undefined {
  return CHENNAI_AREAS.find((a) => a.slug === slug);
}
