/** Auto-generated by scripts/generate-chhattisgarh-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface ChhattisgarhArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const CHHATTISGARH_AREAS: ChhattisgarhArea[] = [
  {
    "slug": "balod",
    "name": "Balod",
    "zone": "durg-bhilai",
    "sortOrder": 1,
    "priorityTier": 3
  },
  {
    "slug": "baloda-bazar-bhatapara",
    "name": "Baloda Bazar-Bhatapara",
    "zone": "raipur-belt",
    "sortOrder": 2,
    "priorityTier": 3
  },
  {
    "slug": "balrampur-ramanujganj",
    "name": "Balrampur-Ramanujganj",
    "zone": "north-chhattisgarh",
    "sortOrder": 3,
    "priorityTier": 3
  },
  {
    "slug": "bastar",
    "name": "Bastar",
    "zone": "bastar-south",
    "sortOrder": 4,
    "priorityTier": 3
  },
  {
    "slug": "bemetara",
    "name": "Bemetara",
    "zone": "raipur-belt",
    "sortOrder": 5,
    "priorityTier": 3
  },
  {
    "slug": "bijapur",
    "name": "Bijapur",
    "zone": "bastar-south",
    "sortOrder": 6,
    "priorityTier": 3
  },
  {
    "slug": "bilaspur",
    "name": "Bilaspur",
    "zone": "bilaspur-belt",
    "sortOrder": 7,
    "priorityTier": 1
  },
  {
    "slug": "dantewada",
    "name": "Dantewada",
    "zone": "bastar-south",
    "sortOrder": 8,
    "priorityTier": 3
  },
  {
    "slug": "dhamtari",
    "name": "Dhamtari",
    "zone": "raipur-belt",
    "sortOrder": 9,
    "priorityTier": 2
  },
  {
    "slug": "durg",
    "name": "Durg",
    "zone": "durg-bhilai",
    "sortOrder": 10,
    "priorityTier": 1
  },
  {
    "slug": "gariaband",
    "name": "Gariaband",
    "zone": "raipur-belt",
    "sortOrder": 11,
    "priorityTier": 3
  },
  {
    "slug": "gaurela-pendra-marwahi",
    "name": "Gaurela-Pendra-Marwahi",
    "zone": "bilaspur-belt",
    "sortOrder": 12,
    "priorityTier": 3
  },
  {
    "slug": "janjgir-champa",
    "name": "Janjgir-Champa",
    "zone": "bilaspur-belt",
    "sortOrder": 13,
    "priorityTier": 3
  },
  {
    "slug": "jashpur",
    "name": "Jashpur",
    "zone": "north-chhattisgarh",
    "sortOrder": 14,
    "priorityTier": 3
  },
  {
    "slug": "kabirdham",
    "name": "Kabirdham",
    "zone": "kawardha-west",
    "sortOrder": 15,
    "priorityTier": 3
  },
  {
    "slug": "kanker",
    "name": "Kanker",
    "zone": "bastar-south",
    "sortOrder": 16,
    "priorityTier": 3
  },
  {
    "slug": "khairagarh-chhuikhadan-gandai",
    "name": "Khairagarh-Chhuikhadan-Gandai",
    "zone": "durg-bhilai",
    "sortOrder": 17,
    "priorityTier": 3
  },
  {
    "slug": "kondagaon",
    "name": "Kondagaon",
    "zone": "bastar-south",
    "sortOrder": 18,
    "priorityTier": 3
  },
  {
    "slug": "korba",
    "name": "Korba",
    "zone": "north-chhattisgarh",
    "sortOrder": 19,
    "priorityTier": 1
  },
  {
    "slug": "koriya",
    "name": "Koriya",
    "zone": "north-chhattisgarh",
    "sortOrder": 20,
    "priorityTier": 3
  },
  {
    "slug": "mahasamund",
    "name": "Mahasamund",
    "zone": "raipur-belt",
    "sortOrder": 21,
    "priorityTier": 2
  },
  {
    "slug": "manendragarh-chirmiri-bharatpur",
    "name": "Manendragarh-Chirmiri-Bharatpur",
    "zone": "north-chhattisgarh",
    "sortOrder": 22,
    "priorityTier": 3
  },
  {
    "slug": "mohla-manpur-ambagarh-chowki",
    "name": "Mohla-Manpur-Ambagarh Chowki",
    "zone": "durg-bhilai",
    "sortOrder": 23,
    "priorityTier": 3
  },
  {
    "slug": "mungeli",
    "name": "Mungeli",
    "zone": "bilaspur-belt",
    "sortOrder": 24,
    "priorityTier": 3
  },
  {
    "slug": "narayanpur",
    "name": "Narayanpur",
    "zone": "bastar-south",
    "sortOrder": 25,
    "priorityTier": 3
  },
  {
    "slug": "raigarh",
    "name": "Raigarh",
    "zone": "north-chhattisgarh",
    "sortOrder": 26,
    "priorityTier": 2
  },
  {
    "slug": "raipur",
    "name": "Raipur",
    "zone": "raipur-belt",
    "sortOrder": 27,
    "priorityTier": 1
  },
  {
    "slug": "rajnandgaon",
    "name": "Rajnandgaon",
    "zone": "durg-bhilai",
    "sortOrder": 28,
    "priorityTier": 2
  },
  {
    "slug": "sakti",
    "name": "Sakti",
    "zone": "bilaspur-belt",
    "sortOrder": 29,
    "priorityTier": 3
  },
  {
    "slug": "sarangarh-bilaigarh",
    "name": "Sarangarh-Bilaigarh",
    "zone": "north-chhattisgarh",
    "sortOrder": 30,
    "priorityTier": 3
  },
  {
    "slug": "sukma",
    "name": "Sukma",
    "zone": "bastar-south",
    "sortOrder": 31,
    "priorityTier": 3
  },
  {
    "slug": "surajpur",
    "name": "Surajpur",
    "zone": "north-chhattisgarh",
    "sortOrder": 32,
    "priorityTier": 3
  },
  {
    "slug": "surguja",
    "name": "Surguja",
    "zone": "north-chhattisgarh",
    "sortOrder": 33,
    "priorityTier": 3
  },
  {
    "slug": "naya-raipur",
    "name": "Naya Raipur",
    "zone": "raipur-belt",
    "sortOrder": 34,
    "priorityTier": 1
  },
  {
    "slug": "atal-nagar",
    "name": "Atal Nagar",
    "zone": "raipur-belt",
    "sortOrder": 35,
    "priorityTier": 2
  },
  {
    "slug": "abhanpur",
    "name": "Abhanpur",
    "zone": "raipur-belt",
    "sortOrder": 36,
    "priorityTier": 3
  },
  {
    "slug": "arang",
    "name": "Arang",
    "zone": "raipur-belt",
    "sortOrder": 37,
    "priorityTier": 3
  },
  {
    "slug": "tilda-newra",
    "name": "Tilda Newra",
    "zone": "raipur-belt",
    "sortOrder": 38,
    "priorityTier": 3
  },
  {
    "slug": "gobra-nawapara",
    "name": "Gobra Nawapara",
    "zone": "raipur-belt",
    "sortOrder": 39,
    "priorityTier": 3
  },
  {
    "slug": "mandir-hasaud",
    "name": "Mandir Hasaud",
    "zone": "raipur-belt",
    "sortOrder": 40,
    "priorityTier": 3
  },
  {
    "slug": "birgaon",
    "name": "Birgaon",
    "zone": "raipur-belt",
    "sortOrder": 41,
    "priorityTier": 3
  },
  {
    "slug": "siltara",
    "name": "Siltara",
    "zone": "raipur-belt",
    "sortOrder": 42,
    "priorityTier": 3
  },
  {
    "slug": "shankar-nagar",
    "name": "Shankar Nagar",
    "zone": "raipur-belt",
    "sortOrder": 43,
    "priorityTier": 1
  },
  {
    "slug": "telibandha",
    "name": "Telibandha",
    "zone": "raipur-belt",
    "sortOrder": 44,
    "priorityTier": 1
  },
  {
    "slug": "tatibandh",
    "name": "Tatibandh",
    "zone": "raipur-belt",
    "sortOrder": 45,
    "priorityTier": 3
  },
  {
    "slug": "devendra-nagar",
    "name": "Devendra Nagar",
    "zone": "raipur-belt",
    "sortOrder": 46,
    "priorityTier": 3
  },
  {
    "slug": "samta-colony",
    "name": "Samta Colony",
    "zone": "raipur-belt",
    "sortOrder": 47,
    "priorityTier": 3
  },
  {
    "slug": "mowa",
    "name": "Mowa",
    "zone": "raipur-belt",
    "sortOrder": 48,
    "priorityTier": 3
  },
  {
    "slug": "kachna",
    "name": "Kachna",
    "zone": "raipur-belt",
    "sortOrder": 49,
    "priorityTier": 3
  },
  {
    "slug": "saddu",
    "name": "Saddu",
    "zone": "raipur-belt",
    "sortOrder": 50,
    "priorityTier": 3
  },
  {
    "slug": "vip-road",
    "name": "VIP Road",
    "zone": "raipur-belt",
    "sortOrder": 51,
    "priorityTier": 3
  },
  {
    "slug": "avanti-vihar",
    "name": "Avanti Vihar",
    "zone": "raipur-belt",
    "sortOrder": 52,
    "priorityTier": 3
  },
  {
    "slug": "kota-raipur",
    "name": "Kota, Raipur",
    "zone": "raipur-belt",
    "sortOrder": 53,
    "priorityTier": 3
  },
  {
    "slug": "pandri",
    "name": "Pandri",
    "zone": "raipur-belt",
    "sortOrder": 54,
    "priorityTier": 3
  },
  {
    "slug": "civil-lines-raipur",
    "name": "Civil Lines, Raipur",
    "zone": "raipur-belt",
    "sortOrder": 55,
    "priorityTier": 3
  },
  {
    "slug": "gudhiyari",
    "name": "Gudhiyari",
    "zone": "raipur-belt",
    "sortOrder": 56,
    "priorityTier": 3
  },
  {
    "slug": "fafadih",
    "name": "Fafadih",
    "zone": "raipur-belt",
    "sortOrder": 57,
    "priorityTier": 3
  },
  {
    "slug": "amanaka",
    "name": "Amanaka",
    "zone": "raipur-belt",
    "sortOrder": 58,
    "priorityTier": 3
  },
  {
    "slug": "sejbahar",
    "name": "Sejbahar",
    "zone": "raipur-belt",
    "sortOrder": 59,
    "priorityTier": 3
  },
  {
    "slug": "labhandi",
    "name": "Labhandi",
    "zone": "raipur-belt",
    "sortOrder": 60,
    "priorityTier": 3
  },
  {
    "slug": "raipura",
    "name": "Raipura",
    "zone": "raipur-belt",
    "sortOrder": 61,
    "priorityTier": 3
  },
  {
    "slug": "hirapur",
    "name": "Hirapur",
    "zone": "raipur-belt",
    "sortOrder": 62,
    "priorityTier": 3
  },
  {
    "slug": "tikrapara",
    "name": "Tikrapara",
    "zone": "raipur-belt",
    "sortOrder": 63,
    "priorityTier": 3
  },
  {
    "slug": "dangania",
    "name": "Dangania",
    "zone": "raipur-belt",
    "sortOrder": 64,
    "priorityTier": 3
  },
  {
    "slug": "pachpedi-naka",
    "name": "Pachpedi Naka",
    "zone": "raipur-belt",
    "sortOrder": 65,
    "priorityTier": 3
  },
  {
    "slug": "byron-bazar",
    "name": "Byron Bazar",
    "zone": "raipur-belt",
    "sortOrder": 66,
    "priorityTier": 3
  },
  {
    "slug": "bhilai",
    "name": "Bhilai",
    "zone": "durg-bhilai",
    "sortOrder": 67,
    "priorityTier": 1
  },
  {
    "slug": "risali",
    "name": "Risali",
    "zone": "durg-bhilai",
    "sortOrder": 68,
    "priorityTier": 2
  },
  {
    "slug": "charoda",
    "name": "Charoda",
    "zone": "durg-bhilai",
    "sortOrder": 69,
    "priorityTier": 2
  },
  {
    "slug": "bhilai-3",
    "name": "Bhilai-3",
    "zone": "durg-bhilai",
    "sortOrder": 70,
    "priorityTier": 3
  },
  {
    "slug": "kumhari",
    "name": "Kumhari",
    "zone": "durg-bhilai",
    "sortOrder": 71,
    "priorityTier": 3
  },
  {
    "slug": "patan",
    "name": "Patan",
    "zone": "durg-bhilai",
    "sortOrder": 72,
    "priorityTier": 3
  },
  {
    "slug": "ahiwara",
    "name": "Ahiwara",
    "zone": "durg-bhilai",
    "sortOrder": 73,
    "priorityTier": 3
  },
  {
    "slug": "supela",
    "name": "Supela",
    "zone": "durg-bhilai",
    "sortOrder": 74,
    "priorityTier": 3
  },
  {
    "slug": "civic-centre",
    "name": "Civic Centre",
    "zone": "durg-bhilai",
    "sortOrder": 75,
    "priorityTier": 3
  },
  {
    "slug": "nehru-nagar-bhilai",
    "name": "Nehru Nagar, Bhilai",
    "zone": "durg-bhilai",
    "sortOrder": 76,
    "priorityTier": 3
  },
  {
    "slug": "junwani",
    "name": "Junwani",
    "zone": "durg-bhilai",
    "sortOrder": 77,
    "priorityTier": 3
  },
  {
    "slug": "khursipar",
    "name": "Khursipar",
    "zone": "durg-bhilai",
    "sortOrder": 78,
    "priorityTier": 3
  },
  {
    "slug": "jamul",
    "name": "Jamul",
    "zone": "durg-bhilai",
    "sortOrder": 79,
    "priorityTier": 3
  },
  {
    "slug": "utai",
    "name": "Utai",
    "zone": "durg-bhilai",
    "sortOrder": 80,
    "priorityTier": 3
  },
  {
    "slug": "dhamdha",
    "name": "Dhamdha",
    "zone": "durg-bhilai",
    "sortOrder": 81,
    "priorityTier": 3
  },
  {
    "slug": "power-house-bhilai",
    "name": "Power House, Bhilai",
    "zone": "durg-bhilai",
    "sortOrder": 82,
    "priorityTier": 3
  },
  {
    "slug": "takhatpur",
    "name": "Takhatpur",
    "zone": "bilaspur-belt",
    "sortOrder": 83,
    "priorityTier": 3
  },
  {
    "slug": "kota",
    "name": "Kota",
    "zone": "bilaspur-belt",
    "sortOrder": 84,
    "priorityTier": 3
  },
  {
    "slug": "ratanpur",
    "name": "Ratanpur",
    "zone": "bilaspur-belt",
    "sortOrder": 85,
    "priorityTier": 3
  },
  {
    "slug": "masturi",
    "name": "Masturi",
    "zone": "bilaspur-belt",
    "sortOrder": 86,
    "priorityTier": 3
  },
  {
    "slug": "belha",
    "name": "Belha",
    "zone": "bilaspur-belt",
    "sortOrder": 87,
    "priorityTier": 3
  },
  {
    "slug": "tifra",
    "name": "Tifra",
    "zone": "bilaspur-belt",
    "sortOrder": 88,
    "priorityTier": 3
  },
  {
    "slug": "sarkanda",
    "name": "Sarkanda",
    "zone": "bilaspur-belt",
    "sortOrder": 89,
    "priorityTier": 2
  },
  {
    "slug": "torwa",
    "name": "Torwa",
    "zone": "bilaspur-belt",
    "sortOrder": 90,
    "priorityTier": 3
  },
  {
    "slug": "vyapar-vihar",
    "name": "Vyapar Vihar",
    "zone": "bilaspur-belt",
    "sortOrder": 91,
    "priorityTier": 3
  },
  {
    "slug": "seepat",
    "name": "Seepat",
    "zone": "bilaspur-belt",
    "sortOrder": 92,
    "priorityTier": 3
  },
  {
    "slug": "lingiyadih",
    "name": "Lingiyadih",
    "zone": "bilaspur-belt",
    "sortOrder": 93,
    "priorityTier": 3
  },
  {
    "slug": "koni",
    "name": "Koni",
    "zone": "bilaspur-belt",
    "sortOrder": 94,
    "priorityTier": 3
  },
  {
    "slug": "rajkishor-nagar",
    "name": "Rajkishor Nagar",
    "zone": "bilaspur-belt",
    "sortOrder": 95,
    "priorityTier": 3
  },
  {
    "slug": "katghora",
    "name": "Katghora",
    "zone": "north-chhattisgarh",
    "sortOrder": 96,
    "priorityTier": 3
  },
  {
    "slug": "dipka",
    "name": "Dipka",
    "zone": "north-chhattisgarh",
    "sortOrder": 97,
    "priorityTier": 3
  },
  {
    "slug": "pali",
    "name": "Pali",
    "zone": "north-chhattisgarh",
    "sortOrder": 98,
    "priorityTier": 3
  },
  {
    "slug": "darri",
    "name": "Darri",
    "zone": "north-chhattisgarh",
    "sortOrder": 99,
    "priorityTier": 3
  },
  {
    "slug": "balco-nagar",
    "name": "BALCO Nagar",
    "zone": "north-chhattisgarh",
    "sortOrder": 100,
    "priorityTier": 3
  },
  {
    "slug": "kusmunda",
    "name": "Kusmunda",
    "zone": "north-chhattisgarh",
    "sortOrder": 101,
    "priorityTier": 3
  },
  {
    "slug": "gevra",
    "name": "Gevra",
    "zone": "north-chhattisgarh",
    "sortOrder": 102,
    "priorityTier": 3
  },
  {
    "slug": "jamnipali",
    "name": "Jamnipali",
    "zone": "north-chhattisgarh",
    "sortOrder": 103,
    "priorityTier": 3
  },
  {
    "slug": "korba-west",
    "name": "Korba West",
    "zone": "north-chhattisgarh",
    "sortOrder": 104,
    "priorityTier": 3
  },
  {
    "slug": "kharsia",
    "name": "Kharsia",
    "zone": "north-chhattisgarh",
    "sortOrder": 105,
    "priorityTier": 3
  },
  {
    "slug": "dharamjaigarh",
    "name": "Dharamjaigarh",
    "zone": "north-chhattisgarh",
    "sortOrder": 106,
    "priorityTier": 3
  },
  {
    "slug": "gharghoda",
    "name": "Gharghoda",
    "zone": "north-chhattisgarh",
    "sortOrder": 107,
    "priorityTier": 3
  },
  {
    "slug": "sarangarh",
    "name": "Sarangarh",
    "zone": "north-chhattisgarh",
    "sortOrder": 108,
    "priorityTier": 3
  },
  {
    "slug": "pusaur",
    "name": "Pusaur",
    "zone": "north-chhattisgarh",
    "sortOrder": 109,
    "priorityTier": 3
  },
  {
    "slug": "lailunga",
    "name": "Lailunga",
    "zone": "north-chhattisgarh",
    "sortOrder": 110,
    "priorityTier": 3
  },
  {
    "slug": "tamnar",
    "name": "Tamnar",
    "zone": "north-chhattisgarh",
    "sortOrder": 111,
    "priorityTier": 3
  },
  {
    "slug": "dongargarh",
    "name": "Dongargarh",
    "zone": "durg-bhilai",
    "sortOrder": 112,
    "priorityTier": 2
  },
  {
    "slug": "dongargaon",
    "name": "Dongargaon",
    "zone": "durg-bhilai",
    "sortOrder": 113,
    "priorityTier": 3
  },
  {
    "slug": "chhuikhadan",
    "name": "Chhuikhadan",
    "zone": "durg-bhilai",
    "sortOrder": 114,
    "priorityTier": 3
  },
  {
    "slug": "khairagarh",
    "name": "Khairagarh",
    "zone": "durg-bhilai",
    "sortOrder": 115,
    "priorityTier": 3
  },
  {
    "slug": "gandai",
    "name": "Gandai",
    "zone": "durg-bhilai",
    "sortOrder": 116,
    "priorityTier": 3
  },
  {
    "slug": "chhuriya",
    "name": "Chhuriya",
    "zone": "durg-bhilai",
    "sortOrder": 117,
    "priorityTier": 3
  },
  {
    "slug": "mohla",
    "name": "Mohla",
    "zone": "durg-bhilai",
    "sortOrder": 118,
    "priorityTier": 3
  },
  {
    "slug": "manpur",
    "name": "Manpur",
    "zone": "durg-bhilai",
    "sortOrder": 119,
    "priorityTier": 3
  },
  {
    "slug": "ambagarh-chowki",
    "name": "Ambagarh Chowki",
    "zone": "durg-bhilai",
    "sortOrder": 120,
    "priorityTier": 3
  },
  {
    "slug": "jagdalpur",
    "name": "Jagdalpur",
    "zone": "bastar-south",
    "sortOrder": 121,
    "priorityTier": 2
  },
  {
    "slug": "keshkal",
    "name": "Keshkal",
    "zone": "bastar-south",
    "sortOrder": 122,
    "priorityTier": 3
  },
  {
    "slug": "tokapal",
    "name": "Tokapal",
    "zone": "bastar-south",
    "sortOrder": 123,
    "priorityTier": 3
  },
  {
    "slug": "darbha",
    "name": "Darbha",
    "zone": "bastar-south",
    "sortOrder": 124,
    "priorityTier": 3
  },
  {
    "slug": "bakawand",
    "name": "Bakawand",
    "zone": "bastar-south",
    "sortOrder": 125,
    "priorityTier": 3
  },
  {
    "slug": "lohandiguda",
    "name": "Lohandiguda",
    "zone": "bastar-south",
    "sortOrder": 126,
    "priorityTier": 3
  },
  {
    "slug": "ambikapur",
    "name": "Ambikapur",
    "zone": "north-chhattisgarh",
    "sortOrder": 127,
    "priorityTier": 2
  },
  {
    "slug": "sitapur",
    "name": "Sitapur",
    "zone": "north-chhattisgarh",
    "sortOrder": 128,
    "priorityTier": 3
  },
  {
    "slug": "lundra",
    "name": "Lundra",
    "zone": "north-chhattisgarh",
    "sortOrder": 129,
    "priorityTier": 3
  },
  {
    "slug": "lakhanpur",
    "name": "Lakhanpur",
    "zone": "north-chhattisgarh",
    "sortOrder": 130,
    "priorityTier": 3
  },
  {
    "slug": "udaipur",
    "name": "Udaipur",
    "zone": "north-chhattisgarh",
    "sortOrder": 131,
    "priorityTier": 3
  },
  {
    "slug": "pratappur",
    "name": "Pratappur",
    "zone": "north-chhattisgarh",
    "sortOrder": 132,
    "priorityTier": 3
  },
  {
    "slug": "rajpur",
    "name": "Rajpur",
    "zone": "north-chhattisgarh",
    "sortOrder": 133,
    "priorityTier": 3
  },
  {
    "slug": "wadrafnagar",
    "name": "Wadrafnagar",
    "zone": "north-chhattisgarh",
    "sortOrder": 134,
    "priorityTier": 3
  },
  {
    "slug": "batauli",
    "name": "Batauli",
    "zone": "north-chhattisgarh",
    "sortOrder": 135,
    "priorityTier": 3
  },
  {
    "slug": "mainpat",
    "name": "Mainpat",
    "zone": "north-chhattisgarh",
    "sortOrder": 136,
    "priorityTier": 3
  },
  {
    "slug": "ramanujganj",
    "name": "Ramanujganj",
    "zone": "north-chhattisgarh",
    "sortOrder": 137,
    "priorityTier": 3
  },
  {
    "slug": "kurud",
    "name": "Kurud",
    "zone": "raipur-belt",
    "sortOrder": 138,
    "priorityTier": 3
  },
  {
    "slug": "nagri",
    "name": "Nagri",
    "zone": "raipur-belt",
    "sortOrder": 139,
    "priorityTier": 3
  },
  {
    "slug": "magarlod",
    "name": "Magarlod",
    "zone": "raipur-belt",
    "sortOrder": 140,
    "priorityTier": 3
  },
  {
    "slug": "saraipali",
    "name": "Saraipali",
    "zone": "raipur-belt",
    "sortOrder": 141,
    "priorityTier": 3
  },
  {
    "slug": "basna",
    "name": "Basna",
    "zone": "raipur-belt",
    "sortOrder": 142,
    "priorityTier": 3
  },
  {
    "slug": "bagbahara",
    "name": "Bagbahara",
    "zone": "raipur-belt",
    "sortOrder": 143,
    "priorityTier": 3
  },
  {
    "slug": "pithora",
    "name": "Pithora",
    "zone": "raipur-belt",
    "sortOrder": 144,
    "priorityTier": 3
  },
  {
    "slug": "dondi",
    "name": "Dondi",
    "zone": "durg-bhilai",
    "sortOrder": 145,
    "priorityTier": 3
  },
  {
    "slug": "dondi-lohara",
    "name": "Dondi Lohara",
    "zone": "durg-bhilai",
    "sortOrder": 146,
    "priorityTier": 3
  },
  {
    "slug": "gunderdehi",
    "name": "Gunderdehi",
    "zone": "durg-bhilai",
    "sortOrder": 147,
    "priorityTier": 3
  },
  {
    "slug": "gurur",
    "name": "Gurur",
    "zone": "durg-bhilai",
    "sortOrder": 148,
    "priorityTier": 3
  },
  {
    "slug": "nawagarh",
    "name": "Nawagarh",
    "zone": "raipur-belt",
    "sortOrder": 149,
    "priorityTier": 3
  },
  {
    "slug": "berla",
    "name": "Berla",
    "zone": "raipur-belt",
    "sortOrder": 150,
    "priorityTier": 3
  },
  {
    "slug": "saja",
    "name": "Saja",
    "zone": "raipur-belt",
    "sortOrder": 151,
    "priorityTier": 3
  },
  {
    "slug": "kawardha",
    "name": "Kawardha",
    "zone": "kawardha-west",
    "sortOrder": 152,
    "priorityTier": 2
  },
  {
    "slug": "pandariya",
    "name": "Pandariya",
    "zone": "kawardha-west",
    "sortOrder": 153,
    "priorityTier": 3
  },
  {
    "slug": "bodla",
    "name": "Bodla",
    "zone": "kawardha-west",
    "sortOrder": 154,
    "priorityTier": 3
  },
  {
    "slug": "pandatarai",
    "name": "Pandatarai",
    "zone": "kawardha-west",
    "sortOrder": 155,
    "priorityTier": 3
  },
  {
    "slug": "lormi",
    "name": "Lormi",
    "zone": "bilaspur-belt",
    "sortOrder": 156,
    "priorityTier": 3
  },
  {
    "slug": "pathariya",
    "name": "Pathariya",
    "zone": "bilaspur-belt",
    "sortOrder": 157,
    "priorityTier": 3
  },
  {
    "slug": "janjgir",
    "name": "Janjgir",
    "zone": "bilaspur-belt",
    "sortOrder": 158,
    "priorityTier": 2
  },
  {
    "slug": "champa",
    "name": "Champa",
    "zone": "bilaspur-belt",
    "sortOrder": 159,
    "priorityTier": 2
  },
  {
    "slug": "akaltara",
    "name": "Akaltara",
    "zone": "bilaspur-belt",
    "sortOrder": 160,
    "priorityTier": 3
  },
  {
    "slug": "baradwar",
    "name": "Baradwar",
    "zone": "bilaspur-belt",
    "sortOrder": 161,
    "priorityTier": 3
  },
  {
    "slug": "naila-janjgir",
    "name": "Naila Janjgir",
    "zone": "bilaspur-belt",
    "sortOrder": 162,
    "priorityTier": 3
  },
  {
    "slug": "pamgarh",
    "name": "Pamgarh",
    "zone": "bilaspur-belt",
    "sortOrder": 163,
    "priorityTier": 3
  },
  {
    "slug": "shivrinarayan",
    "name": "Shivrinarayan",
    "zone": "bilaspur-belt",
    "sortOrder": 164,
    "priorityTier": 3
  },
  {
    "slug": "jashpur-nagar",
    "name": "Jashpur Nagar",
    "zone": "north-chhattisgarh",
    "sortOrder": 165,
    "priorityTier": 3
  },
  {
    "slug": "kunkuri",
    "name": "Kunkuri",
    "zone": "north-chhattisgarh",
    "sortOrder": 166,
    "priorityTier": 3
  },
  {
    "slug": "pathalgaon",
    "name": "Pathalgaon",
    "zone": "north-chhattisgarh",
    "sortOrder": 167,
    "priorityTier": 3
  },
  {
    "slug": "bagicha",
    "name": "Bagicha",
    "zone": "north-chhattisgarh",
    "sortOrder": 168,
    "priorityTier": 3
  },
  {
    "slug": "kansabel",
    "name": "Kansabel",
    "zone": "north-chhattisgarh",
    "sortOrder": 169,
    "priorityTier": 3
  },
  {
    "slug": "bhanupratappur",
    "name": "Bhanupratappur",
    "zone": "bastar-south",
    "sortOrder": 170,
    "priorityTier": 3
  },
  {
    "slug": "charama",
    "name": "Charama",
    "zone": "bastar-south",
    "sortOrder": 171,
    "priorityTier": 3
  },
  {
    "slug": "antagarh",
    "name": "Antagarh",
    "zone": "bastar-south",
    "sortOrder": 172,
    "priorityTier": 3
  },
  {
    "slug": "pakhanjur",
    "name": "Pakhanjur",
    "zone": "bastar-south",
    "sortOrder": 173,
    "priorityTier": 3
  },
  {
    "slug": "narharpur",
    "name": "Narharpur",
    "zone": "bastar-south",
    "sortOrder": 174,
    "priorityTier": 3
  },
  {
    "slug": "konta",
    "name": "Konta",
    "zone": "bastar-south",
    "sortOrder": 175,
    "priorityTier": 3
  },
  {
    "slug": "chhindgarh",
    "name": "Chhindgarh",
    "zone": "bastar-south",
    "sortOrder": 176,
    "priorityTier": 3
  },
  {
    "slug": "geedam",
    "name": "Geedam",
    "zone": "bastar-south",
    "sortOrder": 177,
    "priorityTier": 3
  },
  {
    "slug": "kirandul",
    "name": "Kirandul",
    "zone": "bastar-south",
    "sortOrder": 178,
    "priorityTier": 3
  },
  {
    "slug": "bacheli",
    "name": "Bacheli",
    "zone": "bastar-south",
    "sortOrder": 179,
    "priorityTier": 3
  },
  {
    "slug": "barsur",
    "name": "Barsur",
    "zone": "bastar-south",
    "sortOrder": 180,
    "priorityTier": 3
  },
  {
    "slug": "bhairamgarh",
    "name": "Bhairamgarh",
    "zone": "bastar-south",
    "sortOrder": 181,
    "priorityTier": 3
  },
  {
    "slug": "basaguda",
    "name": "Basaguda",
    "zone": "bastar-south",
    "sortOrder": 182,
    "priorityTier": 3
  },
  {
    "slug": "bhopalpatnam",
    "name": "Bhopalpatnam",
    "zone": "bastar-south",
    "sortOrder": 183,
    "priorityTier": 3
  },
  {
    "slug": "gaurela",
    "name": "Gaurela",
    "zone": "bilaspur-belt",
    "sortOrder": 184,
    "priorityTier": 3
  },
  {
    "slug": "pendra",
    "name": "Pendra",
    "zone": "bilaspur-belt",
    "sortOrder": 185,
    "priorityTier": 3
  },
  {
    "slug": "marwahi",
    "name": "Marwahi",
    "zone": "bilaspur-belt",
    "sortOrder": 186,
    "priorityTier": 3
  },
  {
    "slug": "pendra-road",
    "name": "Pendra Road",
    "zone": "bilaspur-belt",
    "sortOrder": 187,
    "priorityTier": 3
  },
  {
    "slug": "manendragarh",
    "name": "Manendragarh",
    "zone": "north-chhattisgarh",
    "sortOrder": 188,
    "priorityTier": 3
  },
  {
    "slug": "chirmiri",
    "name": "Chirmiri",
    "zone": "north-chhattisgarh",
    "sortOrder": 189,
    "priorityTier": 3
  },
  {
    "slug": "bharatpur",
    "name": "Bharatpur",
    "zone": "north-chhattisgarh",
    "sortOrder": 190,
    "priorityTier": 3
  },
  {
    "slug": "baikunthpur",
    "name": "Baikunthpur",
    "zone": "north-chhattisgarh",
    "sortOrder": 191,
    "priorityTier": 3
  },
  {
    "slug": "bishrampur",
    "name": "Bishrampur",
    "zone": "north-chhattisgarh",
    "sortOrder": 192,
    "priorityTier": 3
  },
  {
    "slug": "premnagar",
    "name": "Premnagar",
    "zone": "north-chhattisgarh",
    "sortOrder": 193,
    "priorityTier": 3
  },
  {
    "slug": "odgi",
    "name": "Odgi",
    "zone": "north-chhattisgarh",
    "sortOrder": 194,
    "priorityTier": 3
  },
  {
    "slug": "rajim",
    "name": "Rajim",
    "zone": "raipur-belt",
    "sortOrder": 195,
    "priorityTier": 3
  },
  {
    "slug": "chhura",
    "name": "Chhura",
    "zone": "raipur-belt",
    "sortOrder": 196,
    "priorityTier": 3
  },
  {
    "slug": "deobhog",
    "name": "Deobhog",
    "zone": "raipur-belt",
    "sortOrder": 197,
    "priorityTier": 3
  },
  {
    "slug": "bindranawagarh",
    "name": "Bindranawagarh",
    "zone": "raipur-belt",
    "sortOrder": 198,
    "priorityTier": 3
  },
  {
    "slug": "baloda-bazar",
    "name": "Baloda Bazar",
    "zone": "raipur-belt",
    "sortOrder": 199,
    "priorityTier": 3
  },
  {
    "slug": "bhatapara",
    "name": "Bhatapara",
    "zone": "raipur-belt",
    "sortOrder": 200,
    "priorityTier": 2
  },
  {
    "slug": "simga",
    "name": "Simga",
    "zone": "raipur-belt",
    "sortOrder": 201,
    "priorityTier": 3
  },
  {
    "slug": "palari",
    "name": "Palari",
    "zone": "raipur-belt",
    "sortOrder": 202,
    "priorityTier": 3
  },
  {
    "slug": "kasdol",
    "name": "Kasdol",
    "zone": "raipur-belt",
    "sortOrder": 203,
    "priorityTier": 3
  },
  {
    "slug": "bilaigarh",
    "name": "Bilaigarh",
    "zone": "north-chhattisgarh",
    "sortOrder": 204,
    "priorityTier": 3
  },
  {
    "slug": "lawan",
    "name": "Lawan",
    "zone": "raipur-belt",
    "sortOrder": 205,
    "priorityTier": 3
  },
  {
    "slug": "balrampur",
    "name": "Balrampur",
    "zone": "north-chhattisgarh",
    "sortOrder": 206,
    "priorityTier": 3
  },
  {
    "slug": "kusmi",
    "name": "Kusmi",
    "zone": "north-chhattisgarh",
    "sortOrder": 207,
    "priorityTier": 3
  },
  {
    "slug": "shankargarh",
    "name": "Shankargarh",
    "zone": "north-chhattisgarh",
    "sortOrder": 208,
    "priorityTier": 3
  }
];

export const CHHATTISGARH_AREA_COUNT = 208;

export function getChhattisgarhAreaBySlug(slug: string): ChhattisgarhArea | undefined {
  return CHHATTISGARH_AREAS.find((a) => a.slug === slug);
}
