/** Auto-generated by scripts/generate-coimbatore-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface CoimbatoreArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const COIMBATORE_AREAS: CoimbatoreArea[] = [
  {
    "slug": "100-feet-road-coimbatore",
    "name": "100 Feet Road Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 1,
    "priorityTier": 3
  },
  {
    "slug": "aathi-nagar",
    "name": "Aathi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 2,
    "priorityTier": 3
  },
  {
    "slug": "achipatti",
    "name": "Achipatti",
    "zone": "coimbatore-central",
    "sortOrder": 3,
    "priorityTier": 3
  },
  {
    "slug": "aero-nagar",
    "name": "Aero Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 4,
    "priorityTier": 3
  },
  {
    "slug": "agraharam-singanallur",
    "name": "Agraharam Singanallur",
    "zone": "singanallur",
    "sortOrder": 5,
    "priorityTier": 3
  },
  {
    "slug": "agraharapudur",
    "name": "Agraharapudur",
    "zone": "coimbatore-central",
    "sortOrder": 6,
    "priorityTier": 3
  },
  {
    "slug": "airport-area-coimbatore",
    "name": "Airport Area Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 7,
    "priorityTier": 3
  },
  {
    "slug": "aishwarya-nagar",
    "name": "Aishwarya Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 8,
    "priorityTier": 3
  },
  {
    "slug": "akkanaickenpalayam",
    "name": "Akkanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 9,
    "priorityTier": 3
  },
  {
    "slug": "akkaraisengapalli",
    "name": "Akkaraisengapalli",
    "zone": "coimbatore-central",
    "sortOrder": 10,
    "priorityTier": 3
  },
  {
    "slug": "akshaya-nagar",
    "name": "Akshaya Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 11,
    "priorityTier": 3
  },
  {
    "slug": "alagesan-road",
    "name": "Alagesan Road",
    "zone": "coimbatore-central",
    "sortOrder": 12,
    "priorityTier": 3
  },
  {
    "slug": "alandurai",
    "name": "Alandurai",
    "zone": "coimbatore-central",
    "sortOrder": 13,
    "priorityTier": 3
  },
  {
    "slug": "alandurai-bus-stand-area",
    "name": "Alandurai Bus Stand Area",
    "zone": "coimbatore-central",
    "sortOrder": 14,
    "priorityTier": 3
  },
  {
    "slug": "alandurai-road",
    "name": "Alandurai Road",
    "zone": "coimbatore-central",
    "sortOrder": 15,
    "priorityTier": 3
  },
  {
    "slug": "alandurai-road-junction",
    "name": "Alandurai Road Junction",
    "zone": "coimbatore-central",
    "sortOrder": 16,
    "priorityTier": 3
  },
  {
    "slug": "alanthurai",
    "name": "Alanthurai",
    "zone": "coimbatore-central",
    "sortOrder": 17,
    "priorityTier": 3
  },
  {
    "slug": "aliyar",
    "name": "Aliyar",
    "zone": "coimbatore-central",
    "sortOrder": 18,
    "priorityTier": 3
  },
  {
    "slug": "allapalayam",
    "name": "Allapalayam",
    "zone": "coimbatore-central",
    "sortOrder": 19,
    "priorityTier": 3
  },
  {
    "slug": "ambarampalayam",
    "name": "Ambarampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 20,
    "priorityTier": 3
  },
  {
    "slug": "amman-kovil-saravanampatti",
    "name": "Amman Kovil Saravanampatti",
    "zone": "saravanampatti",
    "sortOrder": 21,
    "priorityTier": 3
  },
  {
    "slug": "ammankulam",
    "name": "Ammankulam",
    "zone": "coimbatore-central",
    "sortOrder": 22,
    "priorityTier": 3
  },
  {
    "slug": "amrita-university-coimbatore-area",
    "name": "Amrita University Coimbatore Area",
    "zone": "coimbatore-central",
    "sortOrder": 23,
    "priorityTier": 3
  },
  {
    "slug": "anaimalai",
    "name": "Anaimalai",
    "zone": "coimbatore-central",
    "sortOrder": 24,
    "priorityTier": 3
  },
  {
    "slug": "anaimalai-town",
    "name": "Anaimalai Town",
    "zone": "coimbatore-central",
    "sortOrder": 25,
    "priorityTier": 3
  },
  {
    "slug": "angalakurichi",
    "name": "Angalakurichi",
    "zone": "kurichi-industrial",
    "sortOrder": 26,
    "priorityTier": 3
  },
  {
    "slug": "anna-nagar-ganapathy",
    "name": "Anna Nagar Ganapathy",
    "zone": "coimbatore-central",
    "sortOrder": 27,
    "priorityTier": 3
  },
  {
    "slug": "anna-nagar-peelamedu",
    "name": "Anna Nagar Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 28,
    "priorityTier": 1
  },
  {
    "slug": "anna-nagar-saibaba-colony",
    "name": "Anna Nagar Saibaba Colony",
    "zone": "saibaba-colony",
    "sortOrder": 29,
    "priorityTier": 3
  },
  {
    "slug": "annanur-coimbatore",
    "name": "Annanur Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 30,
    "priorityTier": 3
  },
  {
    "slug": "annur",
    "name": "Annur",
    "zone": "mettupalayam-belt",
    "sortOrder": 31,
    "priorityTier": 2
  },
  {
    "slug": "annur-bus-stand-area",
    "name": "Annur Bus Stand Area",
    "zone": "mettupalayam-belt",
    "sortOrder": 32,
    "priorityTier": 3
  },
  {
    "slug": "annur-main-road",
    "name": "Annur Main Road",
    "zone": "mettupalayam-belt",
    "sortOrder": 33,
    "priorityTier": 3
  },
  {
    "slug": "annur-town",
    "name": "Annur Town",
    "zone": "mettupalayam-belt",
    "sortOrder": 34,
    "priorityTier": 3
  },
  {
    "slug": "anugraha-gardens",
    "name": "Anugraha Gardens",
    "zone": "coimbatore-central",
    "sortOrder": 35,
    "priorityTier": 3
  },
  {
    "slug": "anupperpalayam",
    "name": "Anupperpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 36,
    "priorityTier": 3
  },
  {
    "slug": "appanaickenpalayam",
    "name": "Appanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 37,
    "priorityTier": 3
  },
  {
    "slug": "arasampalayam",
    "name": "Arasampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 38,
    "priorityTier": 3
  },
  {
    "slug": "arasampalayam-kinathukadavu",
    "name": "Arasampalayam Kinathukadavu",
    "zone": "pollachi-belt",
    "sortOrder": 39,
    "priorityTier": 3
  },
  {
    "slug": "arasur",
    "name": "Arasur",
    "zone": "coimbatore-central",
    "sortOrder": 40,
    "priorityTier": 3
  },
  {
    "slug": "arasur-industrial-area",
    "name": "Arasur Industrial Area",
    "zone": "coimbatore-central",
    "sortOrder": 41,
    "priorityTier": 3
  },
  {
    "slug": "arisipalayam",
    "name": "Arisipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 42,
    "priorityTier": 3
  },
  {
    "slug": "arun-nagar-vadavalli",
    "name": "Arun Nagar Vadavalli",
    "zone": "saibaba-colony",
    "sortOrder": 43,
    "priorityTier": 3
  },
  {
    "slug": "ashokapuram-podanur",
    "name": "Ashokapuram Podanur",
    "zone": "coimbatore-central",
    "sortOrder": 44,
    "priorityTier": 3
  },
  {
    "slug": "athipalayam",
    "name": "Athipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 45,
    "priorityTier": 3
  },
  {
    "slug": "athipalayam-road",
    "name": "Athipalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 46,
    "priorityTier": 3
  },
  {
    "slug": "athupalam",
    "name": "Athupalam",
    "zone": "coimbatore-central",
    "sortOrder": 47,
    "priorityTier": 3
  },
  {
    "slug": "athur-pollachi",
    "name": "Athur Pollachi",
    "zone": "pollachi-belt",
    "sortOrder": 48,
    "priorityTier": 3
  },
  {
    "slug": "att-colony",
    "name": "ATT Colony",
    "zone": "coimbatore-central",
    "sortOrder": 49,
    "priorityTier": 3
  },
  {
    "slug": "avalchinnampalayam",
    "name": "Avalchinnampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 50,
    "priorityTier": 3
  },
  {
    "slug": "avarampalayam",
    "name": "Avarampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 51,
    "priorityTier": 3
  },
  {
    "slug": "avarampalayam-new-scheme-road",
    "name": "Avarampalayam New Scheme Road",
    "zone": "coimbatore-central",
    "sortOrder": 52,
    "priorityTier": 3
  },
  {
    "slug": "avarampalayam-road",
    "name": "Avarampalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 53,
    "priorityTier": 3
  },
  {
    "slug": "avinashi-road",
    "name": "Avinashi Road",
    "zone": "peelamedu-it",
    "sortOrder": 54,
    "priorityTier": 1
  },
  {
    "slug": "avinashi-road-flyover-area",
    "name": "Avinashi Road Flyover Area",
    "zone": "peelamedu-it",
    "sortOrder": 55,
    "priorityTier": 3
  },
  {
    "slug": "avinashi-road-it-corridor",
    "name": "Avinashi Road It Corridor",
    "zone": "peelamedu-it",
    "sortOrder": 56,
    "priorityTier": 3
  },
  {
    "slug": "avinashi-road-lakshmi-mills",
    "name": "Avinashi Road Lakshmi Mills",
    "zone": "peelamedu-it",
    "sortOrder": 57,
    "priorityTier": 3
  },
  {
    "slug": "avinashi-road-peelamedu",
    "name": "Avinashi Road Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 58,
    "priorityTier": 1
  },
  {
    "slug": "avinashi-road-sitra",
    "name": "Avinashi Road Sitra",
    "zone": "peelamedu-it",
    "sortOrder": 59,
    "priorityTier": 3
  },
  {
    "slug": "avinashilingam-university-area",
    "name": "Avinashilingam University Area",
    "zone": "peelamedu-it",
    "sortOrder": 60,
    "priorityTier": 3
  },
  {
    "slug": "balaji-nagar-coimbatore",
    "name": "Balaji Nagar Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 61,
    "priorityTier": 3
  },
  {
    "slug": "balaji-nagar-ramanathapuram",
    "name": "Balaji Nagar Ramanathapuram",
    "zone": "coimbatore-central",
    "sortOrder": 62,
    "priorityTier": 3
  },
  {
    "slug": "balasundaram-road",
    "name": "Balasundaram Road",
    "zone": "coimbatore-central",
    "sortOrder": 63,
    "priorityTier": 3
  },
  {
    "slug": "belladhi",
    "name": "Belladhi",
    "zone": "coimbatore-central",
    "sortOrder": 64,
    "priorityTier": 3
  },
  {
    "slug": "bettathapuram",
    "name": "Bettathapuram",
    "zone": "coimbatore-central",
    "sortOrder": 65,
    "priorityTier": 3
  },
  {
    "slug": "bharathi-colony",
    "name": "Bharathi Colony",
    "zone": "coimbatore-central",
    "sortOrder": 66,
    "priorityTier": 3
  },
  {
    "slug": "bharathi-colony-peelamedu",
    "name": "Bharathi Colony Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 67,
    "priorityTier": 1
  },
  {
    "slug": "bharathi-nagar-ganapathy",
    "name": "Bharathi Nagar Ganapathy",
    "zone": "coimbatore-central",
    "sortOrder": 68,
    "priorityTier": 3
  },
  {
    "slug": "bharathi-park",
    "name": "Bharathi Park",
    "zone": "coimbatore-central",
    "sortOrder": 69,
    "priorityTier": 3
  },
  {
    "slug": "bharathi-park-cross-road",
    "name": "Bharathi Park Cross Road",
    "zone": "coimbatore-central",
    "sortOrder": 70,
    "priorityTier": 3
  },
  {
    "slug": "bharathiar-road",
    "name": "Bharathiar Road",
    "zone": "coimbatore-central",
    "sortOrder": 71,
    "priorityTier": 3
  },
  {
    "slug": "bharathiar-university-area",
    "name": "Bharathiar University Area",
    "zone": "coimbatore-central",
    "sortOrder": 72,
    "priorityTier": 3
  },
  {
    "slug": "bharathiar-university-road",
    "name": "Bharathiar University Road",
    "zone": "coimbatore-central",
    "sortOrder": 73,
    "priorityTier": 3
  },
  {
    "slug": "big-bazaar-street",
    "name": "Big Bazaar Street",
    "zone": "coimbatore-central",
    "sortOrder": 74,
    "priorityTier": 3
  },
  {
    "slug": "bilal-estate",
    "name": "Bilal Estate",
    "zone": "coimbatore-central",
    "sortOrder": 75,
    "priorityTier": 3
  },
  {
    "slug": "bilichi",
    "name": "Bilichi",
    "zone": "coimbatore-central",
    "sortOrder": 76,
    "priorityTier": 3
  },
  {
    "slug": "bk-pudur",
    "name": "Bk Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 77,
    "priorityTier": 3
  },
  {
    "slug": "bodipalayam",
    "name": "Bodipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 78,
    "priorityTier": 3
  },
  {
    "slug": "boluvampatti",
    "name": "Boluvampatti",
    "zone": "coimbatore-central",
    "sortOrder": 79,
    "priorityTier": 3
  },
  {
    "slug": "bommanampalayam",
    "name": "Bommanampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 80,
    "priorityTier": 3
  },
  {
    "slug": "brindavan-nagar",
    "name": "Brindavan Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 81,
    "priorityTier": 3
  },
  {
    "slug": "brookefields-area",
    "name": "Brookefields Area",
    "zone": "coimbatore-central",
    "sortOrder": 82,
    "priorityTier": 2
  },
  {
    "slug": "bypass-road-ukkadam",
    "name": "Bypass Road Ukkadam",
    "zone": "coimbatore-central",
    "sortOrder": 83,
    "priorityTier": 3
  },
  {
    "slug": "cheran-colony-thudiyalur",
    "name": "Cheran Colony Thudiyalur",
    "zone": "coimbatore-central",
    "sortOrder": 84,
    "priorityTier": 3
  },
  {
    "slug": "cheran-ma-nagar",
    "name": "Cheran Ma Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 85,
    "priorityTier": 3
  },
  {
    "slug": "cheran-nagar",
    "name": "Cheran Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 86,
    "priorityTier": 3
  },
  {
    "slug": "cheran-nagar-koundampalayam",
    "name": "Cheran Nagar Koundampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 87,
    "priorityTier": 3
  },
  {
    "slug": "cheran-nagar-vilankurichi",
    "name": "Cheran Nagar Vilankurichi",
    "zone": "saravanampatti",
    "sortOrder": 88,
    "priorityTier": 3
  },
  {
    "slug": "chettipalayam",
    "name": "Chettipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 89,
    "priorityTier": 3
  },
  {
    "slug": "chettipalayam-kinathukadavu",
    "name": "Chettipalayam Kinathukadavu",
    "zone": "pollachi-belt",
    "sortOrder": 90,
    "priorityTier": 3
  },
  {
    "slug": "chettipalayam-road-perur",
    "name": "Chettipalayam Road Perur",
    "zone": "coimbatore-central",
    "sortOrder": 91,
    "priorityTier": 3
  },
  {
    "slug": "chil-sez-area",
    "name": "CHIL SEZ Area",
    "zone": "coimbatore-central",
    "sortOrder": 92,
    "priorityTier": 3
  },
  {
    "slug": "chinnamathampalayam",
    "name": "Chinnamathampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 93,
    "priorityTier": 3
  },
  {
    "slug": "chinnammal-street",
    "name": "Chinnammal Street",
    "zone": "coimbatore-central",
    "sortOrder": 94,
    "priorityTier": 3
  },
  {
    "slug": "chinnampalayam-pollachi",
    "name": "Chinnampalayam Pollachi",
    "zone": "pollachi-belt",
    "sortOrder": 95,
    "priorityTier": 3
  },
  {
    "slug": "chinnathadagam",
    "name": "Chinnathadagam",
    "zone": "coimbatore-central",
    "sortOrder": 96,
    "priorityTier": 3
  },
  {
    "slug": "chinnavedampatti",
    "name": "Chinnavedampatti",
    "zone": "coimbatore-central",
    "sortOrder": 97,
    "priorityTier": 3
  },
  {
    "slug": "chinnavedampatti-housing-unit",
    "name": "Chinnavedampatti Housing Unit",
    "zone": "coimbatore-central",
    "sortOrder": 98,
    "priorityTier": 3
  },
  {
    "slug": "chinnavedampatti-road",
    "name": "Chinnavedampatti Road",
    "zone": "coimbatore-central",
    "sortOrder": 99,
    "priorityTier": 3
  },
  {
    "slug": "chinniampalayam",
    "name": "Chinniampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 100,
    "priorityTier": 3
  },
  {
    "slug": "chinniampalayam-bypass",
    "name": "Chinniampalayam Bypass",
    "zone": "coimbatore-central",
    "sortOrder": 101,
    "priorityTier": 3
  },
  {
    "slug": "chinniampalayam-road",
    "name": "Chinniampalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 102,
    "priorityTier": 3
  },
  {
    "slug": "chinthamanipudur",
    "name": "Chinthamanipudur",
    "zone": "coimbatore-central",
    "sortOrder": 103,
    "priorityTier": 3
  },
  {
    "slug": "chinthamanipudur-sulur",
    "name": "Chinthamanipudur Sulur",
    "zone": "kurichi-industrial",
    "sortOrder": 104,
    "priorityTier": 3
  },
  {
    "slug": "chokkampudur",
    "name": "Chokkampudur",
    "zone": "coimbatore-central",
    "sortOrder": 105,
    "priorityTier": 3
  },
  {
    "slug": "civil-aerodrome",
    "name": "Civil Aerodrome",
    "zone": "coimbatore-central",
    "sortOrder": 106,
    "priorityTier": 3
  },
  {
    "slug": "classic-gardens",
    "name": "Classic Gardens",
    "zone": "coimbatore-central",
    "sortOrder": 107,
    "priorityTier": 3
  },
  {
    "slug": "cms-school-area-ganapathy",
    "name": "Cms School Area Ganapathy",
    "zone": "coimbatore-central",
    "sortOrder": 108,
    "priorityTier": 3
  },
  {
    "slug": "codissia-trade-fair-complex-area",
    "name": "Codissia Trade Fair Complex Area",
    "zone": "coimbatore-central",
    "sortOrder": 109,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-central",
    "name": "Coimbatore Central",
    "zone": "coimbatore-central",
    "sortOrder": 110,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-institute-of-technology-area",
    "name": "Coimbatore Institute Of Technology Area",
    "zone": "coimbatore-central",
    "sortOrder": 111,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-international-airport-area",
    "name": "Coimbatore International Airport Area",
    "zone": "coimbatore-central",
    "sortOrder": 112,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-junction-area",
    "name": "Coimbatore Junction Area",
    "zone": "coimbatore-central",
    "sortOrder": 113,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-medical-college-area",
    "name": "Coimbatore Medical College Area",
    "zone": "coimbatore-central",
    "sortOrder": 114,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-north",
    "name": "Coimbatore North",
    "zone": "coimbatore-central",
    "sortOrder": 115,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-sidco-industrial-estate",
    "name": "Coimbatore SIDCO Industrial Estate",
    "zone": "coimbatore-central",
    "sortOrder": 116,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-south",
    "name": "Coimbatore South",
    "zone": "coimbatore-central",
    "sortOrder": 117,
    "priorityTier": 3
  },
  {
    "slug": "coimbatore-stock-exchange-area",
    "name": "Coimbatore Stock Exchange Area",
    "zone": "coimbatore-central",
    "sortOrder": 118,
    "priorityTier": 3
  },
  {
    "slug": "collectorate-area",
    "name": "Collectorate Area",
    "zone": "coimbatore-central",
    "sortOrder": 119,
    "priorityTier": 3
  },
  {
    "slug": "cooperative-colony",
    "name": "Cooperative Colony",
    "zone": "coimbatore-central",
    "sortOrder": 120,
    "priorityTier": 3
  },
  {
    "slug": "cross-cut-road",
    "name": "Cross Cut Road",
    "zone": "coimbatore-central",
    "sortOrder": 121,
    "priorityTier": 3
  },
  {
    "slug": "dasampalayam",
    "name": "Dasampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 122,
    "priorityTier": 3
  },
  {
    "slug": "db-road",
    "name": "Db Road",
    "zone": "coimbatore-central",
    "sortOrder": 123,
    "priorityTier": 3
  },
  {
    "slug": "deenampalayam",
    "name": "Deenampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 124,
    "priorityTier": 3
  },
  {
    "slug": "devangapet",
    "name": "Devangapet",
    "zone": "coimbatore-central",
    "sortOrder": 125,
    "priorityTier": 3
  },
  {
    "slug": "devarayapuram-kinathukadavu",
    "name": "Devarayapuram Kinathukadavu",
    "zone": "pollachi-belt",
    "sortOrder": 126,
    "priorityTier": 3
  },
  {
    "slug": "dhaliyur",
    "name": "Dhalyur",
    "zone": "coimbatore-central",
    "sortOrder": 127,
    "priorityTier": 3
  },
  {
    "slug": "dhamu-nagar",
    "name": "Dhamu Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 128,
    "priorityTier": 3
  },
  {
    "slug": "dhamu-nagar-puliakulam",
    "name": "Dhamu Nagar Puliakulam",
    "zone": "coimbatore-central",
    "sortOrder": 129,
    "priorityTier": 3
  },
  {
    "slug": "dhanalakshmi-nagar",
    "name": "Dhanalakshmi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 130,
    "priorityTier": 3
  },
  {
    "slug": "dhanalakshmipuram",
    "name": "Dhanalakshmipuram",
    "zone": "coimbatore-central",
    "sortOrder": 131,
    "priorityTier": 3
  },
  {
    "slug": "diwan-bahadur-road",
    "name": "Diwan Bahadur Road",
    "zone": "coimbatore-central",
    "sortOrder": 132,
    "priorityTier": 3
  },
  {
    "slug": "dr-nanjappa-road",
    "name": "Dr. Nanjappa Road",
    "zone": "coimbatore-central",
    "sortOrder": 133,
    "priorityTier": 3
  },
  {
    "slug": "dr-radhakrishnan-road",
    "name": "Dr. Radhakrishnan Road",
    "zone": "coimbatore-central",
    "sortOrder": 134,
    "priorityTier": 3
  },
  {
    "slug": "eb-colony",
    "name": "E.B. Colony",
    "zone": "coimbatore-central",
    "sortOrder": 135,
    "priorityTier": 3
  },
  {
    "slug": "eachanari",
    "name": "Eachanari",
    "zone": "pollachi-belt",
    "sortOrder": 136,
    "priorityTier": 2
  },
  {
    "slug": "eachanari-industrial-area",
    "name": "Eachanari Industrial Area",
    "zone": "coimbatore-central",
    "sortOrder": 137,
    "priorityTier": 3
  },
  {
    "slug": "eachanari-temple-area",
    "name": "Eachanari Temple Area",
    "zone": "coimbatore-central",
    "sortOrder": 138,
    "priorityTier": 3
  },
  {
    "slug": "east-arokiasamy-road",
    "name": "East Arokiasamy Road",
    "zone": "coimbatore-central",
    "sortOrder": 139,
    "priorityTier": 3
  },
  {
    "slug": "edayar-street",
    "name": "Edayar Street",
    "zone": "coimbatore-central",
    "sortOrder": 140,
    "priorityTier": 3
  },
  {
    "slug": "edayarpalayam",
    "name": "Edayarpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 141,
    "priorityTier": 3
  },
  {
    "slug": "edayarpalayam-vadavalli",
    "name": "Edayarpalayam Vadavalli",
    "zone": "saibaba-colony",
    "sortOrder": 142,
    "priorityTier": 3
  },
  {
    "slug": "ellai-thottam",
    "name": "Ellai Thottam",
    "zone": "coimbatore-central",
    "sortOrder": 143,
    "priorityTier": 3
  },
  {
    "slug": "esi-hospital-area",
    "name": "ESI Hospital Area",
    "zone": "coimbatore-central",
    "sortOrder": 144,
    "priorityTier": 3
  },
  {
    "slug": "ettimadai",
    "name": "Ettimadai",
    "zone": "coimbatore-central",
    "sortOrder": 145,
    "priorityTier": 3
  },
  {
    "slug": "ettimadai-rf",
    "name": "Ettimadai R.f.",
    "zone": "coimbatore-central",
    "sortOrder": 146,
    "priorityTier": 3
  },
  {
    "slug": "fathima-nagar-saravanampatti",
    "name": "Fathima Nagar Saravanampatti",
    "zone": "saravanampatti",
    "sortOrder": 147,
    "priorityTier": 3
  },
  {
    "slug": "fci-road",
    "name": "FCI Road",
    "zone": "coimbatore-central",
    "sortOrder": 148,
    "priorityTier": 3
  },
  {
    "slug": "forest-college-campus-area",
    "name": "Forest College Campus Area",
    "zone": "coimbatore-central",
    "sortOrder": 149,
    "priorityTier": 3
  },
  {
    "slug": "gn-mills",
    "name": "G.N. Mills",
    "zone": "coimbatore-central",
    "sortOrder": 150,
    "priorityTier": 3
  },
  {
    "slug": "ganapathy",
    "name": "Ganapathy",
    "zone": "coimbatore-central",
    "sortOrder": 151,
    "priorityTier": 2
  },
  {
    "slug": "ganapathy-housing-unit",
    "name": "Ganapathy Housing Unit",
    "zone": "coimbatore-central",
    "sortOrder": 152,
    "priorityTier": 3
  },
  {
    "slug": "ganapathy-industrial-estate",
    "name": "Ganapathy Industrial Estate",
    "zone": "coimbatore-central",
    "sortOrder": 153,
    "priorityTier": 3
  },
  {
    "slug": "ganapathy-maanagar",
    "name": "Ganapathy Maanagar",
    "zone": "coimbatore-central",
    "sortOrder": 154,
    "priorityTier": 3
  },
  {
    "slug": "ganapathy-pudur",
    "name": "Ganapathy Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 155,
    "priorityTier": 3
  },
  {
    "slug": "gandhi-maa-nagar",
    "name": "Gandhi Maa Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 156,
    "priorityTier": 3
  },
  {
    "slug": "gandhi-nagar-kavundampalayam",
    "name": "Gandhi Nagar Kavundampalayam",
    "zone": "saibaba-colony",
    "sortOrder": 157,
    "priorityTier": 3
  },
  {
    "slug": "gandhi-nagar-peelamedu",
    "name": "Gandhi Nagar Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 158,
    "priorityTier": 1
  },
  {
    "slug": "gandhi-park",
    "name": "Gandhi Park",
    "zone": "coimbatore-central",
    "sortOrder": 159,
    "priorityTier": 3
  },
  {
    "slug": "gandhiji-road",
    "name": "Gandhiji Road",
    "zone": "coimbatore-central",
    "sortOrder": 160,
    "priorityTier": 3
  },
  {
    "slug": "gandhimaa-nagar",
    "name": "Gandhimaa Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 161,
    "priorityTier": 3
  },
  {
    "slug": "gandhipuram",
    "name": "Gandhipuram",
    "zone": "coimbatore-central",
    "sortOrder": 162,
    "priorityTier": 1
  },
  {
    "slug": "gandhipuram-100-feet-road",
    "name": "Gandhipuram 100 Feet Road",
    "zone": "coimbatore-central",
    "sortOrder": 163,
    "priorityTier": 1
  },
  {
    "slug": "gandhipuram-2nd-street",
    "name": "Gandhipuram 2nd Street",
    "zone": "coimbatore-central",
    "sortOrder": 164,
    "priorityTier": 1
  },
  {
    "slug": "gandhipuram-bus-stand-area",
    "name": "Gandhipuram Bus Stand Area",
    "zone": "coimbatore-central",
    "sortOrder": 165,
    "priorityTier": 1
  },
  {
    "slug": "ganesh-layout",
    "name": "Ganesh Layout",
    "zone": "coimbatore-central",
    "sortOrder": 166,
    "priorityTier": 3
  },
  {
    "slug": "ganeshapuram-annur",
    "name": "Ganeshapuram Annur",
    "zone": "mettupalayam-belt",
    "sortOrder": 167,
    "priorityTier": 3
  },
  {
    "slug": "gct-college-area",
    "name": "Gct College Area",
    "zone": "coimbatore-central",
    "sortOrder": 168,
    "priorityTier": 3
  },
  {
    "slug": "gokulam-colony",
    "name": "Gokulam Colony",
    "zone": "coimbatore-central",
    "sortOrder": 169,
    "priorityTier": 3
  },
  {
    "slug": "goldwins",
    "name": "Goldwins",
    "zone": "coimbatore-central",
    "sortOrder": 170,
    "priorityTier": 3
  },
  {
    "slug": "gomangalam",
    "name": "Gomangalam",
    "zone": "coimbatore-central",
    "sortOrder": 171,
    "priorityTier": 3
  },
  {
    "slug": "gopalapuram",
    "name": "Gopalapuram",
    "zone": "coimbatore-central",
    "sortOrder": 172,
    "priorityTier": 3
  },
  {
    "slug": "gounder-mills",
    "name": "Gounder Mills",
    "zone": "coimbatore-central",
    "sortOrder": 173,
    "priorityTier": 3
  },
  {
    "slug": "govanur",
    "name": "Govanur",
    "zone": "coimbatore-central",
    "sortOrder": 174,
    "priorityTier": 3
  },
  {
    "slug": "government-arts-college-road",
    "name": "Government Arts College Road",
    "zone": "coimbatore-central",
    "sortOrder": 175,
    "priorityTier": 3
  },
  {
    "slug": "green-fields",
    "name": "Green Fields",
    "zone": "coimbatore-central",
    "sortOrder": 176,
    "priorityTier": 3
  },
  {
    "slug": "grey-town",
    "name": "Grey Town",
    "zone": "coimbatore-central",
    "sortOrder": 177,
    "priorityTier": 3
  },
  {
    "slug": "gudalur-coimbatore",
    "name": "Gudalur Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 178,
    "priorityTier": 3
  },
  {
    "slug": "gudalur-municipality-coimbatore",
    "name": "Gudalur Municipality Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 179,
    "priorityTier": 3
  },
  {
    "slug": "gv-residency",
    "name": "Gv Residency",
    "zone": "coimbatore-central",
    "sortOrder": 180,
    "priorityTier": 3
  },
  {
    "slug": "hope-college",
    "name": "Hope College",
    "zone": "coimbatore-central",
    "sortOrder": 181,
    "priorityTier": 3
  },
  {
    "slug": "hopes-college-junction",
    "name": "Hopes College Junction",
    "zone": "coimbatore-central",
    "sortOrder": 182,
    "priorityTier": 3
  },
  {
    "slug": "housing-unit-coimbatore",
    "name": "Housing Unit Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 183,
    "priorityTier": 3
  },
  {
    "slug": "hudco-colony-peelamedu",
    "name": "HUDCO Colony Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 184,
    "priorityTier": 1
  },
  {
    "slug": "huzur-road",
    "name": "Huzur Road",
    "zone": "coimbatore-central",
    "sortOrder": 185,
    "priorityTier": 3
  },
  {
    "slug": "idikarai-road",
    "name": "Idikarai Road",
    "zone": "coimbatore-central",
    "sortOrder": 186,
    "priorityTier": 3
  },
  {
    "slug": "ikkarai-boluvampatti",
    "name": "Ikkarai Boluvampatti",
    "zone": "coimbatore-central",
    "sortOrder": 187,
    "priorityTier": 3
  },
  {
    "slug": "indira-nagar-civil-aerodrome",
    "name": "Indira Nagar Civil Aerodrome",
    "zone": "coimbatore-central",
    "sortOrder": 188,
    "priorityTier": 3
  },
  {
    "slug": "indira-nagar-peelamedu",
    "name": "Indira Nagar Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 189,
    "priorityTier": 1
  },
  {
    "slug": "irugur",
    "name": "Irugur",
    "zone": "kurichi-industrial",
    "sortOrder": 190,
    "priorityTier": 2
  },
  {
    "slug": "irugur-junction",
    "name": "Irugur Junction",
    "zone": "coimbatore-central",
    "sortOrder": 191,
    "priorityTier": 3
  },
  {
    "slug": "irugur-pirivu",
    "name": "Irugur Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 192,
    "priorityTier": 3
  },
  {
    "slug": "iruttupallam",
    "name": "Iruttupallam",
    "zone": "coimbatore-central",
    "sortOrder": 193,
    "priorityTier": 3
  },
  {
    "slug": "isha-yoga-center-area",
    "name": "Isha Yoga Center Area",
    "zone": "coimbatore-central",
    "sortOrder": 194,
    "priorityTier": 3
  },
  {
    "slug": "jadayampalayam",
    "name": "Jadayampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 195,
    "priorityTier": 3
  },
  {
    "slug": "jai-shanthi-nagar",
    "name": "Jai Shanthi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 196,
    "priorityTier": 3
  },
  {
    "slug": "jameen-uthukuli",
    "name": "Jameen Uthukuli",
    "zone": "coimbatore-central",
    "sortOrder": 197,
    "priorityTier": 3
  },
  {
    "slug": "jaya-nagar-vadavalli",
    "name": "Jaya Nagar Vadavalli",
    "zone": "saibaba-colony",
    "sortOrder": 198,
    "priorityTier": 3
  },
  {
    "slug": "jeeva-nagar",
    "name": "Jeeva Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 199,
    "priorityTier": 3
  },
  {
    "slug": "jothipuram",
    "name": "Jothipuram",
    "zone": "coimbatore-central",
    "sortOrder": 200,
    "priorityTier": 3
  },
  {
    "slug": "kg-chavadi",
    "name": "K.g. Chavadi",
    "zone": "coimbatore-central",
    "sortOrder": 201,
    "priorityTier": 3
  },
  {
    "slug": "kk-pudur",
    "name": "K.K. Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 202,
    "priorityTier": 3
  },
  {
    "slug": "krg-nagar",
    "name": "K.R.G. Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 203,
    "priorityTier": 3
  },
  {
    "slug": "kadamparai-sulur",
    "name": "Kadamparai Sulur",
    "zone": "kurichi-industrial",
    "sortOrder": 204,
    "priorityTier": 3
  },
  {
    "slug": "kaikolapalayam",
    "name": "Kaikolapalayam",
    "zone": "coimbatore-central",
    "sortOrder": 205,
    "priorityTier": 3
  },
  {
    "slug": "kakkadavu",
    "name": "Kakkadavu",
    "zone": "coimbatore-central",
    "sortOrder": 206,
    "priorityTier": 3
  },
  {
    "slug": "kalapatti",
    "name": "Kalapatti",
    "zone": "saravanampatti",
    "sortOrder": 207,
    "priorityTier": 1
  },
  {
    "slug": "kalapatti-kurumbapalayam-road",
    "name": "Kalapatti Kurumbapalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 208,
    "priorityTier": 3
  },
  {
    "slug": "kalapatti-road",
    "name": "Kalapatti Road",
    "zone": "coimbatore-central",
    "sortOrder": 209,
    "priorityTier": 3
  },
  {
    "slug": "kaleeswara-mill-area",
    "name": "Kaleeswara Mill Area",
    "zone": "coimbatore-central",
    "sortOrder": 210,
    "priorityTier": 3
  },
  {
    "slug": "kalikkanaickenpalayam",
    "name": "Kalikkanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 211,
    "priorityTier": 3
  },
  {
    "slug": "kaliyapuram",
    "name": "Kaliyapuram",
    "zone": "coimbatore-central",
    "sortOrder": 212,
    "priorityTier": 3
  },
  {
    "slug": "kallapalayam-industrial-area",
    "name": "Kallapalayam Industrial Area",
    "zone": "coimbatore-central",
    "sortOrder": 213,
    "priorityTier": 3
  },
  {
    "slug": "kallimadai",
    "name": "Kallimadai",
    "zone": "coimbatore-central",
    "sortOrder": 214,
    "priorityTier": 3
  },
  {
    "slug": "kalluri-nagar-peelamedu",
    "name": "Kalluri Nagar Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 215,
    "priorityTier": 1
  },
  {
    "slug": "kalveerampalayam",
    "name": "Kalveerampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 216,
    "priorityTier": 3
  },
  {
    "slug": "kamakshi-nagar",
    "name": "Kamakshi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 217,
    "priorityTier": 3
  },
  {
    "slug": "kamaraj-road",
    "name": "Kamaraj Road",
    "zone": "coimbatore-central",
    "sortOrder": 218,
    "priorityTier": 3
  },
  {
    "slug": "kamarajar-road-coimbatore",
    "name": "Kamarajar Road Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 219,
    "priorityTier": 3
  },
  {
    "slug": "kandasamy-layout",
    "name": "Kandasamy Layout",
    "zone": "coimbatore-central",
    "sortOrder": 220,
    "priorityTier": 3
  },
  {
    "slug": "kandegounden-chavadi",
    "name": "Kandegounden Chavadi",
    "zone": "coimbatore-central",
    "sortOrder": 221,
    "priorityTier": 3
  },
  {
    "slug": "kangayampalayam",
    "name": "Kangayampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 222,
    "priorityTier": 3
  },
  {
    "slug": "kangayampalayam-road",
    "name": "Kangayampalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 223,
    "priorityTier": 3
  },
  {
    "slug": "kannampalayam",
    "name": "Kannampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 224,
    "priorityTier": 3
  },
  {
    "slug": "kannan-nagar",
    "name": "Kannan Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 225,
    "priorityTier": 3
  },
  {
    "slug": "kanuvai",
    "name": "Kanuvai",
    "zone": "coimbatore-central",
    "sortOrder": 226,
    "priorityTier": 3
  },
  {
    "slug": "kanuvai-road",
    "name": "Kanuvai Road",
    "zone": "coimbatore-central",
    "sortOrder": 227,
    "priorityTier": 3
  },
  {
    "slug": "karamadai",
    "name": "Karamadai",
    "zone": "mettupalayam-belt",
    "sortOrder": 228,
    "priorityTier": 2
  },
  {
    "slug": "karamadai-bus-stand-area",
    "name": "Karamadai Bus Stand Area",
    "zone": "mettupalayam-belt",
    "sortOrder": 229,
    "priorityTier": 3
  },
  {
    "slug": "karamadai-forest-area",
    "name": "Karamadai Forest Area",
    "zone": "mettupalayam-belt",
    "sortOrder": 230,
    "priorityTier": 3
  },
  {
    "slug": "karamadai-main-road",
    "name": "Karamadai Main Road",
    "zone": "mettupalayam-belt",
    "sortOrder": 231,
    "priorityTier": 3
  },
  {
    "slug": "karamadai-municipality",
    "name": "Karamadai Municipality",
    "zone": "mettupalayam-belt",
    "sortOrder": 232,
    "priorityTier": 3
  },
  {
    "slug": "karamadai-railway-station-area",
    "name": "Karamadai Railway Station Area",
    "zone": "mettupalayam-belt",
    "sortOrder": 233,
    "priorityTier": 3
  },
  {
    "slug": "karamadai-road",
    "name": "Karamadai Road",
    "zone": "mettupalayam-belt",
    "sortOrder": 234,
    "priorityTier": 3
  },
  {
    "slug": "karanampettai",
    "name": "Karanampettai",
    "zone": "coimbatore-central",
    "sortOrder": 235,
    "priorityTier": 3
  },
  {
    "slug": "kariampalayam",
    "name": "Kariampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 236,
    "priorityTier": 3
  },
  {
    "slug": "karpagam-college-area",
    "name": "Karpagam College Area",
    "zone": "coimbatore-central",
    "sortOrder": 237,
    "priorityTier": 3
  },
  {
    "slug": "karpagam-university-area",
    "name": "Karpagam University Area",
    "zone": "coimbatore-central",
    "sortOrder": 238,
    "priorityTier": 3
  },
  {
    "slug": "karumathampatti",
    "name": "Karumathampatti",
    "zone": "coimbatore-central",
    "sortOrder": 239,
    "priorityTier": 3
  },
  {
    "slug": "karumathampatti-industrial-area",
    "name": "Karumathampatti Industrial Area",
    "zone": "coimbatore-central",
    "sortOrder": 240,
    "priorityTier": 3
  },
  {
    "slug": "karumbukkadai",
    "name": "Karumbukkadai",
    "zone": "coimbatore-central",
    "sortOrder": 241,
    "priorityTier": 3
  },
  {
    "slug": "karunya-nagar",
    "name": "Karunya Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 242,
    "priorityTier": 3
  },
  {
    "slug": "karunya-university-area",
    "name": "Karunya University Area",
    "zone": "coimbatore-central",
    "sortOrder": 243,
    "priorityTier": 3
  },
  {
    "slug": "karuvalur-industrial-area",
    "name": "Karuvalur Industrial Area",
    "zone": "coimbatore-central",
    "sortOrder": 244,
    "priorityTier": 3
  },
  {
    "slug": "karuvalur-road",
    "name": "Karuvalur Road",
    "zone": "coimbatore-central",
    "sortOrder": 245,
    "priorityTier": 3
  },
  {
    "slug": "kasthuri-naicken-palayam",
    "name": "Kasthuri Naicken Palayam",
    "zone": "coimbatore-central",
    "sortOrder": 246,
    "priorityTier": 3
  },
  {
    "slug": "kattampatti",
    "name": "Kattampatti",
    "zone": "coimbatore-central",
    "sortOrder": 247,
    "priorityTier": 3
  },
  {
    "slug": "kattoor",
    "name": "Kattoor",
    "zone": "coimbatore-central",
    "sortOrder": 248,
    "priorityTier": 3
  },
  {
    "slug": "kaveri-nagar-coimbatore",
    "name": "Kaveri Nagar Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 249,
    "priorityTier": 3
  },
  {
    "slug": "kaveri-nagar-koundampalayam",
    "name": "Kaveri Nagar Koundampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 250,
    "priorityTier": 3
  },
  {
    "slug": "kavundampalayam",
    "name": "Kavundampalayam",
    "zone": "saibaba-colony",
    "sortOrder": 251,
    "priorityTier": 2
  },
  {
    "slug": "kavundampalayam-housing-unit",
    "name": "Kavundampalayam Housing Unit",
    "zone": "saibaba-colony",
    "sortOrder": 252,
    "priorityTier": 3
  },
  {
    "slug": "keeranatham",
    "name": "Keeranatham",
    "zone": "saravanampatti",
    "sortOrder": 253,
    "priorityTier": 2
  },
  {
    "slug": "keeranatham-it-park-area",
    "name": "Keeranatham It Park Area",
    "zone": "saravanampatti",
    "sortOrder": 254,
    "priorityTier": 3
  },
  {
    "slug": "kgisl-campus-area",
    "name": "KGISL Campus Area",
    "zone": "coimbatore-central",
    "sortOrder": 255,
    "priorityTier": 3
  },
  {
    "slug": "kinathukadavu",
    "name": "Kinathukadavu",
    "zone": "pollachi-belt",
    "sortOrder": 256,
    "priorityTier": 3
  },
  {
    "slug": "kinathukadavu-bus-stand-area",
    "name": "Kinathukadavu Bus Stand Area",
    "zone": "pollachi-belt",
    "sortOrder": 257,
    "priorityTier": 3
  },
  {
    "slug": "kng-pudur",
    "name": "Kng Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 258,
    "priorityTier": 3
  },
  {
    "slug": "kondayampalayam",
    "name": "Kondayampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 259,
    "priorityTier": 3
  },
  {
    "slug": "kothari-layout",
    "name": "Kothari Layout",
    "zone": "coimbatore-central",
    "sortOrder": 260,
    "priorityTier": 3
  },
  {
    "slug": "kothavadi",
    "name": "Kothavadi",
    "zone": "coimbatore-central",
    "sortOrder": 261,
    "priorityTier": 3
  },
  {
    "slug": "kottaimedu",
    "name": "Kottaimedu",
    "zone": "coimbatore-central",
    "sortOrder": 262,
    "priorityTier": 3
  },
  {
    "slug": "kottur",
    "name": "Kottur",
    "zone": "coimbatore-central",
    "sortOrder": 263,
    "priorityTier": 3
  },
  {
    "slug": "kottur-malaiyandipattinam",
    "name": "Kottur Malaiyandipattinam",
    "zone": "coimbatore-central",
    "sortOrder": 264,
    "priorityTier": 3
  },
  {
    "slug": "koundampalayam-junction",
    "name": "Koundampalayam Junction",
    "zone": "coimbatore-central",
    "sortOrder": 265,
    "priorityTier": 3
  },
  {
    "slug": "kovai-pudur-main-road",
    "name": "Kovai Pudur Main Road",
    "zone": "coimbatore-central",
    "sortOrder": 266,
    "priorityTier": 3
  },
  {
    "slug": "kovaipudur",
    "name": "Kovaipudur",
    "zone": "coimbatore-central",
    "sortOrder": 267,
    "priorityTier": 1
  },
  {
    "slug": "kovaipudur-pirivu",
    "name": "Kovaipudur Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 268,
    "priorityTier": 3
  },
  {
    "slug": "kovilmedu",
    "name": "Kovilmedu",
    "zone": "coimbatore-central",
    "sortOrder": 269,
    "priorityTier": 3
  },
  {
    "slug": "kovilpalayam",
    "name": "Kovilpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 270,
    "priorityTier": 3
  },
  {
    "slug": "kovilpalayam-road",
    "name": "Kovilpalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 271,
    "priorityTier": 3
  },
  {
    "slug": "krishnarayapuram",
    "name": "Krishnarayapuram",
    "zone": "coimbatore-central",
    "sortOrder": 272,
    "priorityTier": 3
  },
  {
    "slug": "krishnasamy-nagar",
    "name": "Krishnasamy Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 273,
    "priorityTier": 3
  },
  {
    "slug": "kumaraguru-college-area",
    "name": "Kumaraguru College Area",
    "zone": "coimbatore-central",
    "sortOrder": 274,
    "priorityTier": 3
  },
  {
    "slug": "kumaran-nagar-saravanampatti",
    "name": "Kumaran Nagar Saravanampatti",
    "zone": "saravanampatti",
    "sortOrder": 275,
    "priorityTier": 3
  },
  {
    "slug": "kumarapalayam-perur",
    "name": "Kumarapalayam Perur",
    "zone": "coimbatore-central",
    "sortOrder": 276,
    "priorityTier": 3
  },
  {
    "slug": "kumarasamy-colony",
    "name": "Kumarasamy Colony",
    "zone": "coimbatore-central",
    "sortOrder": 277,
    "priorityTier": 3
  },
  {
    "slug": "kuniyamuthur",
    "name": "Kuniyamuthur",
    "zone": "kurichi-industrial",
    "sortOrder": 278,
    "priorityTier": 1
  },
  {
    "slug": "kuniyamuthur-bus-stand-area",
    "name": "Kuniyamuthur Bus Stand Area",
    "zone": "kurichi-industrial",
    "sortOrder": 279,
    "priorityTier": 3
  },
  {
    "slug": "kunnathur-coimbatore",
    "name": "Kunnathur Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 280,
    "priorityTier": 3
  },
  {
    "slug": "kuppakonam-pudur",
    "name": "Kuppakonam Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 281,
    "priorityTier": 3
  },
  {
    "slug": "kuppakonam-pudur-extension",
    "name": "Kuppakonam Pudur Extension",
    "zone": "coimbatore-central",
    "sortOrder": 282,
    "priorityTier": 3
  },
  {
    "slug": "kuppepalayam",
    "name": "Kuppepalayam",
    "zone": "coimbatore-central",
    "sortOrder": 283,
    "priorityTier": 3
  },
  {
    "slug": "kurichi",
    "name": "Kurichi",
    "zone": "kurichi-industrial",
    "sortOrder": 284,
    "priorityTier": 1
  },
  {
    "slug": "kurichi-housing-unit",
    "name": "Kurichi Housing Unit",
    "zone": "kurichi-industrial",
    "sortOrder": 285,
    "priorityTier": 3
  },
  {
    "slug": "kurichi-industrial-estate",
    "name": "Kurichi Industrial Estate",
    "zone": "kurichi-industrial",
    "sortOrder": 286,
    "priorityTier": 3
  },
  {
    "slug": "kurichi-pirivu",
    "name": "Kurichi Pirivu",
    "zone": "kurichi-industrial",
    "sortOrder": 287,
    "priorityTier": 3
  },
  {
    "slug": "kurumbapalayam",
    "name": "Kurumbapalayam",
    "zone": "coimbatore-central",
    "sortOrder": 288,
    "priorityTier": 3
  },
  {
    "slug": "lakshmi-mills",
    "name": "Lakshmi Mills",
    "zone": "peelamedu-it",
    "sortOrder": 289,
    "priorityTier": 3
  },
  {
    "slug": "lakshmi-mills-junction",
    "name": "Lakshmi Mills Junction",
    "zone": "coimbatore-central",
    "sortOrder": 290,
    "priorityTier": 3
  },
  {
    "slug": "lakshmi-nagar",
    "name": "Lakshmi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 291,
    "priorityTier": 3
  },
  {
    "slug": "lakshmi-nagar-ganapathy",
    "name": "Lakshmi Nagar Ganapathy",
    "zone": "coimbatore-central",
    "sortOrder": 292,
    "priorityTier": 3
  },
  {
    "slug": "lakshmi-puram",
    "name": "Lakshmi Puram",
    "zone": "coimbatore-central",
    "sortOrder": 293,
    "priorityTier": 3
  },
  {
    "slug": "lakshmipuram-ganapathy",
    "name": "Lakshmipuram Ganapathy",
    "zone": "coimbatore-central",
    "sortOrder": 294,
    "priorityTier": 3
  },
  {
    "slug": "lanka-corner",
    "name": "Lanka Corner",
    "zone": "coimbatore-central",
    "sortOrder": 295,
    "priorityTier": 3
  },
  {
    "slug": "light-house-road",
    "name": "Light House Road",
    "zone": "coimbatore-central",
    "sortOrder": 296,
    "priorityTier": 3
  },
  {
    "slug": "madampatti",
    "name": "Madampatti",
    "zone": "coimbatore-central",
    "sortOrder": 297,
    "priorityTier": 3
  },
  {
    "slug": "madhampatti",
    "name": "Madhampatti",
    "zone": "coimbatore-central",
    "sortOrder": 298,
    "priorityTier": 3
  },
  {
    "slug": "madhampatti-junction",
    "name": "Madhampatti Junction",
    "zone": "coimbatore-central",
    "sortOrder": 299,
    "priorityTier": 3
  },
  {
    "slug": "madhampatti-road",
    "name": "Madhampatti Road",
    "zone": "coimbatore-central",
    "sortOrder": 300,
    "priorityTier": 3
  },
  {
    "slug": "madukkarai",
    "name": "Madukkarai",
    "zone": "pollachi-belt",
    "sortOrder": 301,
    "priorityTier": 3
  },
  {
    "slug": "madukkarai-market",
    "name": "Madukkarai Market",
    "zone": "pollachi-belt",
    "sortOrder": 302,
    "priorityTier": 3
  },
  {
    "slug": "madukkarai-municipality",
    "name": "Madukkarai Municipality",
    "zone": "pollachi-belt",
    "sortOrder": 303,
    "priorityTier": 3
  },
  {
    "slug": "madukkarai-railway-station-area",
    "name": "Madukkarai Railway Station Area",
    "zone": "pollachi-belt",
    "sortOrder": 304,
    "priorityTier": 3
  },
  {
    "slug": "makkinampatti",
    "name": "Makkinampatti",
    "zone": "coimbatore-central",
    "sortOrder": 305,
    "priorityTier": 3
  },
  {
    "slug": "malumichampatti",
    "name": "Malumichampatti",
    "zone": "coimbatore-central",
    "sortOrder": 306,
    "priorityTier": 3
  },
  {
    "slug": "malumichampatti-industrial-estate",
    "name": "Malumichampatti Industrial Estate",
    "zone": "coimbatore-central",
    "sortOrder": 307,
    "priorityTier": 3
  },
  {
    "slug": "malumichampatti-junction",
    "name": "Malumichampatti Junction",
    "zone": "coimbatore-central",
    "sortOrder": 308,
    "priorityTier": 3
  },
  {
    "slug": "manis-nagar",
    "name": "Manis Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 309,
    "priorityTier": 3
  },
  {
    "slug": "maniyakarampalayam",
    "name": "Maniyakarampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 310,
    "priorityTier": 3
  },
  {
    "slug": "marapalam",
    "name": "Marapalam",
    "zone": "coimbatore-central",
    "sortOrder": 311,
    "priorityTier": 3
  },
  {
    "slug": "marchanaickenpalayam",
    "name": "Marchanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 312,
    "priorityTier": 3
  },
  {
    "slug": "marudamalai",
    "name": "Marudamalai",
    "zone": "coimbatore-central",
    "sortOrder": 313,
    "priorityTier": 3
  },
  {
    "slug": "marudamalai-road",
    "name": "Marudamalai Road",
    "zone": "coimbatore-central",
    "sortOrder": 314,
    "priorityTier": 3
  },
  {
    "slug": "marudhamalai-main-road",
    "name": "Marudhamalai Main Road",
    "zone": "coimbatore-central",
    "sortOrder": 315,
    "priorityTier": 3
  },
  {
    "slug": "marudur-karamadai",
    "name": "Marudur Karamadai",
    "zone": "mettupalayam-belt",
    "sortOrder": 316,
    "priorityTier": 3
  },
  {
    "slug": "maruthi-nagar",
    "name": "Maruthi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 317,
    "priorityTier": 3
  },
  {
    "slug": "masagoundenchettipalayam",
    "name": "Masagoundenchettipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 318,
    "priorityTier": 3
  },
  {
    "slug": "masakalipalayam",
    "name": "Masakalipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 319,
    "priorityTier": 3
  },
  {
    "slug": "masakalipalayam-road",
    "name": "Masakalipalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 320,
    "priorityTier": 3
  },
  {
    "slug": "mathampalayam-thondamuthur",
    "name": "Mathampalayam Thondamuthur",
    "zone": "coimbatore-central",
    "sortOrder": 321,
    "priorityTier": 3
  },
  {
    "slug": "mavuthampathi",
    "name": "Mavuthampathi",
    "zone": "coimbatore-central",
    "sortOrder": 322,
    "priorityTier": 3
  },
  {
    "slug": "meena-estate",
    "name": "Meena Estate",
    "zone": "coimbatore-central",
    "sortOrder": 323,
    "priorityTier": 3
  },
  {
    "slug": "mettubavi",
    "name": "Mettubavi",
    "zone": "coimbatore-central",
    "sortOrder": 324,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam",
    "name": "Mettupalayam",
    "zone": "mettupalayam-belt",
    "sortOrder": 325,
    "priorityTier": 1
  },
  {
    "slug": "mettupalayam-bus-stand-area",
    "name": "Mettupalayam Bus Stand Area",
    "zone": "mettupalayam-belt",
    "sortOrder": 326,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam-main-road",
    "name": "Mettupalayam Main Road",
    "zone": "mettupalayam-belt",
    "sortOrder": 327,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam-ooty-road",
    "name": "Mettupalayam Ooty Road",
    "zone": "mettupalayam-belt",
    "sortOrder": 328,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam-railway-station-area",
    "name": "Mettupalayam Railway Station Area",
    "zone": "mettupalayam-belt",
    "sortOrder": 329,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam-road",
    "name": "Mettupalayam Road",
    "zone": "mettupalayam-belt",
    "sortOrder": 330,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam-road-gn-mills",
    "name": "Mettupalayam Road G.N. Mills",
    "zone": "mettupalayam-belt",
    "sortOrder": 331,
    "priorityTier": 3
  },
  {
    "slug": "mettupalayam-road-jothipuram",
    "name": "Mettupalayam Road Jothipuram",
    "zone": "mettupalayam-belt",
    "sortOrder": 332,
    "priorityTier": 3
  },
  {
    "slug": "mookambigai-nagar",
    "name": "Mookambigai Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 333,
    "priorityTier": 3
  },
  {
    "slug": "mopperipalayam",
    "name": "Mopperipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 334,
    "priorityTier": 3
  },
  {
    "slug": "mullai-nagar",
    "name": "Mullai Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 335,
    "priorityTier": 3
  },
  {
    "slug": "mullai-nagar-vadavalli",
    "name": "Mullai Nagar Vadavalli",
    "zone": "saibaba-colony",
    "sortOrder": 336,
    "priorityTier": 3
  },
  {
    "slug": "mullupadi",
    "name": "Mullupadi",
    "zone": "coimbatore-central",
    "sortOrder": 337,
    "priorityTier": 3
  },
  {
    "slug": "muthugoundenpudur",
    "name": "Muthugoundenpudur",
    "zone": "coimbatore-central",
    "sortOrder": 338,
    "priorityTier": 3
  },
  {
    "slug": "myleripalayam",
    "name": "Myleripalayam",
    "zone": "coimbatore-central",
    "sortOrder": 339,
    "priorityTier": 3
  },
  {
    "slug": "nsr-road",
    "name": "N.s.r. Road",
    "zone": "coimbatore-central",
    "sortOrder": 340,
    "priorityTier": 3
  },
  {
    "slug": "naickenpalayam",
    "name": "Naickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 341,
    "priorityTier": 3
  },
  {
    "slug": "nallampalayam",
    "name": "Nallampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 342,
    "priorityTier": 3
  },
  {
    "slug": "nallampalayam-road",
    "name": "Nallampalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 343,
    "priorityTier": 3
  },
  {
    "slug": "nallur-pollachi",
    "name": "Nallur Pollachi",
    "zone": "pollachi-belt",
    "sortOrder": 344,
    "priorityTier": 3
  },
  {
    "slug": "nanjappa-nagar",
    "name": "Nanjappa Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 345,
    "priorityTier": 3
  },
  {
    "slug": "nanjappa-road",
    "name": "Nanjappa Road",
    "zone": "coimbatore-central",
    "sortOrder": 346,
    "priorityTier": 3
  },
  {
    "slug": "nanjundapuram",
    "name": "Nanjundapuram",
    "zone": "coimbatore-central",
    "sortOrder": 347,
    "priorityTier": 3
  },
  {
    "slug": "nanjundapuram-main-road",
    "name": "Nanjundapuram Main Road",
    "zone": "coimbatore-central",
    "sortOrder": 348,
    "priorityTier": 3
  },
  {
    "slug": "nanjundapuram-road",
    "name": "Nanjundapuram Road",
    "zone": "coimbatore-central",
    "sortOrder": 349,
    "priorityTier": 3
  },
  {
    "slug": "nanjundapuram-village",
    "name": "Nanjundapuram Village",
    "zone": "coimbatore-central",
    "sortOrder": 350,
    "priorityTier": 3
  },
  {
    "slug": "narasimhanaickenpalayam",
    "name": "Narasimhanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 351,
    "priorityTier": 3
  },
  {
    "slug": "narasimhanaickenpalayam-junction",
    "name": "Narasimhanaickenpalayam Junction",
    "zone": "coimbatore-central",
    "sortOrder": 352,
    "priorityTier": 3
  },
  {
    "slug": "narasimhanaickenpalayam-road",
    "name": "Narasimhanaickenpalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 353,
    "priorityTier": 3
  },
  {
    "slug": "narasipuram",
    "name": "Narasipuram",
    "zone": "coimbatore-central",
    "sortOrder": 354,
    "priorityTier": 3
  },
  {
    "slug": "natesa-gounder-layout",
    "name": "Natesa Gounder Layout",
    "zone": "coimbatore-central",
    "sortOrder": 355,
    "priorityTier": 3
  },
  {
    "slug": "nava-india",
    "name": "Nava India",
    "zone": "coimbatore-central",
    "sortOrder": 356,
    "priorityTier": 3
  },
  {
    "slug": "navakkarai",
    "name": "Navakkarai",
    "zone": "coimbatore-central",
    "sortOrder": 357,
    "priorityTier": 3
  },
  {
    "slug": "navavoor",
    "name": "Navavoor",
    "zone": "coimbatore-central",
    "sortOrder": 358,
    "priorityTier": 3
  },
  {
    "slug": "navavoor-pirivu",
    "name": "Navavoor Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 359,
    "priorityTier": 3
  },
  {
    "slug": "nawab-hakim-road",
    "name": "Nawab Hakim Road",
    "zone": "coimbatore-central",
    "sortOrder": 360,
    "priorityTier": 3
  },
  {
    "slug": "neelambur",
    "name": "Neelambur",
    "zone": "coimbatore-central",
    "sortOrder": 361,
    "priorityTier": 3
  },
  {
    "slug": "neelambur-bypass",
    "name": "Neelambur Bypass",
    "zone": "coimbatore-central",
    "sortOrder": 362,
    "priorityTier": 3
  },
  {
    "slug": "neelambur-industrial-area",
    "name": "Neelambur Industrial Area",
    "zone": "coimbatore-central",
    "sortOrder": 363,
    "priorityTier": 3
  },
  {
    "slug": "neelambur-toll-area",
    "name": "Neelambur Toll Area",
    "zone": "coimbatore-central",
    "sortOrder": 364,
    "priorityTier": 3
  },
  {
    "slug": "negamam",
    "name": "Negamam",
    "zone": "coimbatore-central",
    "sortOrder": 365,
    "priorityTier": 3
  },
  {
    "slug": "nehru-nagar-east",
    "name": "Nehru Nagar East",
    "zone": "coimbatore-central",
    "sortOrder": 366,
    "priorityTier": 3
  },
  {
    "slug": "nehru-nagar-kalapatti",
    "name": "Nehru Nagar Kalapatti",
    "zone": "coimbatore-central",
    "sortOrder": 367,
    "priorityTier": 3
  },
  {
    "slug": "nehru-nagar-west",
    "name": "Nehru Nagar West",
    "zone": "coimbatore-central",
    "sortOrder": 368,
    "priorityTier": 3
  },
  {
    "slug": "nesavaalar-colony",
    "name": "Nesavaalar Colony",
    "zone": "coimbatore-central",
    "sortOrder": 369,
    "priorityTier": 3
  },
  {
    "slug": "nethaji-nagar",
    "name": "Nethaji Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 370,
    "priorityTier": 3
  },
  {
    "slug": "new-dhamu-nagar",
    "name": "New Dhamu Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 371,
    "priorityTier": 3
  },
  {
    "slug": "new-siddhapudur",
    "name": "New Siddhapudur",
    "zone": "coimbatore-central",
    "sortOrder": 372,
    "priorityTier": 3
  },
  {
    "slug": "nggo-colony",
    "name": "Nggo Colony",
    "zone": "coimbatore-central",
    "sortOrder": 373,
    "priorityTier": 3
  },
  {
    "slug": "ngr-colony",
    "name": "NGR Colony",
    "zone": "coimbatore-central",
    "sortOrder": 374,
    "priorityTier": 3
  },
  {
    "slug": "nkr-nagar",
    "name": "NKR Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 375,
    "priorityTier": 3
  },
  {
    "slug": "no4-veerapandi",
    "name": "No.4 Veerapandi",
    "zone": "coimbatore-central",
    "sortOrder": 376,
    "priorityTier": 3
  },
  {
    "slug": "nri-gardens",
    "name": "NRI Gardens",
    "zone": "coimbatore-central",
    "sortOrder": 377,
    "priorityTier": 3
  },
  {
    "slug": "odaiyakulam",
    "name": "Odayakulam",
    "zone": "coimbatore-central",
    "sortOrder": 378,
    "priorityTier": 3
  },
  {
    "slug": "om-sakthi-nagar",
    "name": "Om Sakthi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 379,
    "priorityTier": 3
  },
  {
    "slug": "ondipudur",
    "name": "Ondipudur",
    "zone": "singanallur",
    "sortOrder": 380,
    "priorityTier": 2
  },
  {
    "slug": "ondipudur-bus-stand-area",
    "name": "Ondipudur Bus Stand Area",
    "zone": "singanallur",
    "sortOrder": 381,
    "priorityTier": 3
  },
  {
    "slug": "oppanakara-street",
    "name": "Oppanakara Street",
    "zone": "coimbatore-central",
    "sortOrder": 382,
    "priorityTier": 3
  },
  {
    "slug": "othakkalmandapam",
    "name": "Othakkalmandapam",
    "zone": "coimbatore-central",
    "sortOrder": 383,
    "priorityTier": 3
  },
  {
    "slug": "othakkalmandapam-junction",
    "name": "Othakkalmandapam Junction",
    "zone": "coimbatore-central",
    "sortOrder": 384,
    "priorityTier": 3
  },
  {
    "slug": "p-and-t-colony",
    "name": "P And T Colony",
    "zone": "coimbatore-central",
    "sortOrder": 385,
    "priorityTier": 3
  },
  {
    "slug": "pn-palayam",
    "name": "P.N. Palayam",
    "zone": "coimbatore-central",
    "sortOrder": 386,
    "priorityTier": 3
  },
  {
    "slug": "pn-pudur",
    "name": "P.N. Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 387,
    "priorityTier": 3
  },
  {
    "slug": "palakkad-main-road",
    "name": "Palakkad Main Road",
    "zone": "coimbatore-central",
    "sortOrder": 388,
    "priorityTier": 3
  },
  {
    "slug": "palakkad-road-coimbatore",
    "name": "Palakkad Road Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 389,
    "priorityTier": 3
  },
  {
    "slug": "palanigoundenpudur",
    "name": "Palanigoundenpudur",
    "zone": "coimbatore-central",
    "sortOrder": 390,
    "priorityTier": 3
  },
  {
    "slug": "pallapalayam-sulur",
    "name": "Pallapalayam Sulur",
    "zone": "kurichi-industrial",
    "sortOrder": 391,
    "priorityTier": 3
  },
  {
    "slug": "pannimadai-road",
    "name": "Pannimadai Road",
    "zone": "coimbatore-central",
    "sortOrder": 392,
    "priorityTier": 3
  },
  {
    "slug": "papampatti",
    "name": "Papampatti",
    "zone": "coimbatore-central",
    "sortOrder": 393,
    "priorityTier": 3
  },
  {
    "slug": "papanaickenpalayam",
    "name": "Papanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 394,
    "priorityTier": 3
  },
  {
    "slug": "pappanaickenpalayam",
    "name": "Pappanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 395,
    "priorityTier": 3
  },
  {
    "slug": "pappanaickenpudur",
    "name": "Pappanaickenpudur",
    "zone": "coimbatore-central",
    "sortOrder": 396,
    "priorityTier": 3
  },
  {
    "slug": "park-town-coimbatore",
    "name": "Park Town Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 397,
    "priorityTier": 3
  },
  {
    "slug": "pasur-coimbatore",
    "name": "Pasur Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 398,
    "priorityTier": 3
  },
  {
    "slug": "pattanam-road",
    "name": "Pattanam Road",
    "zone": "coimbatore-central",
    "sortOrder": 399,
    "priorityTier": 3
  },
  {
    "slug": "peelamedu",
    "name": "Peelamedu",
    "zone": "peelamedu-it",
    "sortOrder": 400,
    "priorityTier": 1
  },
  {
    "slug": "peelamedu-pudur",
    "name": "Peelamedu Pudur",
    "zone": "peelamedu-it",
    "sortOrder": 401,
    "priorityTier": 1
  },
  {
    "slug": "periya-negamam",
    "name": "Periya Negamam",
    "zone": "coimbatore-central",
    "sortOrder": 402,
    "priorityTier": 3
  },
  {
    "slug": "periyanaickenpalayam",
    "name": "Periyanaickenpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 403,
    "priorityTier": 3
  },
  {
    "slug": "periyanaickenpalayam-junction",
    "name": "Periyanaickenpalayam Junction",
    "zone": "coimbatore-central",
    "sortOrder": 404,
    "priorityTier": 3
  },
  {
    "slug": "perur",
    "name": "Perur",
    "zone": "coimbatore-central",
    "sortOrder": 405,
    "priorityTier": 3
  },
  {
    "slug": "perur-chettipalayam",
    "name": "Perur Chettipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 406,
    "priorityTier": 3
  },
  {
    "slug": "perur-chettipalayam-road",
    "name": "Perur Chettipalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 407,
    "priorityTier": 3
  },
  {
    "slug": "perur-main-road",
    "name": "Perur Main Road",
    "zone": "coimbatore-central",
    "sortOrder": 408,
    "priorityTier": 3
  },
  {
    "slug": "perur-main-road-coimbatore",
    "name": "Perur Main Road Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 409,
    "priorityTier": 3
  },
  {
    "slug": "perur-pachapalayam",
    "name": "Perur Pachapalayam",
    "zone": "coimbatore-central",
    "sortOrder": 410,
    "priorityTier": 3
  },
  {
    "slug": "pichanur",
    "name": "Pichanur",
    "zone": "coimbatore-central",
    "sortOrder": 411,
    "priorityTier": 3
  },
  {
    "slug": "pichanur-village",
    "name": "Pichanur Village",
    "zone": "coimbatore-central",
    "sortOrder": 412,
    "priorityTier": 3
  },
  {
    "slug": "pillur",
    "name": "Pillur",
    "zone": "coimbatore-central",
    "sortOrder": 413,
    "priorityTier": 3
  },
  {
    "slug": "pioneer-mills",
    "name": "Pioneer Mills",
    "zone": "coimbatore-central",
    "sortOrder": 414,
    "priorityTier": 3
  },
  {
    "slug": "pioneer-nagar",
    "name": "Pioneer Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 415,
    "priorityTier": 3
  },
  {
    "slug": "podanur",
    "name": "Podanur",
    "zone": "coimbatore-central",
    "sortOrder": 416,
    "priorityTier": 1
  },
  {
    "slug": "podanur-junction",
    "name": "Podanur Junction",
    "zone": "coimbatore-central",
    "sortOrder": 417,
    "priorityTier": 3
  },
  {
    "slug": "podanur-railway-station-area",
    "name": "Podanur Railway Station Area",
    "zone": "coimbatore-central",
    "sortOrder": 418,
    "priorityTier": 3
  },
  {
    "slug": "pogalur",
    "name": "Pogalur",
    "zone": "coimbatore-central",
    "sortOrder": 419,
    "priorityTier": 3
  },
  {
    "slug": "pollachi",
    "name": "Pollachi",
    "zone": "pollachi-belt",
    "sortOrder": 420,
    "priorityTier": 1
  },
  {
    "slug": "pollachi-coimbatore-road",
    "name": "Pollachi Coimbatore Road",
    "zone": "pollachi-belt",
    "sortOrder": 421,
    "priorityTier": 3
  },
  {
    "slug": "pollachi-main-road",
    "name": "Pollachi Main Road",
    "zone": "pollachi-belt",
    "sortOrder": 422,
    "priorityTier": 3
  },
  {
    "slug": "pollachi-market-area",
    "name": "Pollachi Market Area",
    "zone": "pollachi-belt",
    "sortOrder": 423,
    "priorityTier": 3
  },
  {
    "slug": "pollachi-new-bus-stand-area",
    "name": "Pollachi New Bus Stand Area",
    "zone": "pollachi-belt",
    "sortOrder": 424,
    "priorityTier": 3
  },
  {
    "slug": "pollachi-old-bus-stand-area",
    "name": "Pollachi Old Bus Stand Area",
    "zone": "pollachi-belt",
    "sortOrder": 425,
    "priorityTier": 3
  },
  {
    "slug": "pollachi-road-coimbatore",
    "name": "Pollachi Road Coimbatore",
    "zone": "pollachi-belt",
    "sortOrder": 426,
    "priorityTier": 3
  },
  {
    "slug": "pongalur-annur",
    "name": "Pongalur Annur",
    "zone": "mettupalayam-belt",
    "sortOrder": 427,
    "priorityTier": 3
  },
  {
    "slug": "ponniarajapuram",
    "name": "Ponniarajapuram",
    "zone": "coimbatore-central",
    "sortOrder": 428,
    "priorityTier": 3
  },
  {
    "slug": "pooluvapatti",
    "name": "Pooluvapatti",
    "zone": "coimbatore-central",
    "sortOrder": 429,
    "priorityTier": 3
  },
  {
    "slug": "poomarket",
    "name": "Poomarket",
    "zone": "coimbatore-central",
    "sortOrder": 430,
    "priorityTier": 3
  },
  {
    "slug": "pottayandiporambu",
    "name": "Pottayandiporambu",
    "zone": "coimbatore-central",
    "sortOrder": 431,
    "priorityTier": 3
  },
  {
    "slug": "premier-mills-area",
    "name": "Premier Mills Area",
    "zone": "coimbatore-central",
    "sortOrder": 432,
    "priorityTier": 3
  },
  {
    "slug": "press-colony",
    "name": "Press Colony",
    "zone": "coimbatore-central",
    "sortOrder": 433,
    "priorityTier": 3
  },
  {
    "slug": "psg-hospitals-area",
    "name": "PSG Hospitals Area",
    "zone": "coimbatore-central",
    "sortOrder": 434,
    "priorityTier": 3
  },
  {
    "slug": "psg-tech-area",
    "name": "PSG Tech Area",
    "zone": "coimbatore-central",
    "sortOrder": 435,
    "priorityTier": 2
  },
  {
    "slug": "puliakulam-road",
    "name": "Puliakulam Road",
    "zone": "coimbatore-central",
    "sortOrder": 436,
    "priorityTier": 3
  },
  {
    "slug": "puliampatti-road",
    "name": "Puliampatti Road",
    "zone": "coimbatore-central",
    "sortOrder": 437,
    "priorityTier": 3
  },
  {
    "slug": "puliyakulam",
    "name": "Puliyakulam",
    "zone": "coimbatore-central",
    "sortOrder": 438,
    "priorityTier": 3
  },
  {
    "slug": "rg-pudur",
    "name": "R.g. Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 439,
    "priorityTier": 3
  },
  {
    "slug": "rs-puram",
    "name": "R.S. Puram",
    "zone": "coimbatore-central",
    "sortOrder": 440,
    "priorityTier": 1
  },
  {
    "slug": "race-course",
    "name": "Race Course",
    "zone": "coimbatore-central",
    "sortOrder": 441,
    "priorityTier": 1
  },
  {
    "slug": "rajiv-gandhi-nagar",
    "name": "Rajiv Gandhi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 442,
    "priorityTier": 3
  },
  {
    "slug": "rajiv-gandhi-nagar-thudiyalur",
    "name": "Rajiv Gandhi Nagar Thudiyalur",
    "zone": "coimbatore-central",
    "sortOrder": 443,
    "priorityTier": 3
  },
  {
    "slug": "raju-naidu-street",
    "name": "Raju Naidu Street",
    "zone": "coimbatore-central",
    "sortOrder": 444,
    "priorityTier": 3
  },
  {
    "slug": "ram-nagar",
    "name": "Ram Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 445,
    "priorityTier": 3
  },
  {
    "slug": "ramakrishna-hospital-area",
    "name": "Ramakrishna Hospital Area",
    "zone": "coimbatore-central",
    "sortOrder": 446,
    "priorityTier": 3
  },
  {
    "slug": "ramakrishna-nagar",
    "name": "Ramakrishna Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 447,
    "priorityTier": 3
  },
  {
    "slug": "ramakrishnapuram",
    "name": "Ramakrishnapuram",
    "zone": "coimbatore-central",
    "sortOrder": 448,
    "priorityTier": 3
  },
  {
    "slug": "ramalingam-colony",
    "name": "Ramalingam Colony",
    "zone": "coimbatore-central",
    "sortOrder": 449,
    "priorityTier": 3
  },
  {
    "slug": "ramanamudalipudur",
    "name": "Ramanamudalipudur",
    "zone": "coimbatore-central",
    "sortOrder": 450,
    "priorityTier": 3
  },
  {
    "slug": "ramanathapuram",
    "name": "Ramanathapuram",
    "zone": "coimbatore-central",
    "sortOrder": 451,
    "priorityTier": 1
  },
  {
    "slug": "ramanathapuram-signal-area",
    "name": "Ramanathapuram Signal Area",
    "zone": "coimbatore-central",
    "sortOrder": 452,
    "priorityTier": 3
  },
  {
    "slug": "ramasamy-nagar",
    "name": "Ramasamy Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 453,
    "priorityTier": 3
  },
  {
    "slug": "ranga-konar-street",
    "name": "Ranga Konar Street",
    "zone": "coimbatore-central",
    "sortOrder": 454,
    "priorityTier": 3
  },
  {
    "slug": "rangasamy-gounden-pudur",
    "name": "Rangasamy Gounden Pudur",
    "zone": "coimbatore-central",
    "sortOrder": 455,
    "priorityTier": 3
  },
  {
    "slug": "rasipalayam",
    "name": "Rasipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 456,
    "priorityTier": 3
  },
  {
    "slug": "rathina-sabapathi-puram",
    "name": "Rathina Sabapathi Puram",
    "zone": "coimbatore-central",
    "sortOrder": 457,
    "priorityTier": 3
  },
  {
    "slug": "rathinam-techzone-area",
    "name": "Rathinam Techzone Area",
    "zone": "coimbatore-central",
    "sortOrder": 458,
    "priorityTier": 3
  },
  {
    "slug": "rathinapuri",
    "name": "Rathinapuri",
    "zone": "coimbatore-central",
    "sortOrder": 459,
    "priorityTier": 3
  },
  {
    "slug": "rathinapuri-extension",
    "name": "Rathinapuri Extension",
    "zone": "coimbatore-central",
    "sortOrder": 460,
    "priorityTier": 3
  },
  {
    "slug": "ravathur",
    "name": "Ravathur",
    "zone": "coimbatore-central",
    "sortOrder": 461,
    "priorityTier": 3
  },
  {
    "slug": "ravathur-pirivu",
    "name": "Ravathur Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 462,
    "priorityTier": 3
  },
  {
    "slug": "renga-nagar",
    "name": "Renga Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 463,
    "priorityTier": 3
  },
  {
    "slug": "ruby-matriculation-area",
    "name": "Ruby Matriculation Area",
    "zone": "coimbatore-central",
    "sortOrder": 464,
    "priorityTier": 3
  },
  {
    "slug": "rukmani-nagar",
    "name": "Rukmani Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 465,
    "priorityTier": 3
  },
  {
    "slug": "saibaba-colony",
    "name": "Saibaba Colony",
    "zone": "saibaba-colony",
    "sortOrder": 466,
    "priorityTier": 1
  },
  {
    "slug": "saibaba-mission-area",
    "name": "Saibaba Mission Area",
    "zone": "saibaba-colony",
    "sortOrder": 467,
    "priorityTier": 3
  },
  {
    "slug": "sakthi-estate",
    "name": "Sakthi Estate",
    "zone": "coimbatore-central",
    "sortOrder": 468,
    "priorityTier": 3
  },
  {
    "slug": "sakthi-nagar",
    "name": "Sakthi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 469,
    "priorityTier": 3
  },
  {
    "slug": "sakthi-road",
    "name": "Sakthi Road",
    "zone": "coimbatore-central",
    "sortOrder": 470,
    "priorityTier": 3
  },
  {
    "slug": "samathur",
    "name": "Samathur",
    "zone": "coimbatore-central",
    "sortOrder": 471,
    "priorityTier": 3
  },
  {
    "slug": "samathuvapuram-coimbatore",
    "name": "Samathuvapuram Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 472,
    "priorityTier": 3
  },
  {
    "slug": "samichettipalayam",
    "name": "Samichettipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 473,
    "priorityTier": 3
  },
  {
    "slug": "sanganoor",
    "name": "Sanganoor",
    "zone": "coimbatore-central",
    "sortOrder": 474,
    "priorityTier": 3
  },
  {
    "slug": "sanganoor-main-road",
    "name": "Sanganoor Main Road",
    "zone": "coimbatore-central",
    "sortOrder": 475,
    "priorityTier": 3
  },
  {
    "slug": "saravanampatti",
    "name": "Saravanampatti",
    "zone": "saravanampatti",
    "sortOrder": 476,
    "priorityTier": 1
  },
  {
    "slug": "saravanampatti-junction",
    "name": "Saravanampatti Junction",
    "zone": "saravanampatti",
    "sortOrder": 477,
    "priorityTier": 3
  },
  {
    "slug": "saravanampatti-main-road",
    "name": "Saravanampatti Main Road",
    "zone": "saravanampatti",
    "sortOrder": 478,
    "priorityTier": 3
  },
  {
    "slug": "sarkar-samakulam",
    "name": "Sarkar Samakulam",
    "zone": "coimbatore-central",
    "sortOrder": 479,
    "priorityTier": 3
  },
  {
    "slug": "sastri-road",
    "name": "Sastri Road",
    "zone": "coimbatore-central",
    "sortOrder": 480,
    "priorityTier": 3
  },
  {
    "slug": "sathy-road",
    "name": "Sathy Road",
    "zone": "coimbatore-central",
    "sortOrder": 481,
    "priorityTier": 3
  },
  {
    "slug": "sathy-road-ganapathy",
    "name": "Sathy Road Ganapathy",
    "zone": "coimbatore-central",
    "sortOrder": 482,
    "priorityTier": 3
  },
  {
    "slug": "sathy-road-saravanampatti",
    "name": "Sathy Road Saravanampatti",
    "zone": "saravanampatti",
    "sortOrder": 483,
    "priorityTier": 3
  },
  {
    "slug": "sathyamangalam-road",
    "name": "Sathyamangalam Road",
    "zone": "coimbatore-central",
    "sortOrder": 484,
    "priorityTier": 3
  },
  {
    "slug": "sathyamangalam-road-saravanampatti",
    "name": "Sathyamangalam Road Saravanampatti",
    "zone": "saravanampatti",
    "sortOrder": 485,
    "priorityTier": 3
  },
  {
    "slug": "seerapalayam",
    "name": "Seerapalayam",
    "zone": "coimbatore-central",
    "sortOrder": 486,
    "priorityTier": 3
  },
  {
    "slug": "seerapalayam-pirivu",
    "name": "Seerapalayam Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 487,
    "priorityTier": 3
  },
  {
    "slug": "selvapuram",
    "name": "Selvapuram",
    "zone": "coimbatore-central",
    "sortOrder": 488,
    "priorityTier": 3
  },
  {
    "slug": "selvapuram-north",
    "name": "Selvapuram North",
    "zone": "coimbatore-central",
    "sortOrder": 489,
    "priorityTier": 3
  },
  {
    "slug": "selvapuram-south",
    "name": "Selvapuram South",
    "zone": "coimbatore-central",
    "sortOrder": 490,
    "priorityTier": 3
  },
  {
    "slug": "semmedu",
    "name": "Semmedu",
    "zone": "coimbatore-central",
    "sortOrder": 491,
    "priorityTier": 3
  },
  {
    "slug": "sengaliappa-nagar",
    "name": "Sengaliappa Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 492,
    "priorityTier": 3
  },
  {
    "slug": "sengalipalayam",
    "name": "Sengalipalayam",
    "zone": "coimbatore-central",
    "sortOrder": 493,
    "priorityTier": 3
  },
  {
    "slug": "sethumadai",
    "name": "Sethumadai",
    "zone": "coimbatore-central",
    "sortOrder": 494,
    "priorityTier": 3
  },
  {
    "slug": "shanmuga-nagar",
    "name": "Shanmuga Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 495,
    "priorityTier": 3
  },
  {
    "slug": "shanthi-social-services-area",
    "name": "Shanthi Social Services Area",
    "zone": "coimbatore-central",
    "sortOrder": 496,
    "priorityTier": 3
  },
  {
    "slug": "shivaram-nagar",
    "name": "Shivaram Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 497,
    "priorityTier": 3
  },
  {
    "slug": "sidco-kurichi",
    "name": "SIDCO Kurichi",
    "zone": "kurichi-industrial",
    "sortOrder": 498,
    "priorityTier": 3
  },
  {
    "slug": "siddhapudur",
    "name": "Siddhapudur",
    "zone": "coimbatore-central",
    "sortOrder": 499,
    "priorityTier": 3
  },
  {
    "slug": "sihs-colony",
    "name": "Sihs Colony",
    "zone": "coimbatore-central",
    "sortOrder": 500,
    "priorityTier": 3
  },
  {
    "slug": "singanallur",
    "name": "Singanallur",
    "zone": "singanallur",
    "sortOrder": 501,
    "priorityTier": 1
  },
  {
    "slug": "singanallur-bus-stand-area",
    "name": "Singanallur Bus Stand Area",
    "zone": "singanallur",
    "sortOrder": 502,
    "priorityTier": 3
  },
  {
    "slug": "sipcot-sulur-area",
    "name": "Sipcot Sulur Area",
    "zone": "kurichi-industrial",
    "sortOrder": 503,
    "priorityTier": 3
  },
  {
    "slug": "sirumugai",
    "name": "Sirumugai",
    "zone": "coimbatore-central",
    "sortOrder": 504,
    "priorityTier": 3
  },
  {
    "slug": "sirumugai-road",
    "name": "Sirumugai Road",
    "zone": "coimbatore-central",
    "sortOrder": 505,
    "priorityTier": 3
  },
  {
    "slug": "sitra",
    "name": "Sitra",
    "zone": "peelamedu-it",
    "sortOrder": 506,
    "priorityTier": 3
  },
  {
    "slug": "sitra-airport-road",
    "name": "Sitra Airport Road",
    "zone": "peelamedu-it",
    "sortOrder": 507,
    "priorityTier": 3
  },
  {
    "slug": "sivananda-colony",
    "name": "Sivananda Colony",
    "zone": "coimbatore-central",
    "sortOrder": 508,
    "priorityTier": 2
  },
  {
    "slug": "sivanandhapuram",
    "name": "Sivanandhapuram",
    "zone": "coimbatore-central",
    "sortOrder": 509,
    "priorityTier": 3
  },
  {
    "slug": "sivasakthi-colony",
    "name": "Sivasakthi Colony",
    "zone": "coimbatore-central",
    "sortOrder": 510,
    "priorityTier": 3
  },
  {
    "slug": "sivasamy-road",
    "name": "Sivasamy Road",
    "zone": "coimbatore-central",
    "sortOrder": 511,
    "priorityTier": 3
  },
  {
    "slug": "solavampalayam",
    "name": "Solavampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 512,
    "priorityTier": 3
  },
  {
    "slug": "somanur-industrial-area",
    "name": "Somanur Industrial Area",
    "zone": "coimbatore-central",
    "sortOrder": 513,
    "priorityTier": 3
  },
  {
    "slug": "somanur-road",
    "name": "Somanur Road",
    "zone": "coimbatore-central",
    "sortOrder": 514,
    "priorityTier": 3
  },
  {
    "slug": "somayampalayam",
    "name": "Somayampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 515,
    "priorityTier": 3
  },
  {
    "slug": "sowripalayam",
    "name": "Sowripalayam",
    "zone": "coimbatore-central",
    "sortOrder": 516,
    "priorityTier": 3
  },
  {
    "slug": "sowripalayam-main-road",
    "name": "Sowripalayam Main Road",
    "zone": "coimbatore-central",
    "sortOrder": 517,
    "priorityTier": 3
  },
  {
    "slug": "sowripalayam-pirivu",
    "name": "Sowripalayam Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 518,
    "priorityTier": 3
  },
  {
    "slug": "sowripalayam-road",
    "name": "Sowripalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 519,
    "priorityTier": 3
  },
  {
    "slug": "sri-ramakrishna-nagar",
    "name": "Sri Ramakrishna Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 520,
    "priorityTier": 3
  },
  {
    "slug": "sri-vari-gardens",
    "name": "Sri Vari Gardens",
    "zone": "coimbatore-central",
    "sortOrder": 521,
    "priorityTier": 3
  },
  {
    "slug": "sridevi-nagar",
    "name": "Sridevi Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 522,
    "priorityTier": 3
  },
  {
    "slug": "srinivasa-nagar",
    "name": "Srinivasa Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 523,
    "priorityTier": 3
  },
  {
    "slug": "srinivasa-nagar-uppilipalayam",
    "name": "Srinivasa Nagar Uppilipalayam",
    "zone": "singanallur",
    "sortOrder": 524,
    "priorityTier": 3
  },
  {
    "slug": "sriram-nagar",
    "name": "Sriram Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 525,
    "priorityTier": 3
  },
  {
    "slug": "subramaniampalayam",
    "name": "Subramaniampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 526,
    "priorityTier": 3
  },
  {
    "slug": "subramaniampalayam-road",
    "name": "Subramaniampalayam Road",
    "zone": "coimbatore-central",
    "sortOrder": 527,
    "priorityTier": 3
  },
  {
    "slug": "sukrawar-pettai",
    "name": "Sukrawar Pettai",
    "zone": "coimbatore-central",
    "sortOrder": 528,
    "priorityTier": 3
  },
  {
    "slug": "suleswaranpatti",
    "name": "Suleswaranpatti",
    "zone": "coimbatore-central",
    "sortOrder": 529,
    "priorityTier": 3
  },
  {
    "slug": "sulur",
    "name": "Sulur",
    "zone": "kurichi-industrial",
    "sortOrder": 530,
    "priorityTier": 2
  },
  {
    "slug": "sulur-air-force-area",
    "name": "Sulur Air Force Area",
    "zone": "kurichi-industrial",
    "sortOrder": 531,
    "priorityTier": 3
  },
  {
    "slug": "sulur-industrial-area",
    "name": "Sulur Industrial Area",
    "zone": "kurichi-industrial",
    "sortOrder": 532,
    "priorityTier": 3
  },
  {
    "slug": "sulur-railway-station-area",
    "name": "Sulur Railway Station Area",
    "zone": "kurichi-industrial",
    "sortOrder": 533,
    "priorityTier": 3
  },
  {
    "slug": "sundakkamuthur-road",
    "name": "Sundakkamuthur Road",
    "zone": "coimbatore-central",
    "sortOrder": 534,
    "priorityTier": 3
  },
  {
    "slug": "sundarapuram",
    "name": "Sundarapuram",
    "zone": "coimbatore-central",
    "sortOrder": 535,
    "priorityTier": 3
  },
  {
    "slug": "sundarapuram-junction",
    "name": "Sundarapuram Junction",
    "zone": "coimbatore-central",
    "sortOrder": 536,
    "priorityTier": 3
  },
  {
    "slug": "sungam",
    "name": "Sungam",
    "zone": "coimbatore-central",
    "sortOrder": 537,
    "priorityTier": 3
  },
  {
    "slug": "sungam-bypass",
    "name": "Sungam Bypass",
    "zone": "coimbatore-central",
    "sortOrder": 538,
    "priorityTier": 3
  },
  {
    "slug": "t-kottampatti",
    "name": "T. Kottampatti",
    "zone": "coimbatore-central",
    "sortOrder": 539,
    "priorityTier": 3
  },
  {
    "slug": "tvs-nagar",
    "name": "T.v.s. Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 540,
    "priorityTier": 3
  },
  {
    "slug": "tamil-nadu-agricultural-university-area",
    "name": "Tamil Nadu Agricultural University Area",
    "zone": "coimbatore-central",
    "sortOrder": 541,
    "priorityTier": 3
  },
  {
    "slug": "tatabad",
    "name": "Tatabad",
    "zone": "coimbatore-central",
    "sortOrder": 542,
    "priorityTier": 3
  },
  {
    "slug": "teachers-colony",
    "name": "Teachers Colony",
    "zone": "coimbatore-central",
    "sortOrder": 543,
    "priorityTier": 3
  },
  {
    "slug": "telungupalayam",
    "name": "Telungupalayam",
    "zone": "coimbatore-central",
    "sortOrder": 544,
    "priorityTier": 3
  },
  {
    "slug": "telungupalayam-pirivu",
    "name": "Telungupalayam Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 545,
    "priorityTier": 3
  },
  {
    "slug": "textool-feeder-road",
    "name": "Textool Feeder Road",
    "zone": "coimbatore-central",
    "sortOrder": 546,
    "priorityTier": 3
  },
  {
    "slug": "thaneerpandal",
    "name": "Thaneerpandal",
    "zone": "coimbatore-central",
    "sortOrder": 547,
    "priorityTier": 3
  },
  {
    "slug": "thaneerpandal-road",
    "name": "Thaneerpandal Road",
    "zone": "coimbatore-central",
    "sortOrder": 548,
    "priorityTier": 3
  },
  {
    "slug": "thanneerpandal-it-corridor",
    "name": "Thanneerpandal It Corridor",
    "zone": "coimbatore-central",
    "sortOrder": 549,
    "priorityTier": 3
  },
  {
    "slug": "thekkampatti",
    "name": "Thekkampatti",
    "zone": "coimbatore-central",
    "sortOrder": 550,
    "priorityTier": 3
  },
  {
    "slug": "thenkarai",
    "name": "Thenkarai",
    "zone": "coimbatore-central",
    "sortOrder": 551,
    "priorityTier": 3
  },
  {
    "slug": "thennampalayam",
    "name": "Thennampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 552,
    "priorityTier": 3
  },
  {
    "slug": "thirumalayampalayam",
    "name": "Thirumalayampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 553,
    "priorityTier": 3
  },
  {
    "slug": "thirumurugan-nagar",
    "name": "Thirumurugan Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 554,
    "priorityTier": 3
  },
  {
    "slug": "thiruvalluvar-nagar",
    "name": "Thiruvalluvar Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 555,
    "priorityTier": 3
  },
  {
    "slug": "thiruvannamalai-nagar",
    "name": "Thiruvannamalai Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 556,
    "priorityTier": 3
  },
  {
    "slug": "tholampalayam",
    "name": "Tholampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 557,
    "priorityTier": 3
  },
  {
    "slug": "thomas-street",
    "name": "Thomas Street",
    "zone": "coimbatore-central",
    "sortOrder": 558,
    "priorityTier": 3
  },
  {
    "slug": "thondamuthur",
    "name": "Thondamuthur",
    "zone": "coimbatore-central",
    "sortOrder": 559,
    "priorityTier": 3
  },
  {
    "slug": "thondamuthur-junction",
    "name": "Thondamuthur Junction",
    "zone": "coimbatore-central",
    "sortOrder": 560,
    "priorityTier": 3
  },
  {
    "slug": "thoppampatti",
    "name": "Thoppampatti",
    "zone": "coimbatore-central",
    "sortOrder": 561,
    "priorityTier": 3
  },
  {
    "slug": "thudiyalur",
    "name": "Thudiyalur",
    "zone": "saibaba-colony",
    "sortOrder": 562,
    "priorityTier": 1
  },
  {
    "slug": "thudiyalur-housing-unit",
    "name": "Thudiyalur Housing Unit",
    "zone": "coimbatore-central",
    "sortOrder": 563,
    "priorityTier": 3
  },
  {
    "slug": "thudiyalur-junction",
    "name": "Thudiyalur Junction",
    "zone": "coimbatore-central",
    "sortOrder": 564,
    "priorityTier": 3
  },
  {
    "slug": "tidel-park-coimbatore-area",
    "name": "Tidel Park Coimbatore Area",
    "zone": "coimbatore-central",
    "sortOrder": 565,
    "priorityTier": 2
  },
  {
    "slug": "town-hall",
    "name": "Town Hall",
    "zone": "coimbatore-central",
    "sortOrder": 566,
    "priorityTier": 3
  },
  {
    "slug": "trichy-road",
    "name": "Trichy Road",
    "zone": "singanallur",
    "sortOrder": 567,
    "priorityTier": 3
  },
  {
    "slug": "trichy-road-coimbatore",
    "name": "Trichy Road Coimbatore",
    "zone": "coimbatore-central",
    "sortOrder": 568,
    "priorityTier": 3
  },
  {
    "slug": "trichy-road-ramanathapuram",
    "name": "Trichy Road Ramanathapuram",
    "zone": "coimbatore-central",
    "sortOrder": 569,
    "priorityTier": 3
  },
  {
    "slug": "udayampalayam",
    "name": "Udayampalayam",
    "zone": "coimbatore-central",
    "sortOrder": 570,
    "priorityTier": 3
  },
  {
    "slug": "udayampalayam-singanallur",
    "name": "Udayampalayam Singanallur",
    "zone": "singanallur",
    "sortOrder": 571,
    "priorityTier": 3
  },
  {
    "slug": "ukkadam",
    "name": "Ukkadam",
    "zone": "coimbatore-central",
    "sortOrder": 572,
    "priorityTier": 1
  },
  {
    "slug": "ukkadam-bus-stand-area",
    "name": "Ukkadam Bus Stand Area",
    "zone": "coimbatore-central",
    "sortOrder": 573,
    "priorityTier": 3
  },
  {
    "slug": "uppilipalayam",
    "name": "Uppilipalayam",
    "zone": "singanallur",
    "sortOrder": 574,
    "priorityTier": 2
  },
  {
    "slug": "uppilipalayam-pirivu",
    "name": "Uppilipalayam Pirivu",
    "zone": "singanallur",
    "sortOrder": 575,
    "priorityTier": 3
  },
  {
    "slug": "uppilipalayam-road",
    "name": "Uppilipalayam Road",
    "zone": "singanallur",
    "sortOrder": 576,
    "priorityTier": 3
  },
  {
    "slug": "vg-rao-nagar",
    "name": "V.G. Rao Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 577,
    "priorityTier": 3
  },
  {
    "slug": "vk-road",
    "name": "V.K. Road",
    "zone": "coimbatore-central",
    "sortOrder": 578,
    "priorityTier": 3
  },
  {
    "slug": "vadachittur",
    "name": "Vadachittur",
    "zone": "coimbatore-central",
    "sortOrder": 579,
    "priorityTier": 3
  },
  {
    "slug": "vadakkalur",
    "name": "Vadakkalur",
    "zone": "coimbatore-central",
    "sortOrder": 580,
    "priorityTier": 3
  },
  {
    "slug": "vadamadurai",
    "name": "Vadamadurai",
    "zone": "coimbatore-central",
    "sortOrder": 581,
    "priorityTier": 3
  },
  {
    "slug": "vadavalli",
    "name": "Vadavalli",
    "zone": "saibaba-colony",
    "sortOrder": 582,
    "priorityTier": 1
  },
  {
    "slug": "vadavalli-bus-stand-area",
    "name": "Vadavalli Bus Stand Area",
    "zone": "saibaba-colony",
    "sortOrder": 583,
    "priorityTier": 3
  },
  {
    "slug": "valparai",
    "name": "Valparai",
    "zone": "coimbatore-central",
    "sortOrder": 584,
    "priorityTier": 3
  },
  {
    "slug": "valparai-town",
    "name": "Valparai Town",
    "zone": "coimbatore-central",
    "sortOrder": 585,
    "priorityTier": 3
  },
  {
    "slug": "varatharajapuram",
    "name": "Varatharajapuram",
    "zone": "coimbatore-central",
    "sortOrder": 586,
    "priorityTier": 3
  },
  {
    "slug": "variety-hall-road",
    "name": "Variety Hall Road",
    "zone": "coimbatore-central",
    "sortOrder": 587,
    "priorityTier": 3
  },
  {
    "slug": "vasantham-nagar",
    "name": "Vasantham Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 588,
    "priorityTier": 3
  },
  {
    "slug": "vedapatti-road",
    "name": "Vedapatti Road",
    "zone": "coimbatore-central",
    "sortOrder": 589,
    "priorityTier": 3
  },
  {
    "slug": "veerakeralam",
    "name": "Veerakeralam",
    "zone": "coimbatore-central",
    "sortOrder": 590,
    "priorityTier": 3
  },
  {
    "slug": "veerakeralam-road",
    "name": "Veerakeralam Road",
    "zone": "coimbatore-central",
    "sortOrder": 591,
    "priorityTier": 3
  },
  {
    "slug": "vellakinar",
    "name": "Vellakinar",
    "zone": "coimbatore-central",
    "sortOrder": 592,
    "priorityTier": 3
  },
  {
    "slug": "vellakinar-pirivu",
    "name": "Vellakinar Pirivu",
    "zone": "coimbatore-central",
    "sortOrder": 593,
    "priorityTier": 3
  },
  {
    "slug": "vellalore",
    "name": "Vellalore",
    "zone": "coimbatore-central",
    "sortOrder": 594,
    "priorityTier": 3
  },
  {
    "slug": "vellalore-housing-unit",
    "name": "Vellalore Housing Unit",
    "zone": "coimbatore-central",
    "sortOrder": 595,
    "priorityTier": 3
  },
  {
    "slug": "vellalore-road",
    "name": "Vellalore Road",
    "zone": "coimbatore-central",
    "sortOrder": 596,
    "priorityTier": 3
  },
  {
    "slug": "vellamadai",
    "name": "Vellamadai",
    "zone": "coimbatore-central",
    "sortOrder": 597,
    "priorityTier": 3
  },
  {
    "slug": "vellimalaipattinam",
    "name": "Vellimalaipattinam",
    "zone": "coimbatore-central",
    "sortOrder": 598,
    "priorityTier": 3
  },
  {
    "slug": "venkatasamy-road",
    "name": "Venkatasamy Road",
    "zone": "coimbatore-central",
    "sortOrder": 599,
    "priorityTier": 3
  },
  {
    "slug": "venkitapuram",
    "name": "Venkitapuram",
    "zone": "coimbatore-central",
    "sortOrder": 600,
    "priorityTier": 3
  },
  {
    "slug": "venkitta-puram",
    "name": "Venkitta Puram",
    "zone": "coimbatore-central",
    "sortOrder": 601,
    "priorityTier": 3
  },
  {
    "slug": "vetri-vinayagar-nagar",
    "name": "Vetri Vinayagar Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 602,
    "priorityTier": 3
  },
  {
    "slug": "vetrilaikaranpalayam",
    "name": "Vetrilaikaranpalayam",
    "zone": "coimbatore-central",
    "sortOrder": 603,
    "priorityTier": 3
  },
  {
    "slug": "vettaikaranpudur",
    "name": "Vettaikaranpudur",
    "zone": "coimbatore-central",
    "sortOrder": 604,
    "priorityTier": 3
  },
  {
    "slug": "vgp-prem-nagar",
    "name": "VGP Prem Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 605,
    "priorityTier": 3
  },
  {
    "slug": "vilankurichi",
    "name": "Vilankurichi",
    "zone": "saravanampatti",
    "sortOrder": 606,
    "priorityTier": 1
  },
  {
    "slug": "vilankurichi-industrial-area",
    "name": "Vilankurichi Industrial Area",
    "zone": "saravanampatti",
    "sortOrder": 607,
    "priorityTier": 3
  },
  {
    "slug": "vilankurichi-it-park-area",
    "name": "Vilankurichi It Park Area",
    "zone": "saravanampatti",
    "sortOrder": 608,
    "priorityTier": 3
  },
  {
    "slug": "vilankurichi-road",
    "name": "Vilankurichi Road",
    "zone": "saravanampatti",
    "sortOrder": 609,
    "priorityTier": 3
  },
  {
    "slug": "vilankurichi-road-coimbatore",
    "name": "Vilankurichi Road Coimbatore",
    "zone": "saravanampatti",
    "sortOrder": 610,
    "priorityTier": 3
  },
  {
    "slug": "vivekananda-nagar",
    "name": "Vivekananda Nagar",
    "zone": "coimbatore-central",
    "sortOrder": 611,
    "priorityTier": 3
  },
  {
    "slug": "voc-park-area",
    "name": "VOC Park Area",
    "zone": "coimbatore-central",
    "sortOrder": 612,
    "priorityTier": 3
  },
  {
    "slug": "walayar-road",
    "name": "Walayar Road",
    "zone": "coimbatore-central",
    "sortOrder": 613,
    "priorityTier": 3
  },
  {
    "slug": "west-club-road",
    "name": "West Club Road",
    "zone": "coimbatore-central",
    "sortOrder": 614,
    "priorityTier": 3
  },
  {
    "slug": "zamin-uthukuli",
    "name": "Zamin Uthukuli",
    "zone": "coimbatore-central",
    "sortOrder": 615,
    "priorityTier": 3
  }
];

export const COIMBATORE_AREA_COUNT = 615;

export function getCoimbatoreAreaBySlug(slug: string): CoimbatoreArea | undefined {
  return COIMBATORE_AREAS.find((a) => a.slug === slug);
}
