/** Auto-generated by scripts/generate-hyderabad-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface HyderabadArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const HYDERABAD_AREAS: HyderabadArea[] = [
  {
    "slug": "as-rao-nagar",
    "name": "Dr A. S. Rao Nagar",
    "zone": "north-hyderabad",
    "sortOrder": 1,
    "priorityTier": 2
  },
  {
    "slug": "abdullapurmet",
    "name": "Abdullapurmet",
    "zone": "west-hyderabad",
    "sortOrder": 2,
    "priorityTier": 3
  },
  {
    "slug": "abids",
    "name": "Abids",
    "zone": "west-hyderabad",
    "sortOrder": 3,
    "priorityTier": 3
  },
  {
    "slug": "ac-guards",
    "name": "Ac Guards",
    "zone": "west-hyderabad",
    "sortOrder": 4,
    "priorityTier": 3
  },
  {
    "slug": "adarsh-nagar",
    "name": "Adarsh Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 5,
    "priorityTier": 3
  },
  {
    "slug": "adibatla",
    "name": "Adibatla",
    "zone": "west-hyderabad",
    "sortOrder": 6,
    "priorityTier": 2
  },
  {
    "slug": "adikmet",
    "name": "Adikmet",
    "zone": "west-hyderabad",
    "sortOrder": 7,
    "priorityTier": 3
  },
  {
    "slug": "afzal-gunj",
    "name": "Afzal Gunj",
    "zone": "west-hyderabad",
    "sortOrder": 8,
    "priorityTier": 3
  },
  {
    "slug": "agapura",
    "name": "Agapura",
    "zone": "west-hyderabad",
    "sortOrder": 9,
    "priorityTier": 3
  },
  {
    "slug": "ahmed-nagar",
    "name": "Ahmed Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 10,
    "priorityTier": 3
  },
  {
    "slug": "alijah-kotla",
    "name": "Alijah Kotla",
    "zone": "west-hyderabad",
    "sortOrder": 11,
    "priorityTier": 3
  },
  {
    "slug": "alkapur-township",
    "name": "Alkapur Township",
    "zone": "west-hyderabad",
    "sortOrder": 12,
    "priorityTier": 3
  },
  {
    "slug": "allwyn-colony",
    "name": "Allwyn Colony",
    "zone": "west-hyderabad",
    "sortOrder": 13,
    "priorityTier": 3
  },
  {
    "slug": "almasguda",
    "name": "Almasguda",
    "zone": "west-hyderabad",
    "sortOrder": 14,
    "priorityTier": 3
  },
  {
    "slug": "alwal",
    "name": "Alwal",
    "zone": "north-hyderabad",
    "sortOrder": 15,
    "priorityTier": 1
  },
  {
    "slug": "amberpet",
    "name": "Amberpet",
    "zone": "west-hyderabad",
    "sortOrder": 16,
    "priorityTier": 3
  },
  {
    "slug": "ameenpur",
    "name": "Ameenpur",
    "zone": "west-hyderabad",
    "sortOrder": 17,
    "priorityTier": 3
  },
  {
    "slug": "ameerpet",
    "name": "Ameerpet",
    "zone": "central-hyderabad",
    "sortOrder": 18,
    "priorityTier": 1
  },
  {
    "slug": "ammuguda",
    "name": "Ammuguda",
    "zone": "west-hyderabad",
    "sortOrder": 19,
    "priorityTier": 3
  },
  {
    "slug": "anand-bagh",
    "name": "Anand Bagh",
    "zone": "west-hyderabad",
    "sortOrder": 20,
    "priorityTier": 3
  },
  {
    "slug": "anand-nagar-colony",
    "name": "Anand Nagar Colony",
    "zone": "west-hyderabad",
    "sortOrder": 21,
    "priorityTier": 3
  },
  {
    "slug": "anjaiah-nagar",
    "name": "Anjaiah Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 22,
    "priorityTier": 3
  },
  {
    "slug": "annojiguda",
    "name": "Annojiguda",
    "zone": "west-hyderabad",
    "sortOrder": 23,
    "priorityTier": 3
  },
  {
    "slug": "appa-junction",
    "name": "Appa Junction",
    "zone": "west-hyderabad",
    "sortOrder": 24,
    "priorityTier": 3
  },
  {
    "slug": "aramghar",
    "name": "Aramghar",
    "zone": "west-hyderabad",
    "sortOrder": 25,
    "priorityTier": 3
  },
  {
    "slug": "ashok-nagar",
    "name": "Ashok Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 26,
    "priorityTier": 3
  },
  {
    "slug": "asif-nagar",
    "name": "Asif Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 27,
    "priorityTier": 3
  },
  {
    "slug": "attapur",
    "name": "Attapur",
    "zone": "west-hyderabad",
    "sortOrder": 28,
    "priorityTier": 1
  },
  {
    "slug": "auto-nagar",
    "name": "Auto Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 29,
    "priorityTier": 3
  },
  {
    "slug": "azamabad",
    "name": "Azamabad",
    "zone": "west-hyderabad",
    "sortOrder": 30,
    "priorityTier": 3
  },
  {
    "slug": "azampura",
    "name": "Azampura",
    "zone": "west-hyderabad",
    "sortOrder": 31,
    "priorityTier": 3
  },
  {
    "slug": "aziz-nagar",
    "name": "Aziz Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 32,
    "priorityTier": 3
  },
  {
    "slug": "bn-reddy-nagar",
    "name": "B.N. Reddy Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 33,
    "priorityTier": 3
  },
  {
    "slug": "bachupally",
    "name": "Bachupally",
    "zone": "north-hyderabad",
    "sortOrder": 34,
    "priorityTier": 1
  },
  {
    "slug": "badangpet",
    "name": "Badangpet",
    "zone": "west-hyderabad",
    "sortOrder": 35,
    "priorityTier": 3
  },
  {
    "slug": "bahadurpally",
    "name": "Bahadurpally",
    "zone": "west-hyderabad",
    "sortOrder": 36,
    "priorityTier": 3
  },
  {
    "slug": "bahadurpura",
    "name": "Bahadurpura",
    "zone": "west-hyderabad",
    "sortOrder": 37,
    "priorityTier": 3
  },
  {
    "slug": "bairamalguda",
    "name": "Bairamalguda",
    "zone": "west-hyderabad",
    "sortOrder": 38,
    "priorityTier": 3
  },
  {
    "slug": "balanagar",
    "name": "Balanagar",
    "zone": "west-hyderabad",
    "sortOrder": 39,
    "priorityTier": 3
  },
  {
    "slug": "balapur",
    "name": "Balapur",
    "zone": "west-hyderabad",
    "sortOrder": 40,
    "priorityTier": 3
  },
  {
    "slug": "balkampet",
    "name": "Balkampet",
    "zone": "west-hyderabad",
    "sortOrder": 41,
    "priorityTier": 3
  },
  {
    "slug": "bandlaguda",
    "name": "Bandlaguda",
    "zone": "west-hyderabad",
    "sortOrder": 42,
    "priorityTier": 3
  },
  {
    "slug": "bandlaguda-jagir",
    "name": "Bandlaguda Jagir",
    "zone": "west-hyderabad",
    "sortOrder": 43,
    "priorityTier": 3
  },
  {
    "slug": "banjara-hills",
    "name": "Banjara Hills",
    "zone": "central-hyderabad",
    "sortOrder": 44,
    "priorityTier": 1
  },
  {
    "slug": "barkas",
    "name": "Barkas",
    "zone": "west-hyderabad",
    "sortOrder": 45,
    "priorityTier": 3
  },
  {
    "slug": "barkatpura",
    "name": "Barkatpura",
    "zone": "west-hyderabad",
    "sortOrder": 46,
    "priorityTier": 3
  },
  {
    "slug": "basheerbagh",
    "name": "Basheerbagh",
    "zone": "west-hyderabad",
    "sortOrder": 47,
    "priorityTier": 3
  },
  {
    "slug": "beeramguda",
    "name": "Beeramguda",
    "zone": "west-hyderabad",
    "sortOrder": 48,
    "priorityTier": 3
  },
  {
    "slug": "begum-bazaar",
    "name": "Begum Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 49,
    "priorityTier": 3
  },
  {
    "slug": "begumpet",
    "name": "Begumpet",
    "zone": "central-hyderabad",
    "sortOrder": 50,
    "priorityTier": 2
  },
  {
    "slug": "bhag-amberpet",
    "name": "Bhag Amberpet",
    "zone": "west-hyderabad",
    "sortOrder": 51,
    "priorityTier": 3
  },
  {
    "slug": "bharat-nagar",
    "name": "Bharat Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 52,
    "priorityTier": 3
  },
  {
    "slug": "bhel-township",
    "name": "Bhel Township",
    "zone": "west-hyderabad",
    "sortOrder": 53,
    "priorityTier": 3
  },
  {
    "slug": "bhoiguda",
    "name": "Bhoiguda",
    "zone": "west-hyderabad",
    "sortOrder": 54,
    "priorityTier": 3
  },
  {
    "slug": "bholakpur",
    "name": "Bholakpur",
    "zone": "west-hyderabad",
    "sortOrder": 55,
    "priorityTier": 3
  },
  {
    "slug": "boduppal",
    "name": "Boduppal",
    "zone": "west-hyderabad",
    "sortOrder": 56,
    "priorityTier": 3
  },
  {
    "slug": "boggulkunta",
    "name": "Boggulkunta",
    "zone": "west-hyderabad",
    "sortOrder": 57,
    "priorityTier": 3
  },
  {
    "slug": "bolarum",
    "name": "Bolarum",
    "zone": "west-hyderabad",
    "sortOrder": 58,
    "priorityTier": 3
  },
  {
    "slug": "bongloor",
    "name": "Bongloor",
    "zone": "west-hyderabad",
    "sortOrder": 59,
    "priorityTier": 3
  },
  {
    "slug": "borabanda",
    "name": "Borabanda",
    "zone": "west-hyderabad",
    "sortOrder": 60,
    "priorityTier": 3
  },
  {
    "slug": "botanical-garden",
    "name": "Botanical Garden",
    "zone": "west-hyderabad",
    "sortOrder": 61,
    "priorityTier": 3
  },
  {
    "slug": "boudha-nagar",
    "name": "Boudha Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 62,
    "priorityTier": 3
  },
  {
    "slug": "bowenpally",
    "name": "Bowenpally",
    "zone": "north-hyderabad",
    "sortOrder": 63,
    "priorityTier": 1
  },
  {
    "slug": "bowrampet",
    "name": "Bowrampet",
    "zone": "west-hyderabad",
    "sortOrder": 64,
    "priorityTier": 3
  },
  {
    "slug": "brahmanwadi",
    "name": "Brahmanwadi",
    "zone": "west-hyderabad",
    "sortOrder": 65,
    "priorityTier": 3
  },
  {
    "slug": "budvel",
    "name": "Budvel",
    "zone": "west-hyderabad",
    "sortOrder": 66,
    "priorityTier": 3
  },
  {
    "slug": "chaderghat",
    "name": "Chaderghat",
    "zone": "west-hyderabad",
    "sortOrder": 67,
    "priorityTier": 3
  },
  {
    "slug": "chaitanyapuri",
    "name": "Chaitanyapuri",
    "zone": "west-hyderabad",
    "sortOrder": 68,
    "priorityTier": 3
  },
  {
    "slug": "champapet",
    "name": "Champapet",
    "zone": "west-hyderabad",
    "sortOrder": 69,
    "priorityTier": 3
  },
  {
    "slug": "chanchalguda",
    "name": "Chanchalguda",
    "zone": "west-hyderabad",
    "sortOrder": 70,
    "priorityTier": 3
  },
  {
    "slug": "chandanagar",
    "name": "Chandanagar",
    "zone": "west-hyderabad",
    "sortOrder": 71,
    "priorityTier": 3
  },
  {
    "slug": "chandrayanagutta",
    "name": "Chandrayanagutta",
    "zone": "west-hyderabad",
    "sortOrder": 72,
    "priorityTier": 3
  },
  {
    "slug": "charminar",
    "name": "Charminar",
    "zone": "old-city",
    "sortOrder": 73,
    "priorityTier": 3
  },
  {
    "slug": "chengicherla",
    "name": "Chengicherla",
    "zone": "west-hyderabad",
    "sortOrder": 74,
    "priorityTier": 3
  },
  {
    "slug": "cherlapally",
    "name": "Cherlapally",
    "zone": "west-hyderabad",
    "sortOrder": 75,
    "priorityTier": 3
  },
  {
    "slug": "chevella",
    "name": "Chevella",
    "zone": "outer-hyderabad",
    "sortOrder": 76,
    "priorityTier": 3
  },
  {
    "slug": "chikkadpally",
    "name": "Chikkadpally",
    "zone": "west-hyderabad",
    "sortOrder": 77,
    "priorityTier": 3
  },
  {
    "slug": "chilakalguda",
    "name": "Chilakalguda",
    "zone": "west-hyderabad",
    "sortOrder": 78,
    "priorityTier": 3
  },
  {
    "slug": "chilkalguda",
    "name": "Chilkalguda",
    "zone": "west-hyderabad",
    "sortOrder": 79,
    "priorityTier": 3
  },
  {
    "slug": "chilkur",
    "name": "Chilkur",
    "zone": "west-hyderabad",
    "sortOrder": 80,
    "priorityTier": 3
  },
  {
    "slug": "chintal",
    "name": "Chintal",
    "zone": "west-hyderabad",
    "sortOrder": 81,
    "priorityTier": 3
  },
  {
    "slug": "chintalkunta",
    "name": "Chintalkunta",
    "zone": "west-hyderabad",
    "sortOrder": 82,
    "priorityTier": 3
  },
  {
    "slug": "chintalmet",
    "name": "Chintalmet",
    "zone": "west-hyderabad",
    "sortOrder": 83,
    "priorityTier": 3
  },
  {
    "slug": "chowmahalla",
    "name": "Chowmahalla",
    "zone": "west-hyderabad",
    "sortOrder": 84,
    "priorityTier": 3
  },
  {
    "slug": "d-d-colony",
    "name": "D.D. Colony",
    "zone": "west-hyderabad",
    "sortOrder": 85,
    "priorityTier": 3
  },
  {
    "slug": "dabirpura",
    "name": "Dabirpura",
    "zone": "west-hyderabad",
    "sortOrder": 86,
    "priorityTier": 3
  },
  {
    "slug": "dammaiguda",
    "name": "Dammaiguda",
    "zone": "west-hyderabad",
    "sortOrder": 87,
    "priorityTier": 3
  },
  {
    "slug": "darulshifa",
    "name": "Darulshifa",
    "zone": "west-hyderabad",
    "sortOrder": 88,
    "priorityTier": 3
  },
  {
    "slug": "dattatreya-nagar",
    "name": "Dattatreya Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 89,
    "priorityTier": 3
  },
  {
    "slug": "dhoolpet",
    "name": "Dhoolpet",
    "zone": "west-hyderabad",
    "sortOrder": 90,
    "priorityTier": 3
  },
  {
    "slug": "dilsukhnagar",
    "name": "Dilsukhnagar",
    "zone": "east-hyderabad",
    "sortOrder": 91,
    "priorityTier": 1
  },
  {
    "slug": "domalguda",
    "name": "Domalguda",
    "zone": "west-hyderabad",
    "sortOrder": 92,
    "priorityTier": 3
  },
  {
    "slug": "doodh-bowli",
    "name": "Doodh Bowli",
    "zone": "west-hyderabad",
    "sortOrder": 93,
    "priorityTier": 3
  },
  {
    "slug": "dundigal",
    "name": "Dundigal",
    "zone": "north-hyderabad",
    "sortOrder": 94,
    "priorityTier": 3
  },
  {
    "slug": "east-anandbagh",
    "name": "East Anandbagh",
    "zone": "west-hyderabad",
    "sortOrder": 95,
    "priorityTier": 3
  },
  {
    "slug": "east-marredpally",
    "name": "East Marredpally",
    "zone": "west-hyderabad",
    "sortOrder": 96,
    "priorityTier": 3
  },
  {
    "slug": "ecil",
    "name": "ECIL",
    "zone": "north-hyderabad",
    "sortOrder": 97,
    "priorityTier": 2
  },
  {
    "slug": "edi-bazaar",
    "name": "Edi Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 98,
    "priorityTier": 3
  },
  {
    "slug": "erragadda",
    "name": "Erragadda",
    "zone": "west-hyderabad",
    "sortOrder": 99,
    "priorityTier": 2
  },
  {
    "slug": "erramanzil",
    "name": "Erramanzil",
    "zone": "west-hyderabad",
    "sortOrder": 100,
    "priorityTier": 3
  },
  {
    "slug": "falaknuma",
    "name": "Falaknuma",
    "zone": "old-city",
    "sortOrder": 101,
    "priorityTier": 3
  },
  {
    "slug": "fateh-darwaza",
    "name": "Fateh Darwaza",
    "zone": "west-hyderabad",
    "sortOrder": 102,
    "priorityTier": 3
  },
  {
    "slug": "fateh-nagar",
    "name": "Fateh Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 103,
    "priorityTier": 3
  },
  {
    "slug": "feelkhana",
    "name": "Feelkhana",
    "zone": "west-hyderabad",
    "sortOrder": 104,
    "priorityTier": 3
  },
  {
    "slug": "film-nagar",
    "name": "Film Nagar",
    "zone": "central-hyderabad",
    "sortOrder": 105,
    "priorityTier": 1
  },
  {
    "slug": "financial-district",
    "name": "Financial District",
    "zone": "west-hyderabad",
    "sortOrder": 106,
    "priorityTier": 1
  },
  {
    "slug": "gachibowli",
    "name": "Gachibowli",
    "zone": "west-hyderabad",
    "sortOrder": 107,
    "priorityTier": 1
  },
  {
    "slug": "gaganpahad",
    "name": "Gaganpahad",
    "zone": "west-hyderabad",
    "sortOrder": 108,
    "priorityTier": 3
  },
  {
    "slug": "gajularamaram",
    "name": "Gajularamaram",
    "zone": "west-hyderabad",
    "sortOrder": 109,
    "priorityTier": 3
  },
  {
    "slug": "gandhi-nagar",
    "name": "Gandhi Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 110,
    "priorityTier": 3
  },
  {
    "slug": "gandimaisamma",
    "name": "Gandimaisamma",
    "zone": "west-hyderabad",
    "sortOrder": 111,
    "priorityTier": 3
  },
  {
    "slug": "gandipet",
    "name": "Gandipet",
    "zone": "west-hyderabad",
    "sortOrder": 112,
    "priorityTier": 3
  },
  {
    "slug": "general-bazaar",
    "name": "General Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 113,
    "priorityTier": 3
  },
  {
    "slug": "ghansi-bazaar",
    "name": "Ghansi Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 114,
    "priorityTier": 3
  },
  {
    "slug": "ghatkesar",
    "name": "Ghatkesar",
    "zone": "west-hyderabad",
    "sortOrder": 115,
    "priorityTier": 3
  },
  {
    "slug": "golconda",
    "name": "Golconda",
    "zone": "west-hyderabad",
    "sortOrder": 116,
    "priorityTier": 3
  },
  {
    "slug": "gopanpally",
    "name": "Gopanpally",
    "zone": "west-hyderabad",
    "sortOrder": 117,
    "priorityTier": 3
  },
  {
    "slug": "goshamahal",
    "name": "Goshamahal",
    "zone": "west-hyderabad",
    "sortOrder": 118,
    "priorityTier": 3
  },
  {
    "slug": "gowlidoddy",
    "name": "Gowlidoddy",
    "zone": "west-hyderabad",
    "sortOrder": 119,
    "priorityTier": 3
  },
  {
    "slug": "gudimalkapur",
    "name": "Gudimalkapur",
    "zone": "west-hyderabad",
    "sortOrder": 120,
    "priorityTier": 3
  },
  {
    "slug": "gundlapochampally",
    "name": "Gundlapochampally",
    "zone": "west-hyderabad",
    "sortOrder": 121,
    "priorityTier": 3
  },
  {
    "slug": "habsiguda",
    "name": "Habsiguda",
    "zone": "west-hyderabad",
    "sortOrder": 122,
    "priorityTier": 1
  },
  {
    "slug": "hafeezpet",
    "name": "Hafeezpet",
    "zone": "west-hyderabad",
    "sortOrder": 123,
    "priorityTier": 1
  },
  {
    "slug": "hakimpet",
    "name": "Hakimpet",
    "zone": "west-hyderabad",
    "sortOrder": 124,
    "priorityTier": 3
  },
  {
    "slug": "hasmathpet",
    "name": "Hasmathpet",
    "zone": "west-hyderabad",
    "sortOrder": 125,
    "priorityTier": 3
  },
  {
    "slug": "hastinapuram",
    "name": "Hastinapuram",
    "zone": "west-hyderabad",
    "sortOrder": 126,
    "priorityTier": 3
  },
  {
    "slug": "hayathnagar",
    "name": "Hayathnagar",
    "zone": "east-hyderabad",
    "sortOrder": 127,
    "priorityTier": 3
  },
  {
    "slug": "himayat-sagar",
    "name": "Himayat Sagar",
    "zone": "west-hyderabad",
    "sortOrder": 128,
    "priorityTier": 3
  },
  {
    "slug": "himayatnagar",
    "name": "Himayatnagar",
    "zone": "west-hyderabad",
    "sortOrder": 129,
    "priorityTier": 3
  },
  {
    "slug": "hitech-city",
    "name": "Hitec City",
    "zone": "west-hyderabad",
    "sortOrder": 130,
    "priorityTier": 1
  },
  {
    "slug": "hmt-colony",
    "name": "HMT Colony",
    "zone": "west-hyderabad",
    "sortOrder": 131,
    "priorityTier": 3
  },
  {
    "slug": "humayun-nagar",
    "name": "Humayun Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 132,
    "priorityTier": 3
  },
  {
    "slug": "hyder-nagar",
    "name": "Hyder Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 133,
    "priorityTier": 3
  },
  {
    "slug": "hyderguda",
    "name": "Hyderguda",
    "zone": "west-hyderabad",
    "sortOrder": 134,
    "priorityTier": 3
  },
  {
    "slug": "hydershakote",
    "name": "Hydershakote",
    "zone": "west-hyderabad",
    "sortOrder": 135,
    "priorityTier": 3
  },
  {
    "slug": "ibrahim-bagh",
    "name": "Ibrahim Bagh",
    "zone": "west-hyderabad",
    "sortOrder": 136,
    "priorityTier": 3
  },
  {
    "slug": "ibrahimpatnam",
    "name": "Ibrahimpatnam",
    "zone": "outer-hyderabad",
    "sortOrder": 137,
    "priorityTier": 3
  },
  {
    "slug": "injapur",
    "name": "Injapur",
    "zone": "west-hyderabad",
    "sortOrder": 138,
    "priorityTier": 3
  },
  {
    "slug": "isnapur",
    "name": "Isnapur",
    "zone": "west-hyderabad",
    "sortOrder": 139,
    "priorityTier": 3
  },
  {
    "slug": "jahanuma",
    "name": "Jahanuma",
    "zone": "west-hyderabad",
    "sortOrder": 140,
    "priorityTier": 3
  },
  {
    "slug": "jalpally",
    "name": "Jalpally",
    "zone": "west-hyderabad",
    "sortOrder": 141,
    "priorityTier": 3
  },
  {
    "slug": "jam-bagh",
    "name": "Jam Bagh",
    "zone": "west-hyderabad",
    "sortOrder": 142,
    "priorityTier": 3
  },
  {
    "slug": "jambagh",
    "name": "Jambagh",
    "zone": "west-hyderabad",
    "sortOrder": 143,
    "priorityTier": 3
  },
  {
    "slug": "james-street",
    "name": "James Street",
    "zone": "west-hyderabad",
    "sortOrder": 144,
    "priorityTier": 3
  },
  {
    "slug": "jawahar-nagar",
    "name": "Jawahar Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 145,
    "priorityTier": 3
  },
  {
    "slug": "jeedimetla",
    "name": "Jeedimetla",
    "zone": "west-hyderabad",
    "sortOrder": 146,
    "priorityTier": 3
  },
  {
    "slug": "jillelguda",
    "name": "Jillelguda",
    "zone": "west-hyderabad",
    "sortOrder": 147,
    "priorityTier": 3
  },
  {
    "slug": "jiyaguda",
    "name": "Jiyaguda",
    "zone": "west-hyderabad",
    "sortOrder": 148,
    "priorityTier": 3
  },
  {
    "slug": "jntu",
    "name": "JNTU",
    "zone": "west-hyderabad",
    "sortOrder": 149,
    "priorityTier": 3
  },
  {
    "slug": "jubilee-hills",
    "name": "Jubilee Hills",
    "zone": "central-hyderabad",
    "sortOrder": 150,
    "priorityTier": 1
  },
  {
    "slug": "kachiguda",
    "name": "Kachiguda",
    "zone": "west-hyderabad",
    "sortOrder": 151,
    "priorityTier": 3
  },
  {
    "slug": "kakatiya-nagar",
    "name": "Kakatiya Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 152,
    "priorityTier": 3
  },
  {
    "slug": "kalapathar",
    "name": "Kalapathar",
    "zone": "west-hyderabad",
    "sortOrder": 153,
    "priorityTier": 3
  },
  {
    "slug": "kalasiguda",
    "name": "Kalasiguda",
    "zone": "west-hyderabad",
    "sortOrder": 154,
    "priorityTier": 3
  },
  {
    "slug": "kanchanbagh",
    "name": "Kanchanbagh",
    "zone": "west-hyderabad",
    "sortOrder": 155,
    "priorityTier": 3
  },
  {
    "slug": "kandi",
    "name": "Kandi",
    "zone": "west-hyderabad",
    "sortOrder": 156,
    "priorityTier": 3
  },
  {
    "slug": "kandlakoya",
    "name": "Kandlakoya",
    "zone": "west-hyderabad",
    "sortOrder": 157,
    "priorityTier": 3
  },
  {
    "slug": "kapra",
    "name": "Kapra",
    "zone": "north-hyderabad",
    "sortOrder": 158,
    "priorityTier": 3
  },
  {
    "slug": "karkhana",
    "name": "Karkhana",
    "zone": "west-hyderabad",
    "sortOrder": 159,
    "priorityTier": 3
  },
  {
    "slug": "karmanghat",
    "name": "Karmanghat",
    "zone": "west-hyderabad",
    "sortOrder": 160,
    "priorityTier": 3
  },
  {
    "slug": "karwan",
    "name": "Karwan",
    "zone": "west-hyderabad",
    "sortOrder": 161,
    "priorityTier": 3
  },
  {
    "slug": "katedan",
    "name": "Katedan",
    "zone": "west-hyderabad",
    "sortOrder": 162,
    "priorityTier": 3
  },
  {
    "slug": "kavadiguda",
    "name": "Kavadiguda",
    "zone": "west-hyderabad",
    "sortOrder": 163,
    "priorityTier": 3
  },
  {
    "slug": "keesara",
    "name": "Keesara",
    "zone": "west-hyderabad",
    "sortOrder": 164,
    "priorityTier": 3
  },
  {
    "slug": "khairatabad",
    "name": "Khairatabad",
    "zone": "central-hyderabad",
    "sortOrder": 165,
    "priorityTier": 3
  },
  {
    "slug": "khajaguda",
    "name": "Khajaguda",
    "zone": "west-hyderabad",
    "sortOrder": 166,
    "priorityTier": 3
  },
  {
    "slug": "khanamet",
    "name": "Khanamet",
    "zone": "west-hyderabad",
    "sortOrder": 167,
    "priorityTier": 3
  },
  {
    "slug": "khilwat",
    "name": "Khilwat",
    "zone": "west-hyderabad",
    "sortOrder": 168,
    "priorityTier": 3
  },
  {
    "slug": "king-koti",
    "name": "King Koti",
    "zone": "west-hyderabad",
    "sortOrder": 169,
    "priorityTier": 3
  },
  {
    "slug": "kishanbagh",
    "name": "Kishanbagh",
    "zone": "west-hyderabad",
    "sortOrder": 170,
    "priorityTier": 3
  },
  {
    "slug": "kismatpur",
    "name": "Kismatpur",
    "zone": "west-hyderabad",
    "sortOrder": 171,
    "priorityTier": 3
  },
  {
    "slug": "koheda",
    "name": "Koheda",
    "zone": "west-hyderabad",
    "sortOrder": 172,
    "priorityTier": 3
  },
  {
    "slug": "kokapet",
    "name": "Kokapet",
    "zone": "west-hyderabad",
    "sortOrder": 173,
    "priorityTier": 1
  },
  {
    "slug": "kollur",
    "name": "Kollur",
    "zone": "west-hyderabad",
    "sortOrder": 174,
    "priorityTier": 3
  },
  {
    "slug": "kompally",
    "name": "Kompally",
    "zone": "north-hyderabad",
    "sortOrder": 175,
    "priorityTier": 1
  },
  {
    "slug": "kondapur",
    "name": "Kondapur",
    "zone": "west-hyderabad",
    "sortOrder": 176,
    "priorityTier": 1
  },
  {
    "slug": "kongara-kalan",
    "name": "Kongara Kalan",
    "zone": "west-hyderabad",
    "sortOrder": 177,
    "priorityTier": 3
  },
  {
    "slug": "kothaguda",
    "name": "Kothaguda",
    "zone": "west-hyderabad",
    "sortOrder": 178,
    "priorityTier": 1
  },
  {
    "slug": "kothapet",
    "name": "Kothapet",
    "zone": "west-hyderabad",
    "sortOrder": 179,
    "priorityTier": 3
  },
  {
    "slug": "kothur",
    "name": "Kothur",
    "zone": "west-hyderabad",
    "sortOrder": 180,
    "priorityTier": 3
  },
  {
    "slug": "koti",
    "name": "Koti",
    "zone": "west-hyderabad",
    "sortOrder": 181,
    "priorityTier": 3
  },
  {
    "slug": "kowkoor",
    "name": "Kowkoor",
    "zone": "west-hyderabad",
    "sortOrder": 182,
    "priorityTier": 3
  },
  {
    "slug": "kphb-colony",
    "name": "KPHB Colony",
    "zone": "west-hyderabad",
    "sortOrder": 183,
    "priorityTier": 2
  },
  {
    "slug": "krishna-nagar",
    "name": "Krishna Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 184,
    "priorityTier": 3
  },
  {
    "slug": "kukatpally",
    "name": "Kukatpally",
    "zone": "west-hyderabad",
    "sortOrder": 185,
    "priorityTier": 1
  },
  {
    "slug": "kushaiguda",
    "name": "Kushaiguda",
    "zone": "west-hyderabad",
    "sortOrder": 186,
    "priorityTier": 3
  },
  {
    "slug": "lb-nagar",
    "name": "L.B. Nagar",
    "zone": "east-hyderabad",
    "sortOrder": 187,
    "priorityTier": 1
  },
  {
    "slug": "lakdikapul",
    "name": "Lakdikapul",
    "zone": "west-hyderabad",
    "sortOrder": 188,
    "priorityTier": 3
  },
  {
    "slug": "lalapet",
    "name": "Lalapet",
    "zone": "west-hyderabad",
    "sortOrder": 189,
    "priorityTier": 3
  },
  {
    "slug": "lallaguda",
    "name": "Lallaguda",
    "zone": "west-hyderabad",
    "sortOrder": 190,
    "priorityTier": 3
  },
  {
    "slug": "langar-houz",
    "name": "Langar Houz",
    "zone": "west-hyderabad",
    "sortOrder": 191,
    "priorityTier": 2
  },
  {
    "slug": "lingampally",
    "name": "Lingampally",
    "zone": "west-hyderabad",
    "sortOrder": 192,
    "priorityTier": 3
  },
  {
    "slug": "lower-tank-bund",
    "name": "Lower Tank Bund",
    "zone": "west-hyderabad",
    "sortOrder": 193,
    "priorityTier": 3
  },
  {
    "slug": "madhapur",
    "name": "Madhapur",
    "zone": "west-hyderabad",
    "sortOrder": 194,
    "priorityTier": 1
  },
  {
    "slug": "madinaguda",
    "name": "Madinaguda",
    "zone": "west-hyderabad",
    "sortOrder": 195,
    "priorityTier": 3
  },
  {
    "slug": "mahendra-hills",
    "name": "Mahendra Hills",
    "zone": "west-hyderabad",
    "sortOrder": 196,
    "priorityTier": 3
  },
  {
    "slug": "maheshwaram",
    "name": "Maheshwaram",
    "zone": "west-hyderabad",
    "sortOrder": 197,
    "priorityTier": 3
  },
  {
    "slug": "mailardevpally",
    "name": "Mailardevpally",
    "zone": "west-hyderabad",
    "sortOrder": 198,
    "priorityTier": 3
  },
  {
    "slug": "malakpet",
    "name": "Malakpet",
    "zone": "old-city",
    "sortOrder": 199,
    "priorityTier": 3
  },
  {
    "slug": "malkajgiri",
    "name": "Malkajgiri",
    "zone": "secunderabad",
    "sortOrder": 200,
    "priorityTier": 1
  },
  {
    "slug": "mallampet",
    "name": "Mallampet",
    "zone": "west-hyderabad",
    "sortOrder": 201,
    "priorityTier": 3
  },
  {
    "slug": "mallapur",
    "name": "Mallapur",
    "zone": "west-hyderabad",
    "sortOrder": 202,
    "priorityTier": 3
  },
  {
    "slug": "mallepally",
    "name": "Mallepally",
    "zone": "west-hyderabad",
    "sortOrder": 203,
    "priorityTier": 3
  },
  {
    "slug": "mamidipally",
    "name": "Mamidipally",
    "zone": "west-hyderabad",
    "sortOrder": 204,
    "priorityTier": 3
  },
  {
    "slug": "mangalhat",
    "name": "Mangalhat",
    "zone": "west-hyderabad",
    "sortOrder": 205,
    "priorityTier": 3
  },
  {
    "slug": "manikonda",
    "name": "Manikonda",
    "zone": "west-hyderabad",
    "sortOrder": 206,
    "priorityTier": 1
  },
  {
    "slug": "mansoorabad",
    "name": "Mansoorabad",
    "zone": "west-hyderabad",
    "sortOrder": 207,
    "priorityTier": 3
  },
  {
    "slug": "marredpally",
    "name": "Marredpally",
    "zone": "west-hyderabad",
    "sortOrder": 208,
    "priorityTier": 3
  },
  {
    "slug": "masab-tank",
    "name": "Masab Tank",
    "zone": "central-hyderabad",
    "sortOrder": 209,
    "priorityTier": 2
  },
  {
    "slug": "masjid-banda",
    "name": "Masjid Banda",
    "zone": "west-hyderabad",
    "sortOrder": 210,
    "priorityTier": 3
  },
  {
    "slug": "medchal",
    "name": "Medchal",
    "zone": "north-hyderabad",
    "sortOrder": 211,
    "priorityTier": 2
  },
  {
    "slug": "medipally",
    "name": "Medipally",
    "zone": "west-hyderabad",
    "sortOrder": 212,
    "priorityTier": 3
  },
  {
    "slug": "meerpet",
    "name": "Meerpet",
    "zone": "west-hyderabad",
    "sortOrder": 213,
    "priorityTier": 3
  },
  {
    "slug": "mehdipatnam",
    "name": "Mehdipatnam",
    "zone": "west-hyderabad",
    "sortOrder": 214,
    "priorityTier": 1
  },
  {
    "slug": "mettuguda",
    "name": "Mettuguda",
    "zone": "west-hyderabad",
    "sortOrder": 215,
    "priorityTier": 3
  },
  {
    "slug": "mg-road",
    "name": "Mg Road",
    "zone": "west-hyderabad",
    "sortOrder": 216,
    "priorityTier": 3
  },
  {
    "slug": "miyapur",
    "name": "Miyapur",
    "zone": "west-hyderabad",
    "sortOrder": 217,
    "priorityTier": 1
  },
  {
    "slug": "moghalpura",
    "name": "Moghalpura",
    "zone": "west-hyderabad",
    "sortOrder": 218,
    "priorityTier": 3
  },
  {
    "slug": "moinabad",
    "name": "Moinabad",
    "zone": "west-hyderabad",
    "sortOrder": 219,
    "priorityTier": 3
  },
  {
    "slug": "moosapet",
    "name": "Moosapet",
    "zone": "west-hyderabad",
    "sortOrder": 220,
    "priorityTier": 2
  },
  {
    "slug": "moosarambagh",
    "name": "Moosarambagh",
    "zone": "west-hyderabad",
    "sortOrder": 221,
    "priorityTier": 3
  },
  {
    "slug": "moula-ali",
    "name": "Moula Ali",
    "zone": "west-hyderabad",
    "sortOrder": 222,
    "priorityTier": 3
  },
  {
    "slug": "muchintal",
    "name": "Muchintal",
    "zone": "west-hyderabad",
    "sortOrder": 223,
    "priorityTier": 3
  },
  {
    "slug": "mughalpura",
    "name": "Mughalpura",
    "zone": "west-hyderabad",
    "sortOrder": 224,
    "priorityTier": 3
  },
  {
    "slug": "musheerabad",
    "name": "Musheerabad",
    "zone": "west-hyderabad",
    "sortOrder": 225,
    "priorityTier": 3
  },
  {
    "slug": "muthangi",
    "name": "Muthangi",
    "zone": "west-hyderabad",
    "sortOrder": 226,
    "priorityTier": 3
  },
  {
    "slug": "nacharam",
    "name": "Nacharam",
    "zone": "west-hyderabad",
    "sortOrder": 227,
    "priorityTier": 3
  },
  {
    "slug": "nadergul",
    "name": "Nadergul",
    "zone": "west-hyderabad",
    "sortOrder": 228,
    "priorityTier": 3
  },
  {
    "slug": "nagaram",
    "name": "Nagaram",
    "zone": "west-hyderabad",
    "sortOrder": 229,
    "priorityTier": 3
  },
  {
    "slug": "nagole",
    "name": "Nagole",
    "zone": "east-hyderabad",
    "sortOrder": 230,
    "priorityTier": 1
  },
  {
    "slug": "nallagandla",
    "name": "Nallagandla",
    "zone": "west-hyderabad",
    "sortOrder": 231,
    "priorityTier": 1
  },
  {
    "slug": "nallakunta",
    "name": "Nallakunta",
    "zone": "west-hyderabad",
    "sortOrder": 232,
    "priorityTier": 3
  },
  {
    "slug": "nampally",
    "name": "Nampally",
    "zone": "west-hyderabad",
    "sortOrder": 233,
    "priorityTier": 3
  },
  {
    "slug": "nanakramguda",
    "name": "Nanakramguda",
    "zone": "west-hyderabad",
    "sortOrder": 234,
    "priorityTier": 1
  },
  {
    "slug": "nanal-nagar",
    "name": "Nanal Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 235,
    "priorityTier": 3
  },
  {
    "slug": "nandigama",
    "name": "Nandigama",
    "zone": "west-hyderabad",
    "sortOrder": 236,
    "priorityTier": 3
  },
  {
    "slug": "narapally",
    "name": "Narapally",
    "zone": "west-hyderabad",
    "sortOrder": 237,
    "priorityTier": 3
  },
  {
    "slug": "narayanaguda",
    "name": "Narayanaguda",
    "zone": "west-hyderabad",
    "sortOrder": 238,
    "priorityTier": 3
  },
  {
    "slug": "narsingi",
    "name": "Narsingi",
    "zone": "west-hyderabad",
    "sortOrder": 239,
    "priorityTier": 1
  },
  {
    "slug": "nawab-saheb-kunta",
    "name": "Nawab Saheb Kunta",
    "zone": "west-hyderabad",
    "sortOrder": 240,
    "priorityTier": 3
  },
  {
    "slug": "necklace-road",
    "name": "Necklace Road",
    "zone": "west-hyderabad",
    "sortOrder": 241,
    "priorityTier": 3
  },
  {
    "slug": "neknampur",
    "name": "Neknampur",
    "zone": "west-hyderabad",
    "sortOrder": 242,
    "priorityTier": 3
  },
  {
    "slug": "neopolis",
    "name": "Neopolis",
    "zone": "west-hyderabad",
    "sortOrder": 243,
    "priorityTier": 3
  },
  {
    "slug": "neredmet",
    "name": "Neredmet",
    "zone": "west-hyderabad",
    "sortOrder": 244,
    "priorityTier": 3
  },
  {
    "slug": "new-bowenpally",
    "name": "New Bowenpally",
    "zone": "north-hyderabad",
    "sortOrder": 245,
    "priorityTier": 3
  },
  {
    "slug": "new-malakpet",
    "name": "New Malakpet",
    "zone": "west-hyderabad",
    "sortOrder": 246,
    "priorityTier": 3
  },
  {
    "slug": "nizampet",
    "name": "Nizampet",
    "zone": "west-hyderabad",
    "sortOrder": 247,
    "priorityTier": 1
  },
  {
    "slug": "noor-khan-bazaar",
    "name": "Noor Khan Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 248,
    "priorityTier": 3
  },
  {
    "slug": "old-alwal",
    "name": "Old Alwal",
    "zone": "west-hyderabad",
    "sortOrder": 249,
    "priorityTier": 3
  },
  {
    "slug": "old-bowenpally",
    "name": "Old Bowenpally",
    "zone": "north-hyderabad",
    "sortOrder": 250,
    "priorityTier": 3
  },
  {
    "slug": "old-city",
    "name": "Old City",
    "zone": "old-city",
    "sortOrder": 251,
    "priorityTier": 3
  },
  {
    "slug": "osman-nagar",
    "name": "Osman Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 252,
    "priorityTier": 3
  },
  {
    "slug": "osmania-university",
    "name": "Osmania University",
    "zone": "west-hyderabad",
    "sortOrder": 253,
    "priorityTier": 3
  },
  {
    "slug": "padmarao-nagar",
    "name": "Padmarao Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 254,
    "priorityTier": 3
  },
  {
    "slug": "pahadi-shareef",
    "name": "Pahadi Shareef",
    "zone": "west-hyderabad",
    "sortOrder": 255,
    "priorityTier": 3
  },
  {
    "slug": "pan-mandi",
    "name": "Pan Mandi",
    "zone": "west-hyderabad",
    "sortOrder": 256,
    "priorityTier": 3
  },
  {
    "slug": "panjagutta",
    "name": "Panjagutta",
    "zone": "central-hyderabad",
    "sortOrder": 257,
    "priorityTier": 2
  },
  {
    "slug": "paradise",
    "name": "Paradise",
    "zone": "west-hyderabad",
    "sortOrder": 258,
    "priorityTier": 3
  },
  {
    "slug": "parsigutta",
    "name": "Parsigutta",
    "zone": "west-hyderabad",
    "sortOrder": 259,
    "priorityTier": 3
  },
  {
    "slug": "patancheru",
    "name": "Patancheru",
    "zone": "outer-hyderabad",
    "sortOrder": 260,
    "priorityTier": 2
  },
  {
    "slug": "pathergatti",
    "name": "Pathergatti",
    "zone": "west-hyderabad",
    "sortOrder": 261,
    "priorityTier": 3
  },
  {
    "slug": "patighanpur",
    "name": "Patighanpur",
    "zone": "west-hyderabad",
    "sortOrder": 262,
    "priorityTier": 3
  },
  {
    "slug": "patny",
    "name": "Patny",
    "zone": "west-hyderabad",
    "sortOrder": 263,
    "priorityTier": 3
  },
  {
    "slug": "pedda-amberpet",
    "name": "Pedda Amberpet",
    "zone": "west-hyderabad",
    "sortOrder": 264,
    "priorityTier": 3
  },
  {
    "slug": "peerancheru",
    "name": "Peerancheru",
    "zone": "west-hyderabad",
    "sortOrder": 265,
    "priorityTier": 3
  },
  {
    "slug": "peerzadiguda",
    "name": "Peerzadiguda",
    "zone": "west-hyderabad",
    "sortOrder": 266,
    "priorityTier": 2
  },
  {
    "slug": "pet-basheerabad",
    "name": "Pet Basheerabad",
    "zone": "west-hyderabad",
    "sortOrder": 267,
    "priorityTier": 3
  },
  {
    "slug": "petlaburj",
    "name": "Petlaburj",
    "zone": "west-hyderabad",
    "sortOrder": 268,
    "priorityTier": 3
  },
  {
    "slug": "picket",
    "name": "Picket",
    "zone": "west-hyderabad",
    "sortOrder": 269,
    "priorityTier": 3
  },
  {
    "slug": "pocharam",
    "name": "Pocharam",
    "zone": "west-hyderabad",
    "sortOrder": 270,
    "priorityTier": 3
  },
  {
    "slug": "pragathi-nagar",
    "name": "Pragathi Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 271,
    "priorityTier": 3
  },
  {
    "slug": "prakash-nagar",
    "name": "Prakash Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 272,
    "priorityTier": 3
  },
  {
    "slug": "puppalaguda",
    "name": "Puppalaguda",
    "zone": "west-hyderabad",
    "sortOrder": 273,
    "priorityTier": 3
  },
  {
    "slug": "puranapul",
    "name": "Puranapul",
    "zone": "west-hyderabad",
    "sortOrder": 274,
    "priorityTier": 3
  },
  {
    "slug": "purani-haveli",
    "name": "Purani Haveli",
    "zone": "west-hyderabad",
    "sortOrder": 275,
    "priorityTier": 3
  },
  {
    "slug": "quthbullapur",
    "name": "Quthbullapur",
    "zone": "north-hyderabad",
    "sortOrder": 276,
    "priorityTier": 3
  },
  {
    "slug": "raidurg",
    "name": "Raidurg",
    "zone": "west-hyderabad",
    "sortOrder": 277,
    "priorityTier": 3
  },
  {
    "slug": "raj-bhavan-road",
    "name": "Raj Bhavan Road",
    "zone": "west-hyderabad",
    "sortOrder": 278,
    "priorityTier": 3
  },
  {
    "slug": "rajendranagar",
    "name": "Rajendranagar",
    "zone": "west-hyderabad",
    "sortOrder": 279,
    "priorityTier": 3
  },
  {
    "slug": "ramachandrapuram",
    "name": "Ramachandrapuram",
    "zone": "west-hyderabad",
    "sortOrder": 280,
    "priorityTier": 3
  },
  {
    "slug": "ramanthapur",
    "name": "Ramanthapur",
    "zone": "west-hyderabad",
    "sortOrder": 281,
    "priorityTier": 3
  },
  {
    "slug": "ramnagar",
    "name": "Ramnagar",
    "zone": "west-hyderabad",
    "sortOrder": 282,
    "priorityTier": 3
  },
  {
    "slug": "rampally",
    "name": "Rampally",
    "zone": "west-hyderabad",
    "sortOrder": 283,
    "priorityTier": 3
  },
  {
    "slug": "ranigunj",
    "name": "Ranigunj",
    "zone": "west-hyderabad",
    "sortOrder": 284,
    "priorityTier": 3
  },
  {
    "slug": "rasoolpura",
    "name": "Rasoolpura",
    "zone": "west-hyderabad",
    "sortOrder": 285,
    "priorityTier": 3
  },
  {
    "slug": "red-hills",
    "name": "Red Hills",
    "zone": "west-hyderabad",
    "sortOrder": 286,
    "priorityTier": 3
  },
  {
    "slug": "rein-bazaar",
    "name": "Rein Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 287,
    "priorityTier": 3
  },
  {
    "slug": "riyasat-nagar",
    "name": "Riyasat Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 288,
    "priorityTier": 3
  },
  {
    "slug": "rtc-cross-roads",
    "name": "Rtc Cross Roads",
    "zone": "west-hyderabad",
    "sortOrder": 289,
    "priorityTier": 3
  },
  {
    "slug": "rudraram",
    "name": "Rudraram",
    "zone": "west-hyderabad",
    "sortOrder": 290,
    "priorityTier": 3
  },
  {
    "slug": "s-d-road",
    "name": "S.D. Road",
    "zone": "west-hyderabad",
    "sortOrder": 291,
    "priorityTier": 3
  },
  {
    "slug": "s-r-nagar",
    "name": "S.R. Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 292,
    "priorityTier": 3
  },
  {
    "slug": "safilguda",
    "name": "Safilguda",
    "zone": "west-hyderabad",
    "sortOrder": 293,
    "priorityTier": 3
  },
  {
    "slug": "saidabad",
    "name": "Saidabad",
    "zone": "west-hyderabad",
    "sortOrder": 294,
    "priorityTier": 3
  },
  {
    "slug": "saifabad",
    "name": "Saifabad",
    "zone": "west-hyderabad",
    "sortOrder": 295,
    "priorityTier": 3
  },
  {
    "slug": "sainikpuri",
    "name": "Sainikpuri",
    "zone": "secunderabad",
    "sortOrder": 296,
    "priorityTier": 1
  },
  {
    "slug": "saleem-nagar",
    "name": "Saleem Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 297,
    "priorityTier": 3
  },
  {
    "slug": "sanath-nagar",
    "name": "Sanath Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 298,
    "priorityTier": 3
  },
  {
    "slug": "santosh-nagar",
    "name": "Santoshnagar",
    "zone": "west-hyderabad",
    "sortOrder": 299,
    "priorityTier": 3
  },
  {
    "slug": "saroornagar",
    "name": "Saroornagar",
    "zone": "east-hyderabad",
    "sortOrder": 300,
    "priorityTier": 3
  },
  {
    "slug": "satamrai",
    "name": "Satamrai",
    "zone": "west-hyderabad",
    "sortOrder": 301,
    "priorityTier": 3
  },
  {
    "slug": "secunderabad",
    "name": "Secunderabad",
    "zone": "secunderabad",
    "sortOrder": 302,
    "priorityTier": 1
  },
  {
    "slug": "seven-tombs",
    "name": "Seven Tombs",
    "zone": "west-hyderabad",
    "sortOrder": 303,
    "priorityTier": 3
  },
  {
    "slug": "shadnagar",
    "name": "Shadnagar",
    "zone": "outer-hyderabad",
    "sortOrder": 304,
    "priorityTier": 3
  },
  {
    "slug": "shah-ali-banda",
    "name": "Shah Ali Banda",
    "zone": "west-hyderabad",
    "sortOrder": 305,
    "priorityTier": 3
  },
  {
    "slug": "shaikpet",
    "name": "Shaikpet",
    "zone": "central-hyderabad",
    "sortOrder": 306,
    "priorityTier": 2
  },
  {
    "slug": "shamirpet",
    "name": "Shamirpet",
    "zone": "west-hyderabad",
    "sortOrder": 307,
    "priorityTier": 3
  },
  {
    "slug": "shamshabad",
    "name": "Shamshabad",
    "zone": "outer-hyderabad",
    "sortOrder": 308,
    "priorityTier": 2
  },
  {
    "slug": "shankarpally",
    "name": "Shankarpally",
    "zone": "west-hyderabad",
    "sortOrder": 309,
    "priorityTier": 3
  },
  {
    "slug": "shapur-nagar",
    "name": "Shapur Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 310,
    "priorityTier": 3
  },
  {
    "slug": "shivrampally",
    "name": "Shivrampally",
    "zone": "west-hyderabad",
    "sortOrder": 311,
    "priorityTier": 3
  },
  {
    "slug": "siddiamber-bazaar",
    "name": "Siddiamber Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 312,
    "priorityTier": 3
  },
  {
    "slug": "sikh-village",
    "name": "Sikh Village",
    "zone": "west-hyderabad",
    "sortOrder": 313,
    "priorityTier": 3
  },
  {
    "slug": "sitaphalmandi",
    "name": "Sitaphalmandi",
    "zone": "west-hyderabad",
    "sortOrder": 314,
    "priorityTier": 3
  },
  {
    "slug": "somajiguda",
    "name": "Somajiguda",
    "zone": "central-hyderabad",
    "sortOrder": 315,
    "priorityTier": 1
  },
  {
    "slug": "sri-nagar-colony",
    "name": "Sri Nagar Colony",
    "zone": "west-hyderabad",
    "sortOrder": 316,
    "priorityTier": 3
  },
  {
    "slug": "subhash-nagar",
    "name": "Subhash Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 317,
    "priorityTier": 3
  },
  {
    "slug": "suchitra",
    "name": "Suchitra",
    "zone": "north-hyderabad",
    "sortOrder": 318,
    "priorityTier": 3
  },
  {
    "slug": "sultan-bazaar",
    "name": "Sultan Bazaar",
    "zone": "west-hyderabad",
    "sortOrder": 319,
    "priorityTier": 3
  },
  {
    "slug": "sun-city",
    "name": "Sun City",
    "zone": "west-hyderabad",
    "sortOrder": 320,
    "priorityTier": 3
  },
  {
    "slug": "suraram",
    "name": "Suraram",
    "zone": "west-hyderabad",
    "sortOrder": 321,
    "priorityTier": 3
  },
  {
    "slug": "tadban",
    "name": "Tadban",
    "zone": "west-hyderabad",
    "sortOrder": 322,
    "priorityTier": 3
  },
  {
    "slug": "tadbund",
    "name": "Tadbund",
    "zone": "west-hyderabad",
    "sortOrder": 323,
    "priorityTier": 3
  },
  {
    "slug": "talab-katta",
    "name": "Talab Katta",
    "zone": "west-hyderabad",
    "sortOrder": 324,
    "priorityTier": 3
  },
  {
    "slug": "tappachabutra",
    "name": "Tappachabutra",
    "zone": "west-hyderabad",
    "sortOrder": 325,
    "priorityTier": 3
  },
  {
    "slug": "tarnaka",
    "name": "Tarnaka",
    "zone": "secunderabad",
    "sortOrder": 326,
    "priorityTier": 1
  },
  {
    "slug": "tellapur",
    "name": "Tellapur",
    "zone": "west-hyderabad",
    "sortOrder": 327,
    "priorityTier": 1
  },
  {
    "slug": "theatre-road",
    "name": "Theatre Road",
    "zone": "west-hyderabad",
    "sortOrder": 328,
    "priorityTier": 3
  },
  {
    "slug": "thumkunta",
    "name": "Thumkunta",
    "zone": "west-hyderabad",
    "sortOrder": 329,
    "priorityTier": 3
  },
  {
    "slug": "tilak-nagar",
    "name": "Tilak Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 330,
    "priorityTier": 3
  },
  {
    "slug": "tolichowki",
    "name": "Tolichowki",
    "zone": "west-hyderabad",
    "sortOrder": 331,
    "priorityTier": 3
  },
  {
    "slug": "trimulgherry",
    "name": "Trimulgherry",
    "zone": "secunderabad",
    "sortOrder": 332,
    "priorityTier": 3
  },
  {
    "slug": "tukkuguda",
    "name": "Tukkuguda",
    "zone": "west-hyderabad",
    "sortOrder": 333,
    "priorityTier": 3
  },
  {
    "slug": "turkayamjal",
    "name": "Turkayamjal",
    "zone": "west-hyderabad",
    "sortOrder": 334,
    "priorityTier": 3
  },
  {
    "slug": "uppal",
    "name": "Uppal",
    "zone": "east-hyderabad",
    "sortOrder": 335,
    "priorityTier": 1
  },
  {
    "slug": "uppal-bhagat",
    "name": "Uppal Bhagat",
    "zone": "west-hyderabad",
    "sortOrder": 336,
    "priorityTier": 3
  },
  {
    "slug": "uppuguda",
    "name": "Uppuguda",
    "zone": "west-hyderabad",
    "sortOrder": 337,
    "priorityTier": 3
  },
  {
    "slug": "vanasthalipuram",
    "name": "Vanasthalipuram",
    "zone": "east-hyderabad",
    "sortOrder": 338,
    "priorityTier": 1
  },
  {
    "slug": "velimela",
    "name": "Velimela",
    "zone": "west-hyderabad",
    "sortOrder": 339,
    "priorityTier": 3
  },
  {
    "slug": "vengal-rao-nagar",
    "name": "Vengal Rao Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 340,
    "priorityTier": 3
  },
  {
    "slug": "vidyanagar",
    "name": "Vidyanagar",
    "zone": "west-hyderabad",
    "sortOrder": 341,
    "priorityTier": 3
  },
  {
    "slug": "vijayanagar-colony",
    "name": "Vijayanagar Colony",
    "zone": "west-hyderabad",
    "sortOrder": 342,
    "priorityTier": 3
  },
  {
    "slug": "vivekananda-nagar",
    "name": "Vivekananda Nagar",
    "zone": "west-hyderabad",
    "sortOrder": 343,
    "priorityTier": 3
  },
  {
    "slug": "west-marredpally",
    "name": "West Marredpally",
    "zone": "west-hyderabad",
    "sortOrder": 344,
    "priorityTier": 3
  },
  {
    "slug": "whitefields",
    "name": "Whitefields",
    "zone": "west-hyderabad",
    "sortOrder": 345,
    "priorityTier": 3
  },
  {
    "slug": "yakutpura",
    "name": "Yakutpura",
    "zone": "old-city",
    "sortOrder": 346,
    "priorityTier": 3
  },
  {
    "slug": "yapral",
    "name": "Yapral",
    "zone": "west-hyderabad",
    "sortOrder": 347,
    "priorityTier": 3
  },
  {
    "slug": "yellareddyguda",
    "name": "Yellareddyguda",
    "zone": "west-hyderabad",
    "sortOrder": 348,
    "priorityTier": 3
  },
  {
    "slug": "yousufguda",
    "name": "Yousufguda",
    "zone": "west-hyderabad",
    "sortOrder": 349,
    "priorityTier": 3
  },
  {
    "slug": "zamistanpur",
    "name": "Zamistanpur",
    "zone": "west-hyderabad",
    "sortOrder": 350,
    "priorityTier": 3
  },
  {
    "slug": "ziaguda",
    "name": "Ziaguda",
    "zone": "west-hyderabad",
    "sortOrder": 351,
    "priorityTier": 3
  }
];

export const HYDERABAD_AREA_COUNT = 351;

export function getHyderabadAreaBySlug(slug: string): HyderabadArea | undefined {
  return HYDERABAD_AREAS.find((a) => a.slug === slug);
}
