/** Auto-generated by scripts/generate-kochi-areas.ts — do not edit by hand */
export type AreaPriorityTier = 1 | 2 | 3;

export interface KochiArea {
  slug: string;
  name: string;
  zone: string;
  sortOrder: number;
  priorityTier: AreaPriorityTier;
}

export const KOCHI_AREAS: KochiArea[] = [
  {
    "slug": "abad-nucleus-mall-area",
    "name": "Abad Nucleus Mall Area",
    "zone": "ernakulam-central",
    "sortOrder": 1,
    "priorityTier": 3
  },
  {
    "slug": "airport-junction-athani",
    "name": "Airport Junction Athani",
    "zone": "ernakulam-central",
    "sortOrder": 2,
    "priorityTier": 3
  },
  {
    "slug": "akaparambu",
    "name": "Akaparambu",
    "zone": "ernakulam-central",
    "sortOrder": 3,
    "priorityTier": 3
  },
  {
    "slug": "alangad",
    "name": "Alangad",
    "zone": "ernakulam-central",
    "sortOrder": 4,
    "priorityTier": 3
  },
  {
    "slug": "alangad-junction",
    "name": "Alangad Junction",
    "zone": "ernakulam-central",
    "sortOrder": 5,
    "priorityTier": 3
  },
  {
    "slug": "alinchuvadu",
    "name": "Alinchuvadu",
    "zone": "ernakulam-central",
    "sortOrder": 6,
    "priorityTier": 3
  },
  {
    "slug": "allapra",
    "name": "Allapra",
    "zone": "ernakulam-central",
    "sortOrder": 7,
    "priorityTier": 3
  },
  {
    "slug": "aluva",
    "name": "Aluva",
    "zone": "aluva",
    "sortOrder": 8,
    "priorityTier": 1
  },
  {
    "slug": "aluva-east",
    "name": "Aluva East",
    "zone": "aluva",
    "sortOrder": 9,
    "priorityTier": 3
  },
  {
    "slug": "aluva-market",
    "name": "Aluva Market",
    "zone": "aluva",
    "sortOrder": 10,
    "priorityTier": 3
  },
  {
    "slug": "aluva-metro-station-area",
    "name": "Aluva Metro Station Area",
    "zone": "aluva",
    "sortOrder": 11,
    "priorityTier": 3
  },
  {
    "slug": "aluva-railway-station-area",
    "name": "Aluva Railway Station Area",
    "zone": "aluva",
    "sortOrder": 12,
    "priorityTier": 3
  },
  {
    "slug": "aluva-west",
    "name": "Aluva West",
    "zone": "aluva",
    "sortOrder": 13,
    "priorityTier": 3
  },
  {
    "slug": "amaravathi-fort-kochi",
    "name": "Amaravathi Fort Kochi",
    "zone": "fort-kochi",
    "sortOrder": 14,
    "priorityTier": 3
  },
  {
    "slug": "amaravathy",
    "name": "Amaravathy",
    "zone": "ernakulam-central",
    "sortOrder": 15,
    "priorityTier": 3
  },
  {
    "slug": "ambalamedu",
    "name": "Ambalamedu",
    "zone": "ernakulam-central",
    "sortOrder": 16,
    "priorityTier": 3
  },
  {
    "slug": "ambelipadam",
    "name": "Ambelipadam",
    "zone": "ernakulam-central",
    "sortOrder": 17,
    "priorityTier": 3
  },
  {
    "slug": "amrita-hospital-area",
    "name": "Amrita Hospital Area",
    "zone": "ernakulam-central",
    "sortOrder": 18,
    "priorityTier": 3
  },
  {
    "slug": "anchumana",
    "name": "Anchumana",
    "zone": "ernakulam-central",
    "sortOrder": 19,
    "priorityTier": 3
  },
  {
    "slug": "andikkadavu",
    "name": "Andikkadavu",
    "zone": "ernakulam-central",
    "sortOrder": 20,
    "priorityTier": 3
  },
  {
    "slug": "angamaly",
    "name": "Angamaly",
    "zone": "angamaly",
    "sortOrder": 21,
    "priorityTier": 2
  },
  {
    "slug": "angamaly-airport-road",
    "name": "Angamaly Airport Road",
    "zone": "angamaly",
    "sortOrder": 22,
    "priorityTier": 3
  },
  {
    "slug": "angamaly-railway-station-area",
    "name": "Angamaly Railway Station Area",
    "zone": "angamaly",
    "sortOrder": 23,
    "priorityTier": 3
  },
  {
    "slug": "angamaly-south",
    "name": "Angamaly South",
    "zone": "angamaly",
    "sortOrder": 24,
    "priorityTier": 3
  },
  {
    "slug": "arayankavu",
    "name": "Arayankavu",
    "zone": "ernakulam-central",
    "sortOrder": 25,
    "priorityTier": 3
  },
  {
    "slug": "arookutty",
    "name": "Arookutty",
    "zone": "ernakulam-central",
    "sortOrder": 26,
    "priorityTier": 3
  },
  {
    "slug": "aroor",
    "name": "Aroor",
    "zone": "ernakulam-central",
    "sortOrder": 27,
    "priorityTier": 3
  },
  {
    "slug": "aroor-ferry",
    "name": "Aroor Ferry",
    "zone": "ernakulam-central",
    "sortOrder": 28,
    "priorityTier": 3
  },
  {
    "slug": "asamannoor",
    "name": "Asamannoor",
    "zone": "ernakulam-central",
    "sortOrder": 29,
    "priorityTier": 3
  },
  {
    "slug": "athani-kakkanad",
    "name": "Athani Kakkanad",
    "zone": "kakkanad-infopark",
    "sortOrder": 30,
    "priorityTier": 1
  },
  {
    "slug": "athani-nedumbassery",
    "name": "Athani Nedumbassery",
    "zone": "angamaly",
    "sortOrder": 31,
    "priorityTier": 3
  },
  {
    "slug": "atlantis-junction",
    "name": "Atlantis Junction",
    "zone": "ernakulam-central",
    "sortOrder": 32,
    "priorityTier": 3
  },
  {
    "slug": "atlantis-kochi",
    "name": "Atlantis Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 33,
    "priorityTier": 3
  },
  {
    "slug": "ayyappankavu",
    "name": "Ayyappankavu",
    "zone": "ernakulam-central",
    "sortOrder": 34,
    "priorityTier": 3
  },
  {
    "slug": "azad-road",
    "name": "Azad Road",
    "zone": "ernakulam-central",
    "sortOrder": 35,
    "priorityTier": 3
  },
  {
    "slug": "azheekal-vypin",
    "name": "Azheekal Vypin",
    "zone": "fort-kochi",
    "sortOrder": 36,
    "priorityTier": 3
  },
  {
    "slug": "banerji-road",
    "name": "Banerji Road",
    "zone": "ernakulam-central",
    "sortOrder": 37,
    "priorityTier": 3
  },
  {
    "slug": "bank-junction-aluva",
    "name": "Bank Junction Aluva",
    "zone": "aluva",
    "sortOrder": 38,
    "priorityTier": 3
  },
  {
    "slug": "bazar-road-mattancherry",
    "name": "Bazar Road Mattancherry",
    "zone": "fort-kochi",
    "sortOrder": 39,
    "priorityTier": 3
  },
  {
    "slug": "bharath-matha-college-area",
    "name": "Bharath Matha College Area",
    "zone": "ernakulam-central",
    "sortOrder": 40,
    "priorityTier": 3
  },
  {
    "slug": "binanipuram",
    "name": "Binanipuram",
    "zone": "ernakulam-central",
    "sortOrder": 41,
    "priorityTier": 3
  },
  {
    "slug": "bolgatty",
    "name": "Bolgatty",
    "zone": "ernakulam-central",
    "sortOrder": 42,
    "priorityTier": 3
  },
  {
    "slug": "bolgatty-island",
    "name": "Bolgatty Island",
    "zone": "ernakulam-central",
    "sortOrder": 43,
    "priorityTier": 3
  },
  {
    "slug": "brahmapuram",
    "name": "Brahmapuram",
    "zone": "ernakulam-central",
    "sortOrder": 44,
    "priorityTier": 3
  },
  {
    "slug": "broadway-kochi",
    "name": "Broadway Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 45,
    "priorityTier": 3
  },
  {
    "slug": "bts-road-edappally",
    "name": "BTS Road Edappally",
    "zone": "edappally",
    "sortOrder": 46,
    "priorityTier": 3
  },
  {
    "slug": "calvathy",
    "name": "Calvathy",
    "zone": "ernakulam-central",
    "sortOrder": 47,
    "priorityTier": 3
  },
  {
    "slug": "cemetery-junction",
    "name": "Cemetery Junction",
    "zone": "ernakulam-central",
    "sortOrder": 48,
    "priorityTier": 3
  },
  {
    "slug": "ch-kannamaly",
    "name": "Ch Kannamaly",
    "zone": "ernakulam-central",
    "sortOrder": 49,
    "priorityTier": 3
  },
  {
    "slug": "chakkalakkal",
    "name": "Chakkalakkal",
    "zone": "ernakulam-central",
    "sortOrder": 50,
    "priorityTier": 3
  },
  {
    "slug": "chakkamadam",
    "name": "Chakkamadam",
    "zone": "ernakulam-central",
    "sortOrder": 51,
    "priorityTier": 3
  },
  {
    "slug": "chakkarakkal-tripunithura",
    "name": "Chakkarakkal Tripunithura",
    "zone": "vyttila",
    "sortOrder": 52,
    "priorityTier": 3
  },
  {
    "slug": "chakkaraparambu",
    "name": "Chakkaraparambu",
    "zone": "ernakulam-central",
    "sortOrder": 53,
    "priorityTier": 3
  },
  {
    "slug": "chalikkavattom",
    "name": "Chalikkavattom",
    "zone": "ernakulam-central",
    "sortOrder": 54,
    "priorityTier": 3
  },
  {
    "slug": "chalikkavattom-junction",
    "name": "Chalikkavattom Junction",
    "zone": "ernakulam-central",
    "sortOrder": 55,
    "priorityTier": 3
  },
  {
    "slug": "chambakkara",
    "name": "Chambakkara",
    "zone": "ernakulam-central",
    "sortOrder": 56,
    "priorityTier": 3
  },
  {
    "slug": "chambakkara-market",
    "name": "Chambakkara Market",
    "zone": "ernakulam-central",
    "sortOrder": 57,
    "priorityTier": 3
  },
  {
    "slug": "champakkara-maradu",
    "name": "Champakkara Maradu",
    "zone": "vyttila",
    "sortOrder": 58,
    "priorityTier": 3
  },
  {
    "slug": "chandiroor",
    "name": "Chandiroor",
    "zone": "ernakulam-central",
    "sortOrder": 59,
    "priorityTier": 3
  },
  {
    "slug": "changampuzha-nagar",
    "name": "Changampuzha Nagar",
    "zone": "ernakulam-central",
    "sortOrder": 60,
    "priorityTier": 3
  },
  {
    "slug": "changampuzha-park",
    "name": "Changampuzha Park",
    "zone": "ernakulam-central",
    "sortOrder": 61,
    "priorityTier": 3
  },
  {
    "slug": "chathari",
    "name": "Chathari",
    "zone": "ernakulam-central",
    "sortOrder": 62,
    "priorityTier": 3
  },
  {
    "slug": "chelamattom",
    "name": "Chelamattom",
    "zone": "ernakulam-central",
    "sortOrder": 63,
    "priorityTier": 3
  },
  {
    "slug": "chellanam",
    "name": "Chellanam",
    "zone": "ernakulam-central",
    "sortOrder": 64,
    "priorityTier": 3
  },
  {
    "slug": "chembumukku",
    "name": "Chembumukku",
    "zone": "ernakulam-central",
    "sortOrder": 65,
    "priorityTier": 3
  },
  {
    "slug": "chendamangalam",
    "name": "Chendamangalam",
    "zone": "ernakulam-central",
    "sortOrder": 66,
    "priorityTier": 3
  },
  {
    "slug": "chendamangalam-junction",
    "name": "Chendamangalam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 67,
    "priorityTier": 3
  },
  {
    "slug": "chengamanad",
    "name": "Chengamanad",
    "zone": "ernakulam-central",
    "sortOrder": 68,
    "priorityTier": 3
  },
  {
    "slug": "cherai",
    "name": "Cherai",
    "zone": "ernakulam-central",
    "sortOrder": 69,
    "priorityTier": 2
  },
  {
    "slug": "cherai-beach",
    "name": "Cherai Beach",
    "zone": "ernakulam-central",
    "sortOrder": 70,
    "priorityTier": 3
  },
  {
    "slug": "cherai-junction",
    "name": "Cherai Junction",
    "zone": "ernakulam-central",
    "sortOrder": 71,
    "priorityTier": 3
  },
  {
    "slug": "cheralai",
    "name": "Cheralai",
    "zone": "ernakulam-central",
    "sortOrder": 72,
    "priorityTier": 3
  },
  {
    "slug": "cheranalloor",
    "name": "Cheranalloor",
    "zone": "ernakulam-central",
    "sortOrder": 73,
    "priorityTier": 3
  },
  {
    "slug": "cheranalloor-ferry",
    "name": "Cheranalloor Ferry",
    "zone": "ernakulam-central",
    "sortOrder": 74,
    "priorityTier": 3
  },
  {
    "slug": "cheranalloor-junction",
    "name": "Cheranalloor Junction",
    "zone": "ernakulam-central",
    "sortOrder": 75,
    "priorityTier": 3
  },
  {
    "slug": "cheranalloor-north",
    "name": "Cheranalloor North",
    "zone": "ernakulam-central",
    "sortOrder": 76,
    "priorityTier": 3
  },
  {
    "slug": "cheranalloor-south",
    "name": "Cheranalloor South",
    "zone": "ernakulam-central",
    "sortOrder": 77,
    "priorityTier": 3
  },
  {
    "slug": "chilavannur",
    "name": "Chilavannur",
    "zone": "ernakulam-central",
    "sortOrder": 78,
    "priorityTier": 3
  },
  {
    "slug": "chilavannur-bund-road",
    "name": "Chilavannur Bund Road",
    "zone": "ernakulam-central",
    "sortOrder": 79,
    "priorityTier": 3
  },
  {
    "slug": "chittethukara",
    "name": "Chittethukara",
    "zone": "ernakulam-central",
    "sortOrder": 80,
    "priorityTier": 3
  },
  {
    "slug": "chittoor-kochi",
    "name": "Chittoor Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 81,
    "priorityTier": 3
  },
  {
    "slug": "chittoor-road",
    "name": "Chittoor Road",
    "zone": "ernakulam-central",
    "sortOrder": 82,
    "priorityTier": 3
  },
  {
    "slug": "choondi",
    "name": "Choondi",
    "zone": "ernakulam-central",
    "sortOrder": 83,
    "priorityTier": 3
  },
  {
    "slug": "choorakkode",
    "name": "Choorakkode",
    "zone": "ernakulam-central",
    "sortOrder": 84,
    "priorityTier": 3
  },
  {
    "slug": "choornikkara",
    "name": "Choornikkara",
    "zone": "ernakulam-central",
    "sortOrder": 85,
    "priorityTier": 3
  },
  {
    "slug": "chottanikkara",
    "name": "Chottanikkara",
    "zone": "ernakulam-central",
    "sortOrder": 86,
    "priorityTier": 3
  },
  {
    "slug": "chottanikkara-junction",
    "name": "Chottanikkara Junction",
    "zone": "ernakulam-central",
    "sortOrder": 87,
    "priorityTier": 3
  },
  {
    "slug": "chottanikkara-road",
    "name": "Chottanikkara Road",
    "zone": "ernakulam-central",
    "sortOrder": 88,
    "priorityTier": 3
  },
  {
    "slug": "chottanikkara-temple-area",
    "name": "Chottanikkara Temple Area",
    "zone": "ernakulam-central",
    "sortOrder": 89,
    "priorityTier": 3
  },
  {
    "slug": "chullickal",
    "name": "Chullickal",
    "zone": "ernakulam-central",
    "sortOrder": 90,
    "priorityTier": 3
  },
  {
    "slug": "chunangamvely",
    "name": "Chunangamvely",
    "zone": "ernakulam-central",
    "sortOrder": 91,
    "priorityTier": 3
  },
  {
    "slug": "civil-station-kakkanad",
    "name": "Civil Station Kakkanad",
    "zone": "kakkanad-infopark",
    "sortOrder": 92,
    "priorityTier": 1
  },
  {
    "slug": "cochin-bazaar",
    "name": "Cochin Bazaar",
    "zone": "ernakulam-central",
    "sortOrder": 93,
    "priorityTier": 3
  },
  {
    "slug": "cochin-international-airport-area",
    "name": "Cochin International Airport Area",
    "zone": "ernakulam-central",
    "sortOrder": 94,
    "priorityTier": 2
  },
  {
    "slug": "cochin-special-economic-zone",
    "name": "Cochin Special Economic Zone",
    "zone": "ernakulam-central",
    "sortOrder": 95,
    "priorityTier": 3
  },
  {
    "slug": "cochin-university-area",
    "name": "Cochin University Area",
    "zone": "ernakulam-central",
    "sortOrder": 96,
    "priorityTier": 3
  },
  {
    "slug": "cochin-university-metro-area",
    "name": "Cochin University Metro Area",
    "zone": "ernakulam-central",
    "sortOrder": 97,
    "priorityTier": 3
  },
  {
    "slug": "collectorate-junction-kakkanad",
    "name": "Collectorate Junction Kakkanad",
    "zone": "kakkanad-infopark",
    "sortOrder": 98,
    "priorityTier": 1
  },
  {
    "slug": "companypady",
    "name": "Companypady",
    "zone": "ernakulam-central",
    "sortOrder": 99,
    "priorityTier": 3
  },
  {
    "slug": "container-road-kochi",
    "name": "Container Road Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 100,
    "priorityTier": 3
  },
  {
    "slug": "convent-junction",
    "name": "Convent Junction",
    "zone": "ernakulam-central",
    "sortOrder": 101,
    "priorityTier": 3
  },
  {
    "slug": "cusat-campus",
    "name": "CUSAT Campus",
    "zone": "ernakulam-central",
    "sortOrder": 102,
    "priorityTier": 3
  },
  {
    "slug": "cusat-junction",
    "name": "CUSAT Junction",
    "zone": "ernakulam-central",
    "sortOrder": 103,
    "priorityTier": 3
  },
  {
    "slug": "deshabhimani-junction",
    "name": "Deshabhimani Junction",
    "zone": "ernakulam-central",
    "sortOrder": 104,
    "priorityTier": 3
  },
  {
    "slug": "deshabhimani-road",
    "name": "Deshabhimani Road",
    "zone": "ernakulam-central",
    "sortOrder": 105,
    "priorityTier": 3
  },
  {
    "slug": "desom",
    "name": "Desom",
    "zone": "ernakulam-central",
    "sortOrder": 106,
    "priorityTier": 3
  },
  {
    "slug": "devankulangara",
    "name": "Devankulangara",
    "zone": "ernakulam-central",
    "sortOrder": 107,
    "priorityTier": 3
  },
  {
    "slug": "durbar-hall",
    "name": "Durbar Hall",
    "zone": "ernakulam-central",
    "sortOrder": 108,
    "priorityTier": 3
  },
  {
    "slug": "earavely",
    "name": "Earavely",
    "zone": "ernakulam-central",
    "sortOrder": 109,
    "priorityTier": 3
  },
  {
    "slug": "east-kadungalloor",
    "name": "East Kadungalloor",
    "zone": "ernakulam-central",
    "sortOrder": 110,
    "priorityTier": 3
  },
  {
    "slug": "edachira",
    "name": "Edachira",
    "zone": "ernakulam-central",
    "sortOrder": 111,
    "priorityTier": 3
  },
  {
    "slug": "edachira-junction",
    "name": "Edachira Junction",
    "zone": "ernakulam-central",
    "sortOrder": 112,
    "priorityTier": 3
  },
  {
    "slug": "edakochi",
    "name": "Edakochi",
    "zone": "ernakulam-central",
    "sortOrder": 113,
    "priorityTier": 3
  },
  {
    "slug": "edakochi-junction",
    "name": "Edakochi Junction",
    "zone": "ernakulam-central",
    "sortOrder": 114,
    "priorityTier": 3
  },
  {
    "slug": "edakochi-north",
    "name": "Edakochi North",
    "zone": "ernakulam-central",
    "sortOrder": 115,
    "priorityTier": 3
  },
  {
    "slug": "edakochi-south",
    "name": "Edakochi South",
    "zone": "ernakulam-central",
    "sortOrder": 116,
    "priorityTier": 3
  },
  {
    "slug": "edappally",
    "name": "Edappally",
    "zone": "edappally",
    "sortOrder": 117,
    "priorityTier": 1
  },
  {
    "slug": "edappally-junction",
    "name": "Edappally Junction",
    "zone": "edappally",
    "sortOrder": 118,
    "priorityTier": 3
  },
  {
    "slug": "edappally-north",
    "name": "Edappally North",
    "zone": "edappally",
    "sortOrder": 119,
    "priorityTier": 3
  },
  {
    "slug": "edappally-south",
    "name": "Edappally South",
    "zone": "edappally",
    "sortOrder": 120,
    "priorityTier": 3
  },
  {
    "slug": "edappally-toll",
    "name": "Edappally Toll",
    "zone": "edappally",
    "sortOrder": 121,
    "priorityTier": 3
  },
  {
    "slug": "edathala",
    "name": "Edathala",
    "zone": "aluva",
    "sortOrder": 122,
    "priorityTier": 3
  },
  {
    "slug": "edathala-north",
    "name": "Edathala North",
    "zone": "aluva",
    "sortOrder": 123,
    "priorityTier": 3
  },
  {
    "slug": "edathala-south",
    "name": "Edathala South",
    "zone": "aluva",
    "sortOrder": 124,
    "priorityTier": 3
  },
  {
    "slug": "edavanakad",
    "name": "Edavanakad",
    "zone": "ernakulam-central",
    "sortOrder": 125,
    "priorityTier": 3
  },
  {
    "slug": "edavoor",
    "name": "Edavoor",
    "zone": "ernakulam-central",
    "sortOrder": 126,
    "priorityTier": 3
  },
  {
    "slug": "edayar",
    "name": "Edayar",
    "zone": "ernakulam-central",
    "sortOrder": 127,
    "priorityTier": 3
  },
  {
    "slug": "elamakkara",
    "name": "Elamakkara",
    "zone": "ernakulam-central",
    "sortOrder": 128,
    "priorityTier": 3
  },
  {
    "slug": "elamakkara-junction",
    "name": "Elamakkara Junction",
    "zone": "ernakulam-central",
    "sortOrder": 129,
    "priorityTier": 3
  },
  {
    "slug": "elamakkara-north",
    "name": "Elamakkara North",
    "zone": "ernakulam-central",
    "sortOrder": 130,
    "priorityTier": 3
  },
  {
    "slug": "elamakkara-railway-gate",
    "name": "Elamakkara Railway Gate",
    "zone": "ernakulam-central",
    "sortOrder": 131,
    "priorityTier": 3
  },
  {
    "slug": "elamakkara-south",
    "name": "Elamakkara South",
    "zone": "ernakulam-central",
    "sortOrder": 132,
    "priorityTier": 3
  },
  {
    "slug": "elamkulam",
    "name": "Elamkulam",
    "zone": "ernakulam-central",
    "sortOrder": 133,
    "priorityTier": 2
  },
  {
    "slug": "elamkulam-junction",
    "name": "Elamkulam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 134,
    "priorityTier": 3
  },
  {
    "slug": "elamkulam-kadavanthra",
    "name": "Elamkulam Kadavanthra",
    "zone": "ernakulam-central",
    "sortOrder": 135,
    "priorityTier": 3
  },
  {
    "slug": "elamkulam-metro-area",
    "name": "Elamkulam Metro Area",
    "zone": "ernakulam-central",
    "sortOrder": 136,
    "priorityTier": 3
  },
  {
    "slug": "elamkunnapuzha",
    "name": "Elamkunnapuzha",
    "zone": "ernakulam-central",
    "sortOrder": 137,
    "priorityTier": 3
  },
  {
    "slug": "eloor",
    "name": "Eloor",
    "zone": "ernakulam-central",
    "sortOrder": 138,
    "priorityTier": 3
  },
  {
    "slug": "eloor-ferry",
    "name": "Eloor Ferry",
    "zone": "ernakulam-central",
    "sortOrder": 139,
    "priorityTier": 3
  },
  {
    "slug": "eloor-north",
    "name": "Eloor North",
    "zone": "ernakulam-central",
    "sortOrder": 140,
    "priorityTier": 3
  },
  {
    "slug": "eloor-south",
    "name": "Eloor South",
    "zone": "ernakulam-central",
    "sortOrder": 141,
    "priorityTier": 3
  },
  {
    "slug": "eramalloor",
    "name": "Eramalloor",
    "zone": "ernakulam-central",
    "sortOrder": 142,
    "priorityTier": 3
  },
  {
    "slug": "ernakulam-boat-jetty",
    "name": "Ernakulam Boat Jetty",
    "zone": "ernakulam-central",
    "sortOrder": 143,
    "priorityTier": 3
  },
  {
    "slug": "ernakulam-central",
    "name": "Ernakulam Central",
    "zone": "ernakulam-central",
    "sortOrder": 144,
    "priorityTier": 1
  },
  {
    "slug": "ernakulam-junction-railway-station-area",
    "name": "Ernakulam Junction Railway Station Area",
    "zone": "ernakulam-central",
    "sortOrder": 145,
    "priorityTier": 3
  },
  {
    "slug": "ernakulam-north",
    "name": "Ernakulam North",
    "zone": "ernakulam-central",
    "sortOrder": 146,
    "priorityTier": 3
  },
  {
    "slug": "ernakulam-south",
    "name": "Ernakulam South",
    "zone": "ernakulam-central",
    "sortOrder": 147,
    "priorityTier": 3
  },
  {
    "slug": "ernakulam-town-railway-station-area",
    "name": "Ernakulam Town Railway Station Area",
    "zone": "ernakulam-central",
    "sortOrder": 148,
    "priorityTier": 3
  },
  {
    "slug": "eroor",
    "name": "Eroor",
    "zone": "ernakulam-central",
    "sortOrder": 149,
    "priorityTier": 3
  },
  {
    "slug": "eroor-junction",
    "name": "Eroor Junction",
    "zone": "ernakulam-central",
    "sortOrder": 150,
    "priorityTier": 3
  },
  {
    "slug": "eroor-north",
    "name": "Eroor North",
    "zone": "ernakulam-central",
    "sortOrder": 151,
    "priorityTier": 3
  },
  {
    "slug": "eroor-south",
    "name": "Eroor South",
    "zone": "ernakulam-central",
    "sortOrder": 152,
    "priorityTier": 3
  },
  {
    "slug": "ezhikkara",
    "name": "Ezhikkara",
    "zone": "ernakulam-central",
    "sortOrder": 153,
    "priorityTier": 3
  },
  {
    "slug": "fact-township",
    "name": "FACT Township",
    "zone": "ernakulam-central",
    "sortOrder": 154,
    "priorityTier": 3
  },
  {
    "slug": "foreshore-road",
    "name": "Foreshore Road",
    "zone": "ernakulam-central",
    "sortOrder": 155,
    "priorityTier": 3
  },
  {
    "slug": "fort-kochi",
    "name": "Fort Kochi",
    "zone": "fort-kochi",
    "sortOrder": 156,
    "priorityTier": 1
  },
  {
    "slug": "fort-kochi-beach",
    "name": "Fort Kochi Beach",
    "zone": "fort-kochi",
    "sortOrder": 157,
    "priorityTier": 3
  },
  {
    "slug": "fort-kochi-kunnumupuram",
    "name": "Fort Kochi Kunnumupuram",
    "zone": "fort-kochi",
    "sortOrder": 158,
    "priorityTier": 3
  },
  {
    "slug": "fort-kochi-veli",
    "name": "Fort Kochi Veli",
    "zone": "fort-kochi",
    "sortOrder": 159,
    "priorityTier": 3
  },
  {
    "slug": "fort-vypin",
    "name": "Fort Vypin",
    "zone": "fort-kochi",
    "sortOrder": 160,
    "priorityTier": 3
  },
  {
    "slug": "gandhi-nagar",
    "name": "Gandhi Nagar",
    "zone": "ernakulam-central",
    "sortOrder": 161,
    "priorityTier": 3
  },
  {
    "slug": "giri-nagar-kadavanthra",
    "name": "Giri Nagar Kadavanthra",
    "zone": "ernakulam-central",
    "sortOrder": 162,
    "priorityTier": 3
  },
  {
    "slug": "girinagar",
    "name": "Girinagar",
    "zone": "ernakulam-central",
    "sortOrder": 163,
    "priorityTier": 3
  },
  {
    "slug": "glass-colony",
    "name": "Glass Colony",
    "zone": "ernakulam-central",
    "sortOrder": 164,
    "priorityTier": 3
  },
  {
    "slug": "gold-souk-area-vyttila",
    "name": "Gold Souk Area Vyttila",
    "zone": "vyttila",
    "sortOrder": 165,
    "priorityTier": 3
  },
  {
    "slug": "goshree-junction",
    "name": "Goshree Junction",
    "zone": "ernakulam-central",
    "sortOrder": 166,
    "priorityTier": 3
  },
  {
    "slug": "gujarati-road",
    "name": "Gujarati Road",
    "zone": "ernakulam-central",
    "sortOrder": 167,
    "priorityTier": 3
  },
  {
    "slug": "gundu-island",
    "name": "Gundu Island",
    "zone": "ernakulam-central",
    "sortOrder": 168,
    "priorityTier": 3
  },
  {
    "slug": "high-court-area-kochi",
    "name": "High Court Area Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 169,
    "priorityTier": 3
  },
  {
    "slug": "high-court-junction",
    "name": "High Court Junction",
    "zone": "ernakulam-central",
    "sortOrder": 170,
    "priorityTier": 3
  },
  {
    "slug": "hmt-colony",
    "name": "HMT Colony",
    "zone": "ernakulam-central",
    "sortOrder": 171,
    "priorityTier": 3
  },
  {
    "slug": "hmt-junction",
    "name": "HMT Junction",
    "zone": "ernakulam-central",
    "sortOrder": 172,
    "priorityTier": 3
  },
  {
    "slug": "infopark-kochi",
    "name": "Infopark Kochi",
    "zone": "kakkanad-infopark",
    "sortOrder": 173,
    "priorityTier": 1
  },
  {
    "slug": "infopark-phase-1",
    "name": "Infopark Phase 1",
    "zone": "kakkanad-infopark",
    "sortOrder": 174,
    "priorityTier": 1
  },
  {
    "slug": "infopark-phase-2",
    "name": "Infopark Phase 2",
    "zone": "kakkanad-infopark",
    "sortOrder": 175,
    "priorityTier": 1
  },
  {
    "slug": "irumpanam",
    "name": "Irumpanam",
    "zone": "ernakulam-central",
    "sortOrder": 176,
    "priorityTier": 3
  },
  {
    "slug": "irumpanam-junction",
    "name": "Irumpanam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 177,
    "priorityTier": 3
  },
  {
    "slug": "island-north",
    "name": "Island North",
    "zone": "ernakulam-central",
    "sortOrder": 178,
    "priorityTier": 3
  },
  {
    "slug": "island-south",
    "name": "Island South",
    "zone": "ernakulam-central",
    "sortOrder": 179,
    "priorityTier": 3
  },
  {
    "slug": "janatha-junction",
    "name": "Janatha Junction",
    "zone": "ernakulam-central",
    "sortOrder": 180,
    "priorityTier": 3
  },
  {
    "slug": "janatha-road-kaloor",
    "name": "Janatha Road Kaloor",
    "zone": "ernakulam-central",
    "sortOrder": 181,
    "priorityTier": 3
  },
  {
    "slug": "jawahar-nagar-kadavanthra",
    "name": "Jawahar Nagar Kadavanthra",
    "zone": "ernakulam-central",
    "sortOrder": 182,
    "priorityTier": 3
  },
  {
    "slug": "jew-street-ernakulam",
    "name": "Jew Street Ernakulam",
    "zone": "ernakulam-central",
    "sortOrder": 183,
    "priorityTier": 3
  },
  {
    "slug": "jew-town",
    "name": "Jew Town",
    "zone": "ernakulam-central",
    "sortOrder": 184,
    "priorityTier": 3
  },
  {
    "slug": "jn-stadium-area",
    "name": "JN Stadium Area",
    "zone": "ernakulam-central",
    "sortOrder": 185,
    "priorityTier": 3
  },
  {
    "slug": "jos-junction",
    "name": "Jos Junction",
    "zone": "ernakulam-central",
    "sortOrder": 186,
    "priorityTier": 3
  },
  {
    "slug": "kacheripady-ernakulam",
    "name": "Kacheripady Ernakulam",
    "zone": "ernakulam-central",
    "sortOrder": 187,
    "priorityTier": 3
  },
  {
    "slug": "kacheripady-palluruthy",
    "name": "Kacheripady Palluruthy",
    "zone": "ernakulam-central",
    "sortOrder": 188,
    "priorityTier": 3
  },
  {
    "slug": "kadamakkudy",
    "name": "Kadamakkudy",
    "zone": "ernakulam-central",
    "sortOrder": 189,
    "priorityTier": 3
  },
  {
    "slug": "kadamakkudy-islands",
    "name": "Kadamakkudy Islands",
    "zone": "ernakulam-central",
    "sortOrder": 190,
    "priorityTier": 3
  },
  {
    "slug": "kadavanthra",
    "name": "Kadavanthra",
    "zone": "ernakulam-central",
    "sortOrder": 191,
    "priorityTier": 1
  },
  {
    "slug": "kadavanthra-junction",
    "name": "Kadavanthra Junction",
    "zone": "ernakulam-central",
    "sortOrder": 192,
    "priorityTier": 3
  },
  {
    "slug": "kadebhagam",
    "name": "Kadebhagam",
    "zone": "ernakulam-central",
    "sortOrder": 193,
    "priorityTier": 3
  },
  {
    "slug": "kadungalloor",
    "name": "Kadungalloor",
    "zone": "ernakulam-central",
    "sortOrder": 194,
    "priorityTier": 3
  },
  {
    "slug": "kaitharam",
    "name": "Kaitharam",
    "zone": "ernakulam-central",
    "sortOrder": 195,
    "priorityTier": 3
  },
  {
    "slug": "kakkanad",
    "name": "Kakkanad",
    "zone": "kakkanad-infopark",
    "sortOrder": 196,
    "priorityTier": 1
  },
  {
    "slug": "kakkanad-civil-station",
    "name": "Kakkanad Civil Station",
    "zone": "kakkanad-infopark",
    "sortOrder": 197,
    "priorityTier": 1
  },
  {
    "slug": "kakkanad-csez",
    "name": "Kakkanad Csez",
    "zone": "kakkanad-infopark",
    "sortOrder": 198,
    "priorityTier": 1
  },
  {
    "slug": "kakkanad-infopark-road",
    "name": "Kakkanad Infopark Road",
    "zone": "kakkanad-infopark",
    "sortOrder": 199,
    "priorityTier": 1
  },
  {
    "slug": "kakkanad-junction",
    "name": "Kakkanad Junction",
    "zone": "kakkanad-infopark",
    "sortOrder": 200,
    "priorityTier": 1
  },
  {
    "slug": "kakkanad-pallikkara",
    "name": "Kakkanad Pallikkara",
    "zone": "kakkanad-infopark",
    "sortOrder": 201,
    "priorityTier": 1
  },
  {
    "slug": "kakkanad-west",
    "name": "Kakkanad West",
    "zone": "kakkanad-infopark",
    "sortOrder": 202,
    "priorityTier": 1
  },
  {
    "slug": "kalamassery",
    "name": "Kalamassery",
    "zone": "ernakulam-central",
    "sortOrder": 203,
    "priorityTier": 1
  },
  {
    "slug": "kalamassery-hmt-junction",
    "name": "Kalamassery HMT Junction",
    "zone": "ernakulam-central",
    "sortOrder": 204,
    "priorityTier": 3
  },
  {
    "slug": "kalamassery-industrial-estate",
    "name": "Kalamassery Industrial Estate",
    "zone": "ernakulam-central",
    "sortOrder": 205,
    "priorityTier": 3
  },
  {
    "slug": "kalamassery-medical-college",
    "name": "Kalamassery Medical College",
    "zone": "ernakulam-central",
    "sortOrder": 206,
    "priorityTier": 3
  },
  {
    "slug": "kalamassery-north",
    "name": "Kalamassery North",
    "zone": "ernakulam-central",
    "sortOrder": 207,
    "priorityTier": 3
  },
  {
    "slug": "kalamassery-premier-junction",
    "name": "Kalamassery Premier Junction",
    "zone": "ernakulam-central",
    "sortOrder": 208,
    "priorityTier": 3
  },
  {
    "slug": "kalamassery-south",
    "name": "Kalamassery South",
    "zone": "ernakulam-central",
    "sortOrder": 209,
    "priorityTier": 3
  },
  {
    "slug": "kaloor",
    "name": "Kaloor",
    "zone": "ernakulam-central",
    "sortOrder": 210,
    "priorityTier": 1
  },
  {
    "slug": "kaloor-international-stadium",
    "name": "Kaloor International Stadium",
    "zone": "ernakulam-central",
    "sortOrder": 211,
    "priorityTier": 3
  },
  {
    "slug": "kaloor-kadavanthra-road",
    "name": "Kaloor Kadavanthra Road",
    "zone": "ernakulam-central",
    "sortOrder": 212,
    "priorityTier": 3
  },
  {
    "slug": "kaloor-market",
    "name": "Kaloor Market",
    "zone": "ernakulam-central",
    "sortOrder": 213,
    "priorityTier": 3
  },
  {
    "slug": "kaloor-north",
    "name": "Kaloor North",
    "zone": "ernakulam-central",
    "sortOrder": 214,
    "priorityTier": 3
  },
  {
    "slug": "kaloor-south",
    "name": "Kaloor South",
    "zone": "ernakulam-central",
    "sortOrder": 215,
    "priorityTier": 3
  },
  {
    "slug": "kandakkadavu",
    "name": "Kandakkadavu",
    "zone": "ernakulam-central",
    "sortOrder": 216,
    "priorityTier": 3
  },
  {
    "slug": "kandanad",
    "name": "Kandanad",
    "zone": "ernakulam-central",
    "sortOrder": 217,
    "priorityTier": 3
  },
  {
    "slug": "kangarappady",
    "name": "Kangarappady",
    "zone": "ernakulam-central",
    "sortOrder": 218,
    "priorityTier": 3
  },
  {
    "slug": "kangarappady-junction",
    "name": "Kangarappady Junction",
    "zone": "ernakulam-central",
    "sortOrder": 219,
    "priorityTier": 3
  },
  {
    "slug": "kaniyampuzha",
    "name": "Kaniyampuzha",
    "zone": "ernakulam-central",
    "sortOrder": 220,
    "priorityTier": 3
  },
  {
    "slug": "kaniyampuzha-road",
    "name": "Kaniyampuzha Road",
    "zone": "ernakulam-central",
    "sortOrder": 221,
    "priorityTier": 3
  },
  {
    "slug": "kanjiramattom",
    "name": "Kanjiramattom",
    "zone": "ernakulam-central",
    "sortOrder": 222,
    "priorityTier": 3
  },
  {
    "slug": "kanjoor",
    "name": "Kanjoor",
    "zone": "ernakulam-central",
    "sortOrder": 223,
    "priorityTier": 3
  },
  {
    "slug": "kannamaly",
    "name": "Kannamaly",
    "zone": "ernakulam-central",
    "sortOrder": 224,
    "priorityTier": 3
  },
  {
    "slug": "kannangatt",
    "name": "Kannangatt",
    "zone": "ernakulam-central",
    "sortOrder": 225,
    "priorityTier": 3
  },
  {
    "slug": "karanakodam",
    "name": "Karanakodam",
    "zone": "ernakulam-central",
    "sortOrder": 226,
    "priorityTier": 3
  },
  {
    "slug": "karingachira",
    "name": "Karingachira",
    "zone": "ernakulam-central",
    "sortOrder": 227,
    "priorityTier": 3
  },
  {
    "slug": "karingachira-junction",
    "name": "Karingachira Junction",
    "zone": "ernakulam-central",
    "sortOrder": 228,
    "priorityTier": 3
  },
  {
    "slug": "karippalam",
    "name": "Karippalam",
    "zone": "ernakulam-central",
    "sortOrder": 229,
    "priorityTier": 3
  },
  {
    "slug": "karukappilly",
    "name": "Karukappilly",
    "zone": "ernakulam-central",
    "sortOrder": 230,
    "priorityTier": 3
  },
  {
    "slug": "karukutty",
    "name": "Karukutty",
    "zone": "ernakulam-central",
    "sortOrder": 231,
    "priorityTier": 3
  },
  {
    "slug": "karumalloor",
    "name": "Karumalloor",
    "zone": "ernakulam-central",
    "sortOrder": 232,
    "priorityTier": 3
  },
  {
    "slug": "karuvelipady",
    "name": "Karuvelipady",
    "zone": "ernakulam-central",
    "sortOrder": 233,
    "priorityTier": 3
  },
  {
    "slug": "kathrikadavu",
    "name": "Kathrikadavu",
    "zone": "ernakulam-central",
    "sortOrder": 234,
    "priorityTier": 3
  },
  {
    "slug": "kathrikadavu-extension",
    "name": "Kathrikadavu Extension",
    "zone": "ernakulam-central",
    "sortOrder": 235,
    "priorityTier": 3
  },
  {
    "slug": "kathrikadavu-junction",
    "name": "Kathrikadavu Junction",
    "zone": "ernakulam-central",
    "sortOrder": 236,
    "priorityTier": 3
  },
  {
    "slug": "keerthi-nagar",
    "name": "Keerthi Nagar",
    "zone": "ernakulam-central",
    "sortOrder": 237,
    "priorityTier": 3
  },
  {
    "slug": "keezhillam",
    "name": "Keezhillam",
    "zone": "ernakulam-central",
    "sortOrder": 238,
    "priorityTier": 3
  },
  {
    "slug": "keezhmad",
    "name": "Keezhmad",
    "zone": "ernakulam-central",
    "sortOrder": 239,
    "priorityTier": 3
  },
  {
    "slug": "kidangoor-angamaly",
    "name": "Kidangoor Angamaly",
    "zone": "angamaly",
    "sortOrder": 240,
    "priorityTier": 3
  },
  {
    "slug": "kizhakkambalam",
    "name": "Kizhakkambalam",
    "zone": "ernakulam-central",
    "sortOrder": 241,
    "priorityTier": 3
  },
  {
    "slug": "kizhakkambalam-road",
    "name": "Kizhakkambalam Road",
    "zone": "ernakulam-central",
    "sortOrder": 242,
    "priorityTier": 3
  },
  {
    "slug": "kizhakkekotta",
    "name": "Kizhakkekotta",
    "zone": "ernakulam-central",
    "sortOrder": 243,
    "priorityTier": 3
  },
  {
    "slug": "kochangadi",
    "name": "Kochangadi",
    "zone": "ernakulam-central",
    "sortOrder": 244,
    "priorityTier": 3
  },
  {
    "slug": "kochi-marine-drive",
    "name": "Kochi Marine Drive",
    "zone": "ernakulam-central",
    "sortOrder": 245,
    "priorityTier": 3
  },
  {
    "slug": "kochi-metro-aluva-area",
    "name": "Kochi Metro Aluva Area",
    "zone": "aluva",
    "sortOrder": 246,
    "priorityTier": 3
  },
  {
    "slug": "kochi-university-junction",
    "name": "Kochi University Junction",
    "zone": "ernakulam-central",
    "sortOrder": 247,
    "priorityTier": 3
  },
  {
    "slug": "kodamthuruth",
    "name": "Kodamthuruth",
    "zone": "ernakulam-central",
    "sortOrder": 248,
    "priorityTier": 3
  },
  {
    "slug": "kolenchery",
    "name": "Kolenchery",
    "zone": "ernakulam-central",
    "sortOrder": 249,
    "priorityTier": 3
  },
  {
    "slug": "kombara",
    "name": "Kombara",
    "zone": "ernakulam-central",
    "sortOrder": 250,
    "priorityTier": 3
  },
  {
    "slug": "konam",
    "name": "Konam",
    "zone": "ernakulam-central",
    "sortOrder": 251,
    "priorityTier": 3
  },
  {
    "slug": "kongorpilly",
    "name": "Kongorpilly",
    "zone": "ernakulam-central",
    "sortOrder": 252,
    "priorityTier": 3
  },
  {
    "slug": "konthuruthy",
    "name": "Konthuruthy",
    "zone": "ernakulam-central",
    "sortOrder": 253,
    "priorityTier": 3
  },
  {
    "slug": "koonamthai",
    "name": "Koonamthai",
    "zone": "ernakulam-central",
    "sortOrder": 254,
    "priorityTier": 3
  },
  {
    "slug": "koovappady",
    "name": "Koovappady",
    "zone": "ernakulam-central",
    "sortOrder": 255,
    "priorityTier": 3
  },
  {
    "slug": "kothad",
    "name": "Kothad",
    "zone": "ernakulam-central",
    "sortOrder": 256,
    "priorityTier": 3
  },
  {
    "slug": "kothad-junction",
    "name": "Kothad Junction",
    "zone": "ernakulam-central",
    "sortOrder": 257,
    "priorityTier": 3
  },
  {
    "slug": "kottapuram-alangad",
    "name": "Kottapuram Alangad",
    "zone": "ernakulam-central",
    "sortOrder": 258,
    "priorityTier": 3
  },
  {
    "slug": "kottuvally",
    "name": "Kottuvally",
    "zone": "ernakulam-central",
    "sortOrder": 259,
    "priorityTier": 3
  },
  {
    "slug": "kp-vallon-road",
    "name": "KP Vallon Road",
    "zone": "ernakulam-central",
    "sortOrder": 260,
    "priorityTier": 3
  },
  {
    "slug": "kp-vallon-road-kadavanthra",
    "name": "KP Vallon Road Kadavanthra",
    "zone": "ernakulam-central",
    "sortOrder": 261,
    "priorityTier": 3
  },
  {
    "slug": "kumbalam",
    "name": "Kumbalam",
    "zone": "ernakulam-central",
    "sortOrder": 262,
    "priorityTier": 3
  },
  {
    "slug": "kumbalam-north",
    "name": "Kumbalam North",
    "zone": "ernakulam-central",
    "sortOrder": 263,
    "priorityTier": 3
  },
  {
    "slug": "kumbalam-south",
    "name": "Kumbalam South",
    "zone": "ernakulam-central",
    "sortOrder": 264,
    "priorityTier": 3
  },
  {
    "slug": "kumbalangi",
    "name": "Kumbalangi",
    "zone": "ernakulam-central",
    "sortOrder": 265,
    "priorityTier": 2
  },
  {
    "slug": "kumbalangi-north",
    "name": "Kumbalangi North",
    "zone": "ernakulam-central",
    "sortOrder": 266,
    "priorityTier": 3
  },
  {
    "slug": "kumbalangi-road",
    "name": "Kumbalangi Road",
    "zone": "ernakulam-central",
    "sortOrder": 267,
    "priorityTier": 3
  },
  {
    "slug": "kumbalangi-south",
    "name": "Kumbalangi South",
    "zone": "ernakulam-central",
    "sortOrder": 268,
    "priorityTier": 3
  },
  {
    "slug": "kundannoor",
    "name": "Kundannoor",
    "zone": "ernakulam-central",
    "sortOrder": 269,
    "priorityTier": 2
  },
  {
    "slug": "kundannoor-bypass",
    "name": "Kundannoor Bypass",
    "zone": "ernakulam-central",
    "sortOrder": 270,
    "priorityTier": 3
  },
  {
    "slug": "kundannoor-junction",
    "name": "Kundannoor Junction",
    "zone": "ernakulam-central",
    "sortOrder": 271,
    "priorityTier": 3
  },
  {
    "slug": "kundannoor-maradu",
    "name": "Kundannoor Maradu",
    "zone": "vyttila",
    "sortOrder": 272,
    "priorityTier": 3
  },
  {
    "slug": "kunnathunad",
    "name": "Kunnathunad",
    "zone": "ernakulam-central",
    "sortOrder": 273,
    "priorityTier": 3
  },
  {
    "slug": "kunnumpuram-cheranalloor",
    "name": "Kunnumpuram Cheranalloor",
    "zone": "ernakulam-central",
    "sortOrder": 274,
    "priorityTier": 3
  },
  {
    "slug": "kunnumpuram-kochi",
    "name": "Kunnumpuram Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 275,
    "priorityTier": 3
  },
  {
    "slug": "kusumagiri",
    "name": "Kusumagiri",
    "zone": "ernakulam-central",
    "sortOrder": 276,
    "priorityTier": 3
  },
  {
    "slug": "kuthappady",
    "name": "Kuthappady",
    "zone": "ernakulam-central",
    "sortOrder": 277,
    "priorityTier": 3
  },
  {
    "slug": "kuthiathode",
    "name": "Kuthiathode",
    "zone": "ernakulam-central",
    "sortOrder": 278,
    "priorityTier": 3
  },
  {
    "slug": "kuzhivelippady",
    "name": "Kuzhivelippady",
    "zone": "ernakulam-central",
    "sortOrder": 279,
    "priorityTier": 3
  },
  {
    "slug": "kuzhuppilly",
    "name": "Kuzhuppilly",
    "zone": "ernakulam-central",
    "sortOrder": 280,
    "priorityTier": 3
  },
  {
    "slug": "kuzhuppilly-beach",
    "name": "Kuzhuppilly Beach",
    "zone": "ernakulam-central",
    "sortOrder": 281,
    "priorityTier": 3
  },
  {
    "slug": "kuzhuppilly-junction",
    "name": "Kuzhuppilly Junction",
    "zone": "ernakulam-central",
    "sortOrder": 282,
    "priorityTier": 3
  },
  {
    "slug": "layam-road",
    "name": "Layam Road",
    "zone": "ernakulam-central",
    "sortOrder": 283,
    "priorityTier": 3
  },
  {
    "slug": "lissie-junction",
    "name": "Lissie Junction",
    "zone": "ernakulam-central",
    "sortOrder": 284,
    "priorityTier": 3
  },
  {
    "slug": "lulu-mall-area",
    "name": "Lulu Mall Area",
    "zone": "ernakulam-central",
    "sortOrder": 285,
    "priorityTier": 1
  },
  {
    "slug": "lulu-mall-junction",
    "name": "Lulu Mall Junction",
    "zone": "ernakulam-central",
    "sortOrder": 286,
    "priorityTier": 3
  },
  {
    "slug": "malippuram",
    "name": "Malippuram",
    "zone": "ernakulam-central",
    "sortOrder": 287,
    "priorityTier": 3
  },
  {
    "slug": "mamangalam",
    "name": "Mamangalam",
    "zone": "ernakulam-central",
    "sortOrder": 288,
    "priorityTier": 3
  },
  {
    "slug": "mamangalam-church-area",
    "name": "Mamangalam Church Area",
    "zone": "ernakulam-central",
    "sortOrder": 289,
    "priorityTier": 3
  },
  {
    "slug": "mamangalam-north",
    "name": "Mamangalam North",
    "zone": "ernakulam-central",
    "sortOrder": 290,
    "priorityTier": 3
  },
  {
    "slug": "manassery",
    "name": "Manassery",
    "zone": "ernakulam-central",
    "sortOrder": 291,
    "priorityTier": 3
  },
  {
    "slug": "maneed",
    "name": "Maneed",
    "zone": "ernakulam-central",
    "sortOrder": 292,
    "priorityTier": 3
  },
  {
    "slug": "manjaly",
    "name": "Manjaly",
    "zone": "ernakulam-central",
    "sortOrder": 293,
    "priorityTier": 3
  },
  {
    "slug": "manjummel",
    "name": "Manjummel",
    "zone": "ernakulam-central",
    "sortOrder": 294,
    "priorityTier": 3
  },
  {
    "slug": "maradu",
    "name": "Maradu",
    "zone": "vyttila",
    "sortOrder": 295,
    "priorityTier": 1
  },
  {
    "slug": "maradu-junction",
    "name": "Maradu Junction",
    "zone": "vyttila",
    "sortOrder": 296,
    "priorityTier": 3
  },
  {
    "slug": "maradu-market",
    "name": "Maradu Market",
    "zone": "vyttila",
    "sortOrder": 297,
    "priorityTier": 3
  },
  {
    "slug": "marampally",
    "name": "Marampally",
    "zone": "ernakulam-central",
    "sortOrder": 298,
    "priorityTier": 3
  },
  {
    "slug": "marine-drive-extension",
    "name": "Marine Drive Extension",
    "zone": "ernakulam-central",
    "sortOrder": 299,
    "priorityTier": 3
  },
  {
    "slug": "market-road-ernakulam",
    "name": "Market Road Ernakulam",
    "zone": "ernakulam-central",
    "sortOrder": 300,
    "priorityTier": 3
  },
  {
    "slug": "maruvakkad",
    "name": "Maruvakkad",
    "zone": "ernakulam-central",
    "sortOrder": 301,
    "priorityTier": 3
  },
  {
    "slug": "mattancherry",
    "name": "Mattancherry",
    "zone": "fort-kochi",
    "sortOrder": 302,
    "priorityTier": 1
  },
  {
    "slug": "mattancherry-palace-area",
    "name": "Mattancherry Palace Area",
    "zone": "fort-kochi",
    "sortOrder": 303,
    "priorityTier": 3
  },
  {
    "slug": "mattancherry-town",
    "name": "Mattancherry Town",
    "zone": "fort-kochi",
    "sortOrder": 304,
    "priorityTier": 3
  },
  {
    "slug": "mattoor",
    "name": "Mattoor",
    "zone": "ernakulam-central",
    "sortOrder": 305,
    "priorityTier": 3
  },
  {
    "slug": "mekkara",
    "name": "Mekkara",
    "zone": "ernakulam-central",
    "sortOrder": 306,
    "priorityTier": 3
  },
  {
    "slug": "menaka",
    "name": "Menaka",
    "zone": "ernakulam-central",
    "sortOrder": 307,
    "priorityTier": 3
  },
  {
    "slug": "metro-pillar-450-area",
    "name": "Metro Pillar 450 Area",
    "zone": "ernakulam-central",
    "sortOrder": 308,
    "priorityTier": 3
  },
  {
    "slug": "mg-road-kochi",
    "name": "MG Road Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 309,
    "priorityTier": 1
  },
  {
    "slug": "moolamkuzhy",
    "name": "Moolamkuzhy",
    "zone": "ernakulam-central",
    "sortOrder": 310,
    "priorityTier": 3
  },
  {
    "slug": "moolampilly",
    "name": "Moolampilly",
    "zone": "ernakulam-central",
    "sortOrder": 311,
    "priorityTier": 3
  },
  {
    "slug": "moothakunnam",
    "name": "Moothakunnam",
    "zone": "ernakulam-central",
    "sortOrder": 312,
    "priorityTier": 3
  },
  {
    "slug": "mudickal",
    "name": "Mudickal",
    "zone": "ernakulam-central",
    "sortOrder": 313,
    "priorityTier": 3
  },
  {
    "slug": "mulanthuruthy",
    "name": "Mulanthuruthy",
    "zone": "ernakulam-central",
    "sortOrder": 314,
    "priorityTier": 3
  },
  {
    "slug": "mulanthuruthy-junction",
    "name": "Mulanthuruthy Junction",
    "zone": "ernakulam-central",
    "sortOrder": 315,
    "priorityTier": 3
  },
  {
    "slug": "mulavukad",
    "name": "Mulavukad",
    "zone": "ernakulam-central",
    "sortOrder": 316,
    "priorityTier": 3
  },
  {
    "slug": "mulavukad-junction",
    "name": "Mulavukad Junction",
    "zone": "ernakulam-central",
    "sortOrder": 317,
    "priorityTier": 3
  },
  {
    "slug": "mullassery-canal-road",
    "name": "Mullassery Canal Road",
    "zone": "ernakulam-central",
    "sortOrder": 318,
    "priorityTier": 3
  },
  {
    "slug": "munambam",
    "name": "Munambam",
    "zone": "ernakulam-central",
    "sortOrder": 319,
    "priorityTier": 3
  },
  {
    "slug": "mundamveli",
    "name": "Mundamveli",
    "zone": "ernakulam-central",
    "sortOrder": 320,
    "priorityTier": 3
  },
  {
    "slug": "mundamveli-east",
    "name": "Mundamveli East",
    "zone": "ernakulam-central",
    "sortOrder": 321,
    "priorityTier": 3
  },
  {
    "slug": "mundamveli-junction",
    "name": "Mundamveli Junction",
    "zone": "ernakulam-central",
    "sortOrder": 322,
    "priorityTier": 3
  },
  {
    "slug": "muppathadam",
    "name": "Muppathadam",
    "zone": "ernakulam-central",
    "sortOrder": 323,
    "priorityTier": 3
  },
  {
    "slug": "muppathadam-junction",
    "name": "Muppathadam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 324,
    "priorityTier": 3
  },
  {
    "slug": "muttar",
    "name": "Muttar",
    "zone": "ernakulam-central",
    "sortOrder": 325,
    "priorityTier": 3
  },
  {
    "slug": "muttom-aluva",
    "name": "Muttom Aluva",
    "zone": "aluva",
    "sortOrder": 326,
    "priorityTier": 3
  },
  {
    "slug": "nad-aluva",
    "name": "NAD Aluva",
    "zone": "aluva",
    "sortOrder": 327,
    "priorityTier": 3
  },
  {
    "slug": "nadama",
    "name": "Nadama",
    "zone": "ernakulam-central",
    "sortOrder": 328,
    "priorityTier": 3
  },
  {
    "slug": "nambyapuram",
    "name": "Nambyapuram",
    "zone": "ernakulam-central",
    "sortOrder": 329,
    "priorityTier": 3
  },
  {
    "slug": "nasrath",
    "name": "Nasrath",
    "zone": "ernakulam-central",
    "sortOrder": 330,
    "priorityTier": 3
  },
  {
    "slug": "naval-base-kochi",
    "name": "Naval Base Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 331,
    "priorityTier": 3
  },
  {
    "slug": "nayarambalam",
    "name": "Nayarambalam",
    "zone": "ernakulam-central",
    "sortOrder": 332,
    "priorityTier": 3
  },
  {
    "slug": "nayathode",
    "name": "Nayathode",
    "zone": "ernakulam-central",
    "sortOrder": 333,
    "priorityTier": 3
  },
  {
    "slug": "nedumbassery",
    "name": "Nedumbassery",
    "zone": "angamaly",
    "sortOrder": 334,
    "priorityTier": 2
  },
  {
    "slug": "nedumbassery-airport-junction",
    "name": "Nedumbassery Airport Junction",
    "zone": "angamaly",
    "sortOrder": 335,
    "priorityTier": 3
  },
  {
    "slug": "neerikode",
    "name": "Neerikode",
    "zone": "ernakulam-central",
    "sortOrder": 336,
    "priorityTier": 3
  },
  {
    "slug": "nettoor",
    "name": "Nettoor",
    "zone": "ernakulam-central",
    "sortOrder": 337,
    "priorityTier": 3
  },
  {
    "slug": "nettoor-junction",
    "name": "Nettoor Junction",
    "zone": "ernakulam-central",
    "sortOrder": 338,
    "priorityTier": 3
  },
  {
    "slug": "nettoor-south",
    "name": "Nettoor South",
    "zone": "ernakulam-central",
    "sortOrder": 339,
    "priorityTier": 3
  },
  {
    "slug": "ngo-quarters-kakkanad",
    "name": "NGO Quarters Kakkanad",
    "zone": "kakkanad-infopark",
    "sortOrder": 340,
    "priorityTier": 1
  },
  {
    "slug": "njarakkal",
    "name": "Njarakkal",
    "zone": "ernakulam-central",
    "sortOrder": 341,
    "priorityTier": 3
  },
  {
    "slug": "njarakkal-junction",
    "name": "Njarakkal Junction",
    "zone": "ernakulam-central",
    "sortOrder": 342,
    "priorityTier": 3
  },
  {
    "slug": "north-kalamassery",
    "name": "North Kalamassery",
    "zone": "ernakulam-central",
    "sortOrder": 343,
    "priorityTier": 3
  },
  {
    "slug": "north-paravur",
    "name": "North Paravur",
    "zone": "angamaly",
    "sortOrder": 344,
    "priorityTier": 2
  },
  {
    "slug": "north-paravur-market",
    "name": "North Paravur Market",
    "zone": "angamaly",
    "sortOrder": 345,
    "priorityTier": 3
  },
  {
    "slug": "oberon-mall-area",
    "name": "Oberon Mall Area",
    "zone": "ernakulam-central",
    "sortOrder": 346,
    "priorityTier": 3
  },
  {
    "slug": "ochanthuruthu",
    "name": "Ochanthuruthu",
    "zone": "ernakulam-central",
    "sortOrder": 347,
    "priorityTier": 3
  },
  {
    "slug": "okkal",
    "name": "Okkal",
    "zone": "ernakulam-central",
    "sortOrder": 348,
    "priorityTier": 3
  },
  {
    "slug": "pachalam",
    "name": "Pachalam",
    "zone": "ernakulam-central",
    "sortOrder": 349,
    "priorityTier": 3
  },
  {
    "slug": "pachalam-junction",
    "name": "Pachalam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 350,
    "priorityTier": 3
  },
  {
    "slug": "padamugal",
    "name": "Padamugal",
    "zone": "ernakulam-central",
    "sortOrder": 351,
    "priorityTier": 3
  },
  {
    "slug": "padamugal-junction",
    "name": "Padamugal Junction",
    "zone": "ernakulam-central",
    "sortOrder": 352,
    "priorityTier": 3
  },
  {
    "slug": "padamugal-kochi",
    "name": "Padamugal Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 353,
    "priorityTier": 3
  },
  {
    "slug": "padivattom",
    "name": "Padivattom",
    "zone": "ernakulam-central",
    "sortOrder": 354,
    "priorityTier": 3
  },
  {
    "slug": "padma-junction",
    "name": "Padma Junction",
    "zone": "ernakulam-central",
    "sortOrder": 355,
    "priorityTier": 3
  },
  {
    "slug": "palarivattom",
    "name": "Palarivattom",
    "zone": "edappally",
    "sortOrder": 356,
    "priorityTier": 1
  },
  {
    "slug": "palarivattom-bypass",
    "name": "Palarivattom Bypass",
    "zone": "edappally",
    "sortOrder": 357,
    "priorityTier": 3
  },
  {
    "slug": "palarivattom-civil-line-road",
    "name": "Palarivattom Civil Line Road",
    "zone": "edappally",
    "sortOrder": 358,
    "priorityTier": 3
  },
  {
    "slug": "palarivattom-junction",
    "name": "Palarivattom Junction",
    "zone": "edappally",
    "sortOrder": 359,
    "priorityTier": 3
  },
  {
    "slug": "palarivattom-pipeline",
    "name": "Palarivattom Pipeline",
    "zone": "edappally",
    "sortOrder": 360,
    "priorityTier": 3
  },
  {
    "slug": "pallikkara-kakkanad",
    "name": "Pallikkara Kakkanad",
    "zone": "kakkanad-infopark",
    "sortOrder": 361,
    "priorityTier": 1
  },
  {
    "slug": "pallippuram-kochi",
    "name": "Pallippuram Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 362,
    "priorityTier": 3
  },
  {
    "slug": "palluruthy",
    "name": "Palluruthy",
    "zone": "ernakulam-central",
    "sortOrder": 363,
    "priorityTier": 3
  },
  {
    "slug": "palluruthy-east",
    "name": "Palluruthy East",
    "zone": "ernakulam-central",
    "sortOrder": 364,
    "priorityTier": 3
  },
  {
    "slug": "palluruthy-kacheripady",
    "name": "Palluruthy Kacheripady",
    "zone": "ernakulam-central",
    "sortOrder": 365,
    "priorityTier": 3
  },
  {
    "slug": "palluruthy-veli",
    "name": "Palluruthy Veli",
    "zone": "ernakulam-central",
    "sortOrder": 366,
    "priorityTier": 3
  },
  {
    "slug": "panampilly-nagar",
    "name": "Panampilly Nagar",
    "zone": "ernakulam-central",
    "sortOrder": 367,
    "priorityTier": 1
  },
  {
    "slug": "panampilly-nagar-avenue",
    "name": "Panampilly Nagar Avenue",
    "zone": "ernakulam-central",
    "sortOrder": 368,
    "priorityTier": 3
  },
  {
    "slug": "panampilly-nagar-central",
    "name": "Panampilly Nagar Central",
    "zone": "ernakulam-central",
    "sortOrder": 369,
    "priorityTier": 3
  },
  {
    "slug": "panampilly-nagar-south",
    "name": "Panampilly Nagar South",
    "zone": "ernakulam-central",
    "sortOrder": 370,
    "priorityTier": 3
  },
  {
    "slug": "panangad-kochi",
    "name": "Panangad Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 371,
    "priorityTier": 3
  },
  {
    "slug": "panayappilly",
    "name": "Panayappilly",
    "zone": "ernakulam-central",
    "sortOrder": 372,
    "priorityTier": 3
  },
  {
    "slug": "parade-ground-fort-kochi",
    "name": "Parade Ground Fort Kochi",
    "zone": "fort-kochi",
    "sortOrder": 373,
    "priorityTier": 3
  },
  {
    "slug": "paravoor-kavala",
    "name": "Paravoor Kavala",
    "zone": "ernakulam-central",
    "sortOrder": 374,
    "priorityTier": 3
  },
  {
    "slug": "paravur-junction-aluva",
    "name": "Paravur Junction Aluva",
    "zone": "aluva",
    "sortOrder": 375,
    "priorityTier": 3
  },
  {
    "slug": "paravur-kavala-aluva",
    "name": "Paravur Kavala Aluva",
    "zone": "aluva",
    "sortOrder": 376,
    "priorityTier": 3
  },
  {
    "slug": "paravur-town",
    "name": "Paravur Town",
    "zone": "angamaly",
    "sortOrder": 377,
    "priorityTier": 3
  },
  {
    "slug": "pathadipalam",
    "name": "Pathadipalam",
    "zone": "ernakulam-central",
    "sortOrder": 378,
    "priorityTier": 3
  },
  {
    "slug": "pathalam",
    "name": "Pathalam",
    "zone": "ernakulam-central",
    "sortOrder": 379,
    "priorityTier": 3
  },
  {
    "slug": "pattimattom",
    "name": "Pattimattom",
    "zone": "ernakulam-central",
    "sortOrder": 380,
    "priorityTier": 3
  },
  {
    "slug": "perumanoor",
    "name": "Perumanoor",
    "zone": "ernakulam-central",
    "sortOrder": 381,
    "priorityTier": 3
  },
  {
    "slug": "perumanoor-junction",
    "name": "Perumanoor Junction",
    "zone": "ernakulam-central",
    "sortOrder": 382,
    "priorityTier": 3
  },
  {
    "slug": "perumbavoor",
    "name": "Perumbavoor",
    "zone": "angamaly",
    "sortOrder": 383,
    "priorityTier": 2
  },
  {
    "slug": "perumbavoor-market",
    "name": "Perumbavoor Market",
    "zone": "aluva",
    "sortOrder": 384,
    "priorityTier": 3
  },
  {
    "slug": "perumbavoor-mc-road",
    "name": "Perumbavoor Mc Road",
    "zone": "aluva",
    "sortOrder": 385,
    "priorityTier": 3
  },
  {
    "slug": "perumbavoor-town",
    "name": "Perumbavoor Town",
    "zone": "aluva",
    "sortOrder": 386,
    "priorityTier": 3
  },
  {
    "slug": "perumpadappu",
    "name": "Perumpadappu",
    "zone": "ernakulam-central",
    "sortOrder": 387,
    "priorityTier": 3
  },
  {
    "slug": "petta-metro-area",
    "name": "Petta Metro Area",
    "zone": "ernakulam-central",
    "sortOrder": 388,
    "priorityTier": 3
  },
  {
    "slug": "pettah-kochi",
    "name": "Pettah Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 389,
    "priorityTier": 3
  },
  {
    "slug": "pipeline-junction",
    "name": "Pipeline Junction",
    "zone": "ernakulam-central",
    "sortOrder": 390,
    "priorityTier": 3
  },
  {
    "slug": "piravom-road-area",
    "name": "Piravom Road Area",
    "zone": "ernakulam-central",
    "sortOrder": 391,
    "priorityTier": 3
  },
  {
    "slug": "pizhala",
    "name": "Pizhala",
    "zone": "ernakulam-central",
    "sortOrder": 392,
    "priorityTier": 3
  },
  {
    "slug": "ponekkara",
    "name": "Ponekkara",
    "zone": "ernakulam-central",
    "sortOrder": 393,
    "priorityTier": 3
  },
  {
    "slug": "ponekkara-east",
    "name": "Ponekkara East",
    "zone": "ernakulam-central",
    "sortOrder": 394,
    "priorityTier": 3
  },
  {
    "slug": "ponekkara-temple-area",
    "name": "Ponekkara Temple Area",
    "zone": "ernakulam-central",
    "sortOrder": 395,
    "priorityTier": 3
  },
  {
    "slug": "ponnumthuruthu-kochi",
    "name": "Ponnumthuruthu Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 396,
    "priorityTier": 3
  },
  {
    "slug": "ponnurunni",
    "name": "Ponnurunni",
    "zone": "ernakulam-central",
    "sortOrder": 397,
    "priorityTier": 3
  },
  {
    "slug": "ponnurunni-east",
    "name": "Ponnurunni East",
    "zone": "ernakulam-central",
    "sortOrder": 398,
    "priorityTier": 3
  },
  {
    "slug": "ponnurunni-junction",
    "name": "Ponnurunni Junction",
    "zone": "ernakulam-central",
    "sortOrder": 399,
    "priorityTier": 3
  },
  {
    "slug": "ponnurunni-railway-gate",
    "name": "Ponnurunni Railway Gate",
    "zone": "ernakulam-central",
    "sortOrder": 400,
    "priorityTier": 3
  },
  {
    "slug": "ponnurunni-vyttila",
    "name": "Ponnurunni Vyttila",
    "zone": "vyttila",
    "sortOrder": 401,
    "priorityTier": 3
  },
  {
    "slug": "poonithura",
    "name": "Poonithura",
    "zone": "ernakulam-central",
    "sortOrder": 402,
    "priorityTier": 3
  },
  {
    "slug": "poonithura-junction",
    "name": "Poonithura Junction",
    "zone": "ernakulam-central",
    "sortOrder": 403,
    "priorityTier": 3
  },
  {
    "slug": "poothotta",
    "name": "Poothotta",
    "zone": "ernakulam-central",
    "sortOrder": 404,
    "priorityTier": 3
  },
  {
    "slug": "pottakuzhi-junction",
    "name": "Pottakuzhi Junction",
    "zone": "ernakulam-central",
    "sortOrder": 405,
    "priorityTier": 3
  },
  {
    "slug": "pottakuzhy",
    "name": "Pottakuzhy",
    "zone": "ernakulam-central",
    "sortOrder": 406,
    "priorityTier": 3
  },
  {
    "slug": "premier-junction",
    "name": "Premier Junction",
    "zone": "ernakulam-central",
    "sortOrder": 407,
    "priorityTier": 3
  },
  {
    "slug": "princess-street",
    "name": "Princess Street",
    "zone": "ernakulam-central",
    "sortOrder": 408,
    "priorityTier": 3
  },
  {
    "slug": "providence-road",
    "name": "Providence Road",
    "zone": "ernakulam-central",
    "sortOrder": 409,
    "priorityTier": 3
  },
  {
    "slug": "pulinchodu",
    "name": "Pulinchodu",
    "zone": "ernakulam-central",
    "sortOrder": 410,
    "priorityTier": 3
  },
  {
    "slug": "pulivelipady",
    "name": "Pulivelipady",
    "zone": "ernakulam-central",
    "sortOrder": 411,
    "priorityTier": 3
  },
  {
    "slug": "pullardesam",
    "name": "Pullardesam",
    "zone": "ernakulam-central",
    "sortOrder": 412,
    "priorityTier": 3
  },
  {
    "slug": "pullepady",
    "name": "Pullepady",
    "zone": "ernakulam-central",
    "sortOrder": 413,
    "priorityTier": 3
  },
  {
    "slug": "puthencruz",
    "name": "Puthencruz",
    "zone": "ernakulam-central",
    "sortOrder": 414,
    "priorityTier": 3
  },
  {
    "slug": "puthenkurish",
    "name": "Puthenkurish",
    "zone": "ernakulam-central",
    "sortOrder": 415,
    "priorityTier": 3
  },
  {
    "slug": "puthenvelikkara",
    "name": "Puthenvelikkara",
    "zone": "ernakulam-central",
    "sortOrder": 416,
    "priorityTier": 3
  },
  {
    "slug": "puthiya-road",
    "name": "Puthiya Road",
    "zone": "ernakulam-central",
    "sortOrder": 417,
    "priorityTier": 3
  },
  {
    "slug": "puthiyakavu",
    "name": "Puthiyakavu",
    "zone": "ernakulam-central",
    "sortOrder": 418,
    "priorityTier": 3
  },
  {
    "slug": "puthukalavattom",
    "name": "Puthukalavattom",
    "zone": "ernakulam-central",
    "sortOrder": 419,
    "priorityTier": 3
  },
  {
    "slug": "puthuvype",
    "name": "Puthuvype",
    "zone": "ernakulam-central",
    "sortOrder": 420,
    "priorityTier": 3
  },
  {
    "slug": "puthuvype-beach",
    "name": "Puthuvype Beach",
    "zone": "ernakulam-central",
    "sortOrder": 421,
    "priorityTier": 3
  },
  {
    "slug": "rajagiri-college-area",
    "name": "Rajagiri College Area",
    "zone": "ernakulam-central",
    "sortOrder": 422,
    "priorityTier": 3
  },
  {
    "slug": "rajagiri-valley",
    "name": "Rajagiri Valley",
    "zone": "ernakulam-central",
    "sortOrder": 423,
    "priorityTier": 3
  },
  {
    "slug": "ravipuram",
    "name": "Ravipuram",
    "zone": "ernakulam-central",
    "sortOrder": 424,
    "priorityTier": 3
  },
  {
    "slug": "ravipuram-junction",
    "name": "Ravipuram Junction",
    "zone": "ernakulam-central",
    "sortOrder": 425,
    "priorityTier": 3
  },
  {
    "slug": "rayamangalam",
    "name": "Rayamangalam",
    "zone": "ernakulam-central",
    "sortOrder": 426,
    "priorityTier": 3
  },
  {
    "slug": "sahodaran-ayyappan-road",
    "name": "Sahodaran Ayyappan Road",
    "zone": "ernakulam-central",
    "sortOrder": 427,
    "priorityTier": 3
  },
  {
    "slug": "saudi-kochi",
    "name": "Saudi Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 428,
    "priorityTier": 3
  },
  {
    "slug": "seaport-airport-road",
    "name": "Seaport Airport Road",
    "zone": "ernakulam-central",
    "sortOrder": 429,
    "priorityTier": 3
  },
  {
    "slug": "seaport-airport-road-tripunithura",
    "name": "Seaport Airport Road Tripunithura",
    "zone": "vyttila",
    "sortOrder": 430,
    "priorityTier": 3
  },
  {
    "slug": "shanmugham-road",
    "name": "Shanmugham Road",
    "zone": "ernakulam-central",
    "sortOrder": 431,
    "priorityTier": 3
  },
  {
    "slug": "smartcity-kochi",
    "name": "Smartcity Kochi",
    "zone": "kakkanad-infopark",
    "sortOrder": 432,
    "priorityTier": 2
  },
  {
    "slug": "sn-junction",
    "name": "SN Junction",
    "zone": "ernakulam-central",
    "sortOrder": 433,
    "priorityTier": 3
  },
  {
    "slug": "south-chittoor",
    "name": "South Chittoor",
    "zone": "ernakulam-central",
    "sortOrder": 434,
    "priorityTier": 3
  },
  {
    "slug": "south-kalamassery",
    "name": "South Kalamassery",
    "zone": "ernakulam-central",
    "sortOrder": 435,
    "priorityTier": 3
  },
  {
    "slug": "south-kalamassery-metro-area",
    "name": "South Kalamassery Metro Area",
    "zone": "ernakulam-central",
    "sortOrder": 436,
    "priorityTier": 3
  },
  {
    "slug": "sreemoolanagaram",
    "name": "Sreemoolanagaram",
    "zone": "ernakulam-central",
    "sortOrder": 437,
    "priorityTier": 3
  },
  {
    "slug": "srm-road",
    "name": "SRM Road",
    "zone": "ernakulam-central",
    "sortOrder": 438,
    "priorityTier": 3
  },
  {
    "slug": "stadium-area-kaloor",
    "name": "Stadium Area Kaloor",
    "zone": "ernakulam-central",
    "sortOrder": 439,
    "priorityTier": 3
  },
  {
    "slug": "stadium-junction-kaloor",
    "name": "Stadium Junction Kaloor",
    "zone": "ernakulam-central",
    "sortOrder": 440,
    "priorityTier": 3
  },
  {
    "slug": "stadium-link-road",
    "name": "Stadium Link Road",
    "zone": "ernakulam-central",
    "sortOrder": 441,
    "priorityTier": 3
  },
  {
    "slug": "statue-junction-tripunithura",
    "name": "Statue Junction Tripunithura",
    "zone": "vyttila",
    "sortOrder": 442,
    "priorityTier": 3
  },
  {
    "slug": "tatapuram",
    "name": "Tatapuram",
    "zone": "ernakulam-central",
    "sortOrder": 443,
    "priorityTier": 3
  },
  {
    "slug": "thamaraparambu",
    "name": "Thamaraparambu",
    "zone": "ernakulam-central",
    "sortOrder": 444,
    "priorityTier": 3
  },
  {
    "slug": "thammanam",
    "name": "Thammanam",
    "zone": "ernakulam-central",
    "sortOrder": 445,
    "priorityTier": 3
  },
  {
    "slug": "thammanam-junction",
    "name": "Thammanam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 446,
    "priorityTier": 3
  },
  {
    "slug": "thammanam-pullepady-road",
    "name": "Thammanam Pullepady Road",
    "zone": "ernakulam-central",
    "sortOrder": 447,
    "priorityTier": 3
  },
  {
    "slug": "thanthonnithuruthu",
    "name": "Thanthonnithuruthu",
    "zone": "ernakulam-central",
    "sortOrder": 448,
    "priorityTier": 3
  },
  {
    "slug": "tharebhagam",
    "name": "Tharebhagam",
    "zone": "ernakulam-central",
    "sortOrder": 449,
    "priorityTier": 3
  },
  {
    "slug": "thattaazham",
    "name": "Thattaazham",
    "zone": "ernakulam-central",
    "sortOrder": 450,
    "priorityTier": 3
  },
  {
    "slug": "thazhuppu",
    "name": "Thazhuppu",
    "zone": "ernakulam-central",
    "sortOrder": 451,
    "priorityTier": 3
  },
  {
    "slug": "thengod",
    "name": "Thengod",
    "zone": "ernakulam-central",
    "sortOrder": 452,
    "priorityTier": 3
  },
  {
    "slug": "thengod-junction",
    "name": "Thengod Junction",
    "zone": "ernakulam-central",
    "sortOrder": 453,
    "priorityTier": 3
  },
  {
    "slug": "thevara",
    "name": "Thevara",
    "zone": "ernakulam-central",
    "sortOrder": 454,
    "priorityTier": 3
  },
  {
    "slug": "thevara-ferry",
    "name": "Thevara Ferry",
    "zone": "ernakulam-central",
    "sortOrder": 455,
    "priorityTier": 3
  },
  {
    "slug": "thevara-junction",
    "name": "Thevara Junction",
    "zone": "ernakulam-central",
    "sortOrder": 456,
    "priorityTier": 3
  },
  {
    "slug": "thevara-kundannoor-road",
    "name": "Thevara Kundannoor Road",
    "zone": "ernakulam-central",
    "sortOrder": 457,
    "priorityTier": 3
  },
  {
    "slug": "thiruvankulam",
    "name": "Thiruvankulam",
    "zone": "ernakulam-central",
    "sortOrder": 458,
    "priorityTier": 3
  },
  {
    "slug": "thiruvankulam-junction",
    "name": "Thiruvankulam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 459,
    "priorityTier": 3
  },
  {
    "slug": "thoppil-junction",
    "name": "Thoppil Junction",
    "zone": "ernakulam-central",
    "sortOrder": 460,
    "priorityTier": 3
  },
  {
    "slug": "thoppumpady",
    "name": "Thoppumpady",
    "zone": "ernakulam-central",
    "sortOrder": 461,
    "priorityTier": 3
  },
  {
    "slug": "thoppumpady-junction",
    "name": "Thoppumpady Junction",
    "zone": "ernakulam-central",
    "sortOrder": 462,
    "priorityTier": 3
  },
  {
    "slug": "thottakkattukara",
    "name": "Thottakkattukara",
    "zone": "ernakulam-central",
    "sortOrder": 463,
    "priorityTier": 3
  },
  {
    "slug": "thottumugham",
    "name": "Thottumugham",
    "zone": "ernakulam-central",
    "sortOrder": 464,
    "priorityTier": 3
  },
  {
    "slug": "thrikkakara",
    "name": "Thrikkakara",
    "zone": "ernakulam-central",
    "sortOrder": 465,
    "priorityTier": 2
  },
  {
    "slug": "thrikkakara-north",
    "name": "Thrikkakara North",
    "zone": "ernakulam-central",
    "sortOrder": 466,
    "priorityTier": 3
  },
  {
    "slug": "thrikkakara-south",
    "name": "Thrikkakara South",
    "zone": "ernakulam-central",
    "sortOrder": 467,
    "priorityTier": 3
  },
  {
    "slug": "thrikkakara-temple-area",
    "name": "Thrikkakara Temple Area",
    "zone": "ernakulam-central",
    "sortOrder": 468,
    "priorityTier": 3
  },
  {
    "slug": "thrikkanarvattom",
    "name": "Thrikkanarvattom",
    "zone": "ernakulam-central",
    "sortOrder": 469,
    "priorityTier": 3
  },
  {
    "slug": "thuravoor-angamaly",
    "name": "Thuravoor Angamaly",
    "zone": "angamaly",
    "sortOrder": 470,
    "priorityTier": 3
  },
  {
    "slug": "thuravoor-cherthala",
    "name": "Thuravoor Cherthala",
    "zone": "ernakulam-central",
    "sortOrder": 471,
    "priorityTier": 3
  },
  {
    "slug": "thykoodam",
    "name": "Thykoodam",
    "zone": "ernakulam-central",
    "sortOrder": 472,
    "priorityTier": 3
  },
  {
    "slug": "thykoodam-junction",
    "name": "Thykoodam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 473,
    "priorityTier": 3
  },
  {
    "slug": "tripunithura",
    "name": "Tripunithura",
    "zone": "vyttila",
    "sortOrder": 474,
    "priorityTier": 1
  },
  {
    "slug": "tripunithura-east",
    "name": "Tripunithura East",
    "zone": "vyttila",
    "sortOrder": 475,
    "priorityTier": 3
  },
  {
    "slug": "tripunithura-petta",
    "name": "Tripunithura Petta",
    "zone": "vyttila",
    "sortOrder": 476,
    "priorityTier": 3
  },
  {
    "slug": "tripunithura-railway-station-area",
    "name": "Tripunithura Railway Station Area",
    "zone": "vyttila",
    "sortOrder": 477,
    "priorityTier": 3
  },
  {
    "slug": "tripunithura-west",
    "name": "Tripunithura West",
    "zone": "vyttila",
    "sortOrder": 478,
    "priorityTier": 3
  },
  {
    "slug": "uc-college-aluva",
    "name": "UC College Aluva",
    "zone": "aluva",
    "sortOrder": 479,
    "priorityTier": 3
  },
  {
    "slug": "udayamperoor",
    "name": "Udayamperoor",
    "zone": "ernakulam-central",
    "sortOrder": 480,
    "priorityTier": 3
  },
  {
    "slug": "udayamperoor-junction",
    "name": "Udayamperoor Junction",
    "zone": "ernakulam-central",
    "sortOrder": 481,
    "priorityTier": 3
  },
  {
    "slug": "udyogamandal",
    "name": "Udyogamandal",
    "zone": "ernakulam-central",
    "sortOrder": 482,
    "priorityTier": 3
  },
  {
    "slug": "uliyannoor",
    "name": "Uliyannoor",
    "zone": "ernakulam-central",
    "sortOrder": 483,
    "priorityTier": 3
  },
  {
    "slug": "vadakkekara",
    "name": "Vadakkekara",
    "zone": "ernakulam-central",
    "sortOrder": 484,
    "priorityTier": 3
  },
  {
    "slug": "vadavucode",
    "name": "Vadavucode",
    "zone": "ernakulam-central",
    "sortOrder": 485,
    "priorityTier": 3
  },
  {
    "slug": "vadavucode-puthencruz",
    "name": "Vadavucode Puthencruz",
    "zone": "ernakulam-central",
    "sortOrder": 486,
    "priorityTier": 3
  },
  {
    "slug": "vaduthala",
    "name": "Vaduthala",
    "zone": "ernakulam-central",
    "sortOrder": 487,
    "priorityTier": 3
  },
  {
    "slug": "vaduthala-east",
    "name": "Vaduthala East",
    "zone": "ernakulam-central",
    "sortOrder": 488,
    "priorityTier": 3
  },
  {
    "slug": "vaduthala-west",
    "name": "Vaduthala West",
    "zone": "ernakulam-central",
    "sortOrder": 489,
    "priorityTier": 3
  },
  {
    "slug": "valanjambalam",
    "name": "Valanjambalam",
    "zone": "ernakulam-central",
    "sortOrder": 490,
    "priorityTier": 3
  },
  {
    "slug": "vallarpadam",
    "name": "Vallarpadam",
    "zone": "ernakulam-central",
    "sortOrder": 491,
    "priorityTier": 3
  },
  {
    "slug": "vallarpadam-container-terminal",
    "name": "Vallarpadam Container Terminal",
    "zone": "ernakulam-central",
    "sortOrder": 492,
    "priorityTier": 3
  },
  {
    "slug": "vallarpadam-junction",
    "name": "Vallarpadam Junction",
    "zone": "ernakulam-central",
    "sortOrder": 493,
    "priorityTier": 3
  },
  {
    "slug": "vallathol-junction",
    "name": "Vallathol Junction",
    "zone": "ernakulam-central",
    "sortOrder": 494,
    "priorityTier": 3
  },
  {
    "slug": "varapuzha",
    "name": "Varapuzha",
    "zone": "ernakulam-central",
    "sortOrder": 495,
    "priorityTier": 3
  },
  {
    "slug": "varapuzha-landing",
    "name": "Varapuzha Landing",
    "zone": "ernakulam-central",
    "sortOrder": 496,
    "priorityTier": 3
  },
  {
    "slug": "vazhakkala",
    "name": "Vazhakkala",
    "zone": "ernakulam-central",
    "sortOrder": 497,
    "priorityTier": 3
  },
  {
    "slug": "vazhakkala-bypass",
    "name": "Vazhakkala Bypass",
    "zone": "ernakulam-central",
    "sortOrder": 498,
    "priorityTier": 3
  },
  {
    "slug": "vazhakkala-junction",
    "name": "Vazhakkala Junction",
    "zone": "ernakulam-central",
    "sortOrder": 499,
    "priorityTier": 3
  },
  {
    "slug": "vazhakkala-kochi",
    "name": "Vazhakkala Kochi",
    "zone": "ernakulam-central",
    "sortOrder": 500,
    "priorityTier": 3
  },
  {
    "slug": "vazhakulam-ernakulam",
    "name": "Vazhakulam Ernakulam",
    "zone": "ernakulam-central",
    "sortOrder": 501,
    "priorityTier": 3
  },
  {
    "slug": "vazhakulam-junction-ernakulam",
    "name": "Vazhakulam Junction Ernakulam",
    "zone": "ernakulam-central",
    "sortOrder": 502,
    "priorityTier": 3
  },
  {
    "slug": "veli-fort-kochi",
    "name": "Veli Fort Kochi",
    "zone": "fort-kochi",
    "sortOrder": 503,
    "priorityTier": 3
  },
  {
    "slug": "vengola",
    "name": "Vengola",
    "zone": "ernakulam-central",
    "sortOrder": 504,
    "priorityTier": 3
  },
  {
    "slug": "vennala",
    "name": "Vennala",
    "zone": "ernakulam-central",
    "sortOrder": 505,
    "priorityTier": 3
  },
  {
    "slug": "vennala-arakkakadavu",
    "name": "Vennala Arakkakadavu",
    "zone": "ernakulam-central",
    "sortOrder": 506,
    "priorityTier": 3
  },
  {
    "slug": "vennala-high-school-junction",
    "name": "Vennala High School Junction",
    "zone": "ernakulam-central",
    "sortOrder": 507,
    "priorityTier": 3
  },
  {
    "slug": "vennala-junction",
    "name": "Vennala Junction",
    "zone": "ernakulam-central",
    "sortOrder": 508,
    "priorityTier": 3
  },
  {
    "slug": "vypin",
    "name": "Vypin",
    "zone": "fort-kochi",
    "sortOrder": 509,
    "priorityTier": 3
  },
  {
    "slug": "vypin-beach",
    "name": "Vypin Beach",
    "zone": "fort-kochi",
    "sortOrder": 510,
    "priorityTier": 3
  },
  {
    "slug": "vypin-junction",
    "name": "Vypin Junction",
    "zone": "fort-kochi",
    "sortOrder": 511,
    "priorityTier": 3
  },
  {
    "slug": "vyttila",
    "name": "Vyttila",
    "zone": "vyttila",
    "sortOrder": 512,
    "priorityTier": 1
  },
  {
    "slug": "vyttila-bypass",
    "name": "Vyttila Bypass",
    "zone": "vyttila",
    "sortOrder": 513,
    "priorityTier": 3
  },
  {
    "slug": "vyttila-hub-area",
    "name": "Vyttila Hub Area",
    "zone": "vyttila",
    "sortOrder": 514,
    "priorityTier": 3
  },
  {
    "slug": "vyttila-janatha",
    "name": "Vyttila Janatha",
    "zone": "vyttila",
    "sortOrder": 515,
    "priorityTier": 3
  },
  {
    "slug": "vyttila-junction",
    "name": "Vyttila Junction",
    "zone": "vyttila",
    "sortOrder": 516,
    "priorityTier": 3
  },
  {
    "slug": "vyttila-mobility-hub",
    "name": "Vyttila Mobility Hub",
    "zone": "vyttila",
    "sortOrder": 517,
    "priorityTier": 3
  },
  {
    "slug": "vyttila-power-house-junction",
    "name": "Vyttila Power House Junction",
    "zone": "vyttila",
    "sortOrder": 518,
    "priorityTier": 3
  },
  {
    "slug": "vyttila-service-road",
    "name": "Vyttila Service Road",
    "zone": "vyttila",
    "sortOrder": 519,
    "priorityTier": 3
  },
  {
    "slug": "warriam-road",
    "name": "Warriam Road",
    "zone": "ernakulam-central",
    "sortOrder": 520,
    "priorityTier": 3
  },
  {
    "slug": "west-kadungalloor",
    "name": "West Kadungalloor",
    "zone": "ernakulam-central",
    "sortOrder": 521,
    "priorityTier": 3
  },
  {
    "slug": "willingdon-island",
    "name": "Willingdon Island",
    "zone": "fort-kochi",
    "sortOrder": 522,
    "priorityTier": 3
  },
  {
    "slug": "willingdon-island-naval-base",
    "name": "Willingdon Island Naval Base",
    "zone": "fort-kochi",
    "sortOrder": 523,
    "priorityTier": 3
  },
  {
    "slug": "wonderla-kochi-area",
    "name": "Wonderla Kochi Area",
    "zone": "ernakulam-central",
    "sortOrder": 524,
    "priorityTier": 3
  }
];

export const KOCHI_AREA_COUNT = 524;

export function getKochiAreaBySlug(slug: string): KochiArea | undefined {
  return KOCHI_AREAS.find((a) => a.slug === slug);
}
